// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: examples/stories/ui/tabs/tab-group-demo/tab-group-demo.story.ts#section[0] "Three-tab navigation"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxTab, CngxTabLabel, CngxTabContent } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';

@Component({
  selector: 'app-tab-group-three-tab-navigation',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxTabGroup, CngxTab, CngxTabLabel, CngxTabContent],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-tab-group [(activeIndex)]="active" aria-label="Settings tabs">
        <div cngxTab [label]="'Profile'">
          <ng-template cngxTabLabel>Profile</ng-template>
          <ng-template cngxTabContent>
            <p>Profile content — name, avatar, bio.</p>
          </ng-template>
        </div>
        <div cngxTab [label]="'Account'">
          <ng-template cngxTabLabel>Account</ng-template>
          <ng-template cngxTabContent>
            <p>Account content — email, password, authentication method.</p>
          </ng-template>
        </div>
        <div cngxTab [label]="'Notifications'">
          <ng-template cngxTabLabel>Notifications</ng-template>
          <ng-template cngxTabContent>
            <p>Notifications content — email + push channel preferences.</p>
          </ng-template>
        </div>
      </cngx-tab-group>
      <div class="event-grid" style="margin-top:12px;gap:8px">
        <div class="event-row"><span class="event-label">Active tab</span><span class="event-value">{{ active() }}</span></div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class TabGroupThreeTabNavigation {
  protected readonly _exTitle: string = 'Tabs — horizontal';
  protected readonly _exDescription: string = '<code>&lt;cngx-tab-group&gt;</code> in horizontal orientation (default). W3C Tabs ARIA pattern — <code>role="tablist"</code> strip, <code>role="tab"</code> headers, <code>role="tabpanel"</code> bodies. Roving tabindex via composed host-directive.';
  protected readonly _exSectionTitle: string = 'Three-tab navigation';
  protected readonly _exSubtitle: string = 'Bind <code>[(activeIndex)]</code> for two-way control. ArrowLeft / ArrowRight cycle tabs; Home / End jump to ends; Tab leaves the strip and lands inside the active panel.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'organism' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'audience', value: 'a11y' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'composition' }, { dim: 'focus', value: 'a11y-pattern' }, { dim: 'focus', value: 'behavior' }];
  protected readonly _exTs: string = `import { CngxTab, CngxTabLabel, CngxTabContent } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';

protected readonly active = signal(0);`;
  protected readonly _exHtml: string = `<cngx-tab-group [(activeIndex)]="active" aria-label="Settings tabs">
  <div cngxTab [label]="'Profile'">
    <ng-template cngxTabLabel>Profile</ng-template>
    <ng-template cngxTabContent>
      <p>Profile content — name, avatar, bio.</p>
    </ng-template>
  </div>
  <div cngxTab [label]="'Account'">
    <ng-template cngxTabLabel>Account</ng-template>
    <ng-template cngxTabContent>
      <p>Account content — email, password, authentication method.</p>
    </ng-template>
  </div>
  <div cngxTab [label]="'Notifications'">
    <ng-template cngxTabLabel>Notifications</ng-template>
    <ng-template cngxTabContent>
      <p>Notifications content — email + push channel preferences.</p>
    </ng-template>
  </div>
</cngx-tab-group>`;
  protected readonly active = signal(0);
}
