// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/ui/feedback/banner-demo/banner-demo.story.ts#section[0] "System Banners"

import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CngxBanner } from '@cngx/ui/feedback';

@Component({
  selector: 'app-banner-system-banners',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div style="display:flex;flex-wrap:wrap;gap:8px">
        <button (click)="showOffline()" class="chip">Offline</button>
        <button (click)="showMaintenance()" class="chip">Maintenance</button>
        <button (click)="showSessionTimeout()" class="chip">Session Timeout (async)</button>
        <button (click)="showNewVersion()" class="chip">New Version</button>
        <button (click)="dismissOffline()" class="chip">Dismiss Offline</button>
        <button (click)="dismissAll()" class="chip">Dismiss All</button>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class BannerSystemBanners {
  protected readonly _exTitle: string = 'Banner';
  protected readonly _exDescription: string = 'Global system-level banners for session timeout, maintenance, offline status. Sticky top, always persistent, dedup by id, async action lifecycle.';
  protected readonly _exSectionTitle: string = 'System Banners';
  protected readonly _exSubtitle: string = 'Inject <code>CngxBanner</code> and call <code>.show()</code>. Banners are always persistent — dismiss programmatically via <code>dismiss(id)</code>. <code>role="alert"</code> for error/warning, <code>aria-live="assertive"</code> for error only.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'organism' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'audience', value: 'a11y' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'async-state' }, { dim: 'focus', value: 'visual-variants' }, { dim: 'focus', value: 'a11y-pattern' }];
  protected readonly _exTs: string = `import { CngxBanner } from '@cngx/ui/feedback';

private readonly banner = inject(CngxBanner);

// ── Basic demos ──
protected showOffline(): void {
  this.banner.show({
    message: 'You are offline. Changes will sync when reconnected.',
    id: 'net:offline',
    severity: 'error',
  });
}

protected showMaintenance(): void {
  this.banner.show({
    message: 'Scheduled maintenance tonight at 22:00 UTC.',
    id: 'sys:maintenance',
    severity: 'info',
    action: { label: 'More Info', handler: () => alert('Maintenance details...') },
  });
}

protected showSessionTimeout(): void {
  this.banner.show({
    message: 'Your session expires in 5 minutes.',
    id: 'auth:session-timeout',
    severity: 'warning',
    action: {
      label: 'Extend',
      handler: () => new Promise<void>(r => setTimeout(r, 1500)),
    },
  });
}

protected showNewVersion(): void {
  this.banner.show({
    message: 'A new version is available.',
    id: 'app:version',
    severity: 'info',
    action: { label: 'Refresh', handler: () => location.reload() },
  });
}

protected dismissOffline(): void {
  this.banner.dismiss('net:offline');
}

protected dismissAll(): void {
  this.banner.dismissAll();
}

// ── Update demo ──
private countdown = 5;
private countdownInterval: ReturnType<typeof setInterval> | undefined;

protected startCountdown(): void {
  this.countdown = 5;
  this.banner.show({
    message: 'Session expires in 5 minutes.',
    id: 'auth:countdown',
    severity: 'warning',
    dismissible: false,
  });
  clearInterval(this.countdownInterval);
  this.countdownInterval = setInterval(() => {
    this.countdown--;
    if (this.countdown <= 0) {
      clearInterval(this.countdownInterval);
      this.banner.dismiss('auth:countdown');
    } else {
      this.banner.update('auth:countdown', {
        message: 'Session expires in ' + this.countdown + ' minutes.',
        severity: this.countdown <= 2 ? 'error' : 'warning',
      });
    }
  }, 1000);
}

// ── Async action demo ──
protected showAsyncAction(): void {
  this.banner.show({
    message: 'Payment method expired.',
    id: 'billing:payment',
    severity: 'error',
    action: {
      label: 'Update Payment',
      handler: () => new Promise<void>((resolve, reject) => {
        setTimeout(() => Math.random() > 0.5 ? resolve() : reject(new Error('Card declined')), 2000);
      }),
    },
  });
}`;
  protected readonly _exHtml: string = `<div style="display:flex;flex-wrap:wrap;gap:8px">
  <button (click)="showOffline()" class="chip">Offline</button>
  <button (click)="showMaintenance()" class="chip">Maintenance</button>
  <button (click)="showSessionTimeout()" class="chip">Session Timeout (async)</button>
  <button (click)="showNewVersion()" class="chip">New Version</button>
  <button (click)="dismissOffline()" class="chip">Dismiss Offline</button>
  <button (click)="dismissAll()" class="chip">Dismiss All</button>
</div>`;
  private readonly banner = inject(CngxBanner);

    // ── Basic demos ──
    protected showOffline(): void {
      this.banner.show({
        message: 'You are offline. Changes will sync when reconnected.',
        id: 'net:offline',
        severity: 'error',
      });
    }

    protected showMaintenance(): void {
      this.banner.show({
        message: 'Scheduled maintenance tonight at 22:00 UTC.',
        id: 'sys:maintenance',
        severity: 'info',
        action: { label: 'More Info', handler: () => alert('Maintenance details...') },
      });
    }

    protected showSessionTimeout(): void {
      this.banner.show({
        message: 'Your session expires in 5 minutes.',
        id: 'auth:session-timeout',
        severity: 'warning',
        action: {
          label: 'Extend',
          handler: () => new Promise<void>(r => setTimeout(r, 1500)),
        },
      });
    }

    protected showNewVersion(): void {
      this.banner.show({
        message: 'A new version is available.',
        id: 'app:version',
        severity: 'info',
        action: { label: 'Refresh', handler: () => location.reload() },
      });
    }

    protected dismissOffline(): void {
      this.banner.dismiss('net:offline');
    }

    protected dismissAll(): void {
      this.banner.dismissAll();
    }

    // ── Update demo ──
    private countdown = 5;
    private countdownInterval: ReturnType<typeof setInterval> | undefined;

    protected startCountdown(): void {
      this.countdown = 5;
      this.banner.show({
        message: 'Session expires in 5 minutes.',
        id: 'auth:countdown',
        severity: 'warning',
        dismissible: false,
      });
      clearInterval(this.countdownInterval);
      this.countdownInterval = setInterval(() => {
        this.countdown--;
        if (this.countdown <= 0) {
          clearInterval(this.countdownInterval);
          this.banner.dismiss('auth:countdown');
        } else {
          this.banner.update('auth:countdown', {
            message: 'Session expires in ' + this.countdown + ' minutes.',
            severity: this.countdown <= 2 ? 'error' : 'warning',
          });
        }
      }, 1000);
    }

    // ── Async action demo ──
    protected showAsyncAction(): void {
      this.banner.show({
        message: 'Payment method expired.',
        id: 'billing:payment',
        severity: 'error',
        action: {
          label: 'Update Payment',
          handler: () => new Promise<void>((resolve, reject) => {
            setTimeout(() => Math.random() > 0.5 ? resolve() : reject(new Error('Card declined')), 2000);
          }),
        },
      });
    }
}
