// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/listbox-forms-demo/listbox-forms-demo.story.ts#section[2] "Material mat-select via CngxBindField"

import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { form, schema, required, minLength, submit } from '@angular/forms/signals';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { toSignal } from '@angular/core/rxjs-interop';
import { CngxFormField, CngxLabel, CngxFieldErrors, adaptFormControl, CngxBindField } from '@cngx/forms/field';
import { MatSelect } from '@angular/material/select';
import { MatOption } from '@angular/material/core';

@Component({
  selector: 'app-listbox-forms-material-mat-select-via-cngxbindfield',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxFormField, CngxLabel, CngxFieldErrors, CngxBindField, MatSelect, MatOption, ReactiveFormsModule],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-form-field [field]="matSelectField">
        <label cngxLabel>Größe</label>
        <mat-select cngxBindField
                    [formControl]="matSelectControl"
                    placeholder="Bitte wählen"
                    style="min-width:200px;display:inline-block">
          <mat-option value="s">Small</mat-option>
          <mat-option value="m">Medium</mat-option>
          <mat-option value="l">Large</mat-option>
          <mat-option value="xl">X-Large</mat-option>
        </mat-select>
        <cngx-field-errors />
      </cngx-form-field>
      <div class="event-grid" style="margin-top:12px">
        <div class="event-row">
          <span class="event-label">mat-select value</span>
          <span class="event-value">{{ matSelectValue() || '—' }}</span>
        </div>
        <div class="event-row">
          <span class="event-label">Valid</span>
          <span class="event-value">{{ matSelectControl.valid ? 'yes' : 'no' }}</span>
        </div>
        <div class="event-row">
          <span class="event-label">Touched</span>
          <span class="event-value">{{ matSelectControl.touched ? 'yes' : 'no' }}</span>
        </div>
        <div class="event-row" style="margin-top:8px">
          <button type="button" class="chip" (click)="handleMatSelectSubmit()">Touch</button>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class ListboxFormsMaterialMatSelectViaCngxbindfield {
  protected readonly _exTitle: string = 'Listbox Forms';
  protected readonly _exDescription: string = 'CngxListbox integrated into &lt;cngx-form-field&gt; via CngxListboxFieldBridge, plus the universal CngxBindField bridge for any other control (mat-select, native inputs, custom controls).';
  protected readonly _exSectionTitle: string = 'Material mat-select via CngxBindField';
  protected readonly _exSubtitle: string = 'Universal bridge pattern: <code>[cngxBindField]</code> on any Material / native / custom control. All form-field state (ID, empty, focused, disabled, errorState) derives from the bound field via the presenter — no control-specific bridge needed.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxListboxFieldBridge', 'CngxBindField', 'CngxListbox', 'CngxOption', 'CngxFormField'];
  protected readonly _exTs: string = `import { form, schema, required, minLength, submit } from '@angular/forms/signals';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { toSignal } from '@angular/core/rxjs-interop';
import { CngxFormField, CngxLabel, CngxFieldErrors, adaptFormControl, CngxBindField } from '@cngx/forms/field';
import { MatSelect } from '@angular/material/select';
import { MatOption } from '@angular/material/core';

// ── Signal Forms single ──────────────────────────────────
private readonly singleModel = signal<{ color: string }>({ color: '' });
private readonly singleSchema = schema<{ color: string }>((root) => {
  required(root.color);
});
protected readonly singleForm = form(this.singleModel, this.singleSchema);

// ── Signal Forms multi ───────────────────────────────────
private readonly multiModel = signal<{ toppings: string[] }>({ toppings: [] });
private readonly multiSchema = schema<{ toppings: string[] }>((root) => {
  minLength(root.toppings, 2);
});
protected readonly multiForm = form(this.multiModel, this.multiSchema);

// ── Reactive Forms single ────────────────────────────────
protected readonly rfControl = new FormControl<string>('green', { validators: [Validators.required], nonNullable: true });
protected readonly rfField = adaptFormControl(this.rfControl, 'color', inject(DestroyRef));
protected readonly rfValue = toSignal(this.rfControl.valueChanges, { initialValue: this.rfControl.value });
protected readonly rfTouched = signal(false);

// ── mat-select via CngxBindField ─────────────────────────
protected readonly matSelectControl = new FormControl<string>('', { validators: [Validators.required], nonNullable: true });
protected readonly matSelectField = adaptFormControl(this.matSelectControl, 'size', inject(DestroyRef));
protected readonly matSelectValue = toSignal(this.matSelectControl.valueChanges, { initialValue: this.matSelectControl.value });

protected handleSingleSubmit(): void {
  submit(this.singleForm, async () => []);
}
protected handleMultiSubmit(): void {
  submit(this.multiForm, async () => []);
}
protected handleMatSelectSubmit(): void {
  this.matSelectField().markAsTouched();
}`;
  protected readonly _exHtml: string = `<cngx-form-field [field]="matSelectField">
  <label cngxLabel>Größe</label>
  <mat-select cngxBindField
              [formControl]="matSelectControl"
              placeholder="Bitte wählen"
              style="min-width:200px;display:inline-block">
    <mat-option value="s">Small</mat-option>
    <mat-option value="m">Medium</mat-option>
    <mat-option value="l">Large</mat-option>
    <mat-option value="xl">X-Large</mat-option>
  </mat-select>
  <cngx-field-errors />
</cngx-form-field>`;
  // ── Signal Forms single ──────────────────────────────────
    private readonly singleModel = signal<{ color: string }>({ color: '' });
    private readonly singleSchema = schema<{ color: string }>((root) => {
      required(root.color);
    });
    protected readonly singleForm = form(this.singleModel, this.singleSchema);

    // ── Signal Forms multi ───────────────────────────────────
    private readonly multiModel = signal<{ toppings: string[] }>({ toppings: [] });
    private readonly multiSchema = schema<{ toppings: string[] }>((root) => {
      minLength(root.toppings, 2);
    });
    protected readonly multiForm = form(this.multiModel, this.multiSchema);

    // ── Reactive Forms single ────────────────────────────────
    protected readonly rfControl = new FormControl<string>('green', { validators: [Validators.required], nonNullable: true });
    protected readonly rfField = adaptFormControl(this.rfControl, 'color', inject(DestroyRef));
    protected readonly rfValue = toSignal(this.rfControl.valueChanges, { initialValue: this.rfControl.value });
    protected readonly rfTouched = signal(false);

    // ── mat-select via CngxBindField ─────────────────────────
    protected readonly matSelectControl = new FormControl<string>('', { validators: [Validators.required], nonNullable: true });
    protected readonly matSelectField = adaptFormControl(this.matSelectControl, 'size', inject(DestroyRef));
    protected readonly matSelectValue = toSignal(this.matSelectControl.valueChanges, { initialValue: this.matSelectControl.value });

    protected handleSingleSubmit(): void {
      submit(this.singleForm, async () => []);
    }
    protected handleMultiSubmit(): void {
      submit(this.multiForm, async () => []);
    }
    protected handleMatSelectSubmit(): void {
      this.matSelectField().markAsTouched();
    }
}
