// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/common/display/tag-demo/tag-demo.story.ts

import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ExampleCardComponent } from '../../../../shared/example-card.component';
import { DocShellComponent } from '../../../../shared/doc-shell.component';
import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';

@Component({
  selector: 'app-tag-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxTag,
    CngxAvatar,
    CngxIcon,
  ],
  template: `
    <app-doc-shell title="Tag"
      description="Decorative label / badge / status indicator. Dual selector ([cngxTag] and <cngx-tag>) so it composes onto any host element including <a> for link-mode tags. Removable affordances live in CngxChip; clickable interactions live on native <button cngxTag> / <a cngxTag>."
      overview="<p><code>[cngxTag]</code> applies host classes for variant / color / size / truncate / maxWidth. Predefined colours (<code>neutral</code>, <code>success</code>, <code>warning</code>, <code>error</code>, <code>info</code>) cascade through <code>--cngx-tag-{name}-*</code> custom properties; open-string colours emit a <code>data-color=&quot;…&quot;</code> attribute consumers can theme directly.</p>"
      [apiComponents]="['CngxTag', 'CngxIcon', 'CngxAvatar']">
      <app-example-card title="Variant matrix"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0"
        [sourceCss]="_srcCss0">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag variant="filled" color="success">Filled</span>
    <span cngxTag variant="outline" color="success">Outline</span>
    <span cngxTag variant="subtle" color="success">Subtle</span>
  </div>
      </app-example-card>
      <app-example-card title="Color palette"
        [subtitle]="_s1"
        [sourceHtml]="_srcHtml1"
        [sourceTs]="_srcTs1"
        [sourceCss]="_srcCss1">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="neutral">Neutral</span>
    <span cngxTag color="success">Active</span>
    <span cngxTag color="warning">Pending</span>
    <span cngxTag color="error">Failed</span>
    <span cngxTag color="info">Beta</span>
    <span cngxTag color="my-brand" style="--cngx-tag-bg: #4f46e5; --cngx-tag-color: #ffffff;">Branded</span>
  </div>
      </app-example-card>
      <app-example-card title="Density"
        [subtitle]="_s2"
        [sourceHtml]="_srcHtml2"
        [sourceTs]="_srcTs2"
        [sourceCss]="_srcCss2">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag size="sm" color="info">Small</span>
    <span cngxTag size="md" color="info">Medium</span>
    <span cngxTag size="lg" color="info">Large</span>
    <span cngxTag size="xl" color="info">Extra large</span>
  </div>
      </app-example-card>
      <app-example-card title="Truncate + maxWidth"
        [subtitle]="_s3"
        [sourceHtml]="_srcHtml3"
        [sourceTs]="_srcTs3"
        [sourceCss]="_srcCss3">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="neutral" [truncate]="true" maxWidth="8rem">A very long taxonomy label that overflows</span>
    <span cngxTag color="info" [truncate]="true" maxWidth="12rem">Another lengthy descriptor here</span>
  </div>
      </app-example-card>
      <app-example-card title="Link mode"
        [subtitle]="_s4"
        [sourceHtml]="_srcHtml4"
        [sourceTs]="_srcTs4"
        [sourceCss]="_srcCss4">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <a cngxTag color="info" href="#category/frontend" style="text-decoration: none;">frontend</a>
    <a cngxTag color="success" href="#category/cleared" style="text-decoration: none;">cleared</a>
    <a cngxTag color="warning" href="#category/pending" style="text-decoration: none;">pending</a>
  </div>
      </app-example-card>
      <app-example-card title="Composition with CngxAvatar"
        [subtitle]="_s5"
        [sourceHtml]="_srcHtml5"
        [sourceTs]="_srcTs5"
        [sourceCss]="_srcCss5">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag size="sm" color="info">
      <cngx-avatar initials="S" />
      Sarah M.
    </span>
    <span cngxTag size="md" color="success">
      <cngx-avatar initials="J" />
      Jane Doe
    </span>
    <span cngxTag size="lg" color="warning">
      <cngx-avatar initials="A" />
      Alex K.
    </span>
    <span cngxTag size="xl" color="error">
      <cngx-avatar initials="M" />
      Marcus S.
    </span>
  </div>
      </app-example-card>
      <app-example-card title="Composition with CngxIcon"
        [subtitle]="_s6"
        [sourceHtml]="_srcHtml6"
        [sourceTs]="_srcTs6"
        [sourceCss]="_srcCss6">
        
  <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="success">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" focusable="false"><path fill="currentColor" d="M6.5 11.5 3 8l1.4-1.4 2.1 2.1L11.6 4l1.4 1.4z" /></svg>
      </cngx-icon>
      Active
    </span>
    <span cngxTag color="warning">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" focusable="false"><circle cx="8" cy="8" r="4" fill="currentColor" /></svg>
      </cngx-icon>
      Pending
    </span>
    <span cngxTag color="error">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" focusable="false"><path d="m4 4 8 8m0-8-8 8" /></svg>
      </cngx-icon>
      Failed
    </span>
  </div>
      </app-example-card>
    </app-doc-shell>
  `,
})
export class TagDemoComponent {
  protected readonly _s0 = 'Same colour, three visual variants — filled, outline, subtle.';
  protected readonly _s1 = 'Five predefined semantic colours plus open-string extension via <code>data-color</code>.';
  protected readonly _s2 = 'Four sizes scale padding + font-size; <code>md</code> is the default.';
  protected readonly _s3 = 'Visual-only truncation — full text remains in the DOM for assistive tech.';
  protected readonly _s4 = 'Native <code>&lt;a cngxTag&gt;</code> preserves anchor semantics — focus, keyboard, navigation.';
  protected readonly _s5 = 'Drop <code>&lt;cngx-avatar&gt;</code> directly inside <code>&lt;span cngxTag&gt;</code> — the tag overrides <code>--cngx-avatar-size</code> via the <code>--cngx-tag-content-size</code> cascade so the avatar scales with the tag’s density instead of forcing the chip taller. Override <code>--cngx-tag-content-size</code> per instance for finer control.';
  protected readonly _s6 = 'Drop <code>&lt;cngx-icon&gt;</code> directly inside <code>&lt;span cngxTag&gt;</code> — no tag-specific icon atom needed. CngxIcon handles sizing, vertical alignment, and <code>aria-hidden</code>.';
  protected readonly _srcHtml0 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag variant="filled" color="success">Filled</span>
    <span cngxTag variant="outline" color="success">Outline</span>
    <span cngxTag variant="subtle" color="success">Subtle</span>
  </div>`;
  protected readonly _srcTs0 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss0 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }`;
  protected readonly _srcHtml1 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="neutral">Neutral</span>
    <span cngxTag color="success">Active</span>
    <span cngxTag color="warning">Pending</span>
    <span cngxTag color="error">Failed</span>
    <span cngxTag color="info">Beta</span>
    <span cngxTag color="my-brand" style="--cngx-tag-bg: #4f46e5; --cngx-tag-color: #ffffff;">Branded</span>
  </div>`;
  protected readonly _srcTs1 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss1 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
[data-color="my-brand"] {
  --cngx-tag-bg: #4f46e5;
  --cngx-tag-color: #ffffff;
}`;
  protected readonly _srcHtml2 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag size="sm" color="info">Small</span>
    <span cngxTag size="md" color="info">Medium</span>
    <span cngxTag size="lg" color="info">Large</span>
    <span cngxTag size="xl" color="info">Extra large</span>
  </div>`;
  protected readonly _srcTs2 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss2 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }`;
  protected readonly _srcHtml3 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="neutral" [truncate]="true" maxWidth="8rem">A very long taxonomy label that overflows</span>
    <span cngxTag color="info" [truncate]="true" maxWidth="12rem">Another lengthy descriptor here</span>
  </div>`;
  protected readonly _srcTs3 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss3 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }`;
  protected readonly _srcHtml4 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <a cngxTag color="info" href="#category/frontend" style="text-decoration: none;">frontend</a>
    <a cngxTag color="success" href="#category/cleared" style="text-decoration: none;">cleared</a>
    <a cngxTag color="warning" href="#category/pending" style="text-decoration: none;">pending</a>
  </div>`;
  protected readonly _srcTs4 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss4 = `.row { display: flex; gap: 12px; align-items: center; }
.row a { text-decoration: none; }
.row a:hover { filter: brightness(0.92); }`;
  protected readonly _srcHtml5 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag size="sm" color="info">
      <cngx-avatar initials="S" />
      Sarah M.
    </span>
    <span cngxTag size="md" color="success">
      <cngx-avatar initials="J" />
      Jane Doe
    </span>
    <span cngxTag size="lg" color="warning">
      <cngx-avatar initials="A" />
      Alex K.
    </span>
    <span cngxTag size="xl" color="error">
      <cngx-avatar initials="M" />
      Marcus S.
    </span>
  </div>`;
  protected readonly _srcTs5 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss5 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
.cngx-tag cngx-avatar {
  /* Tag overrides --cngx-avatar-size via --cngx-tag-content-size cascade.
   * Consumers can override per-instance:
   *   <span cngxTag style="--cngx-tag-content-size: 2em">…</span>
   */
}`;
  protected readonly _srcHtml6 = `<div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
    <span cngxTag color="success">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" focusable="false"><path fill="currentColor" d="M6.5 11.5 3 8l1.4-1.4 2.1 2.1L11.6 4l1.4 1.4z" /></svg>
      </cngx-icon>
      Active
    </span>
    <span cngxTag color="warning">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" focusable="false"><circle cx="8" cy="8" r="4" fill="currentColor" /></svg>
      </cngx-icon>
      Pending
    </span>
    <span cngxTag color="error">
      <cngx-icon size="sm">
        <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" focusable="false"><path d="m4 4 8 8m0-8-8 8" /></svg>
      </cngx-icon>
      Failed
    </span>
  </div>`;
  protected readonly _srcTs6 = `import { CngxTag, CngxIcon, CngxAvatar } from '@cngx/common/display';`;
  protected readonly _srcCss6 = `.row { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }`;
}
