// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/ui/mat-stepper/mat-stepper-instrumentation-demo/mat-stepper-instrumentation-demo.story.ts#section[0] "Vanilla <mat-stepper> upgraded by adding cngxMatStepper"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Observable } from 'rxjs';
import { MatStepperModule } from '@angular/material/stepper';
import { type CngxStepperCommitAction } from '@cngx/common/stepper';
import { CngxMatStepperBridge } from '@cngx/ui/mat-stepper';
import { CngxToastOn, CngxBannerOn } from '@cngx/ui/feedback';

@Component({
  selector: 'app-mat-stepper-instrumentation-vanilla-mat-stepper-upgraded-by-adding-cngxmatstepper',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatStepperModule, CngxMatStepperBridge, CngxToastOn, CngxBannerOn],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="event-row" style="gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap">
        <button type="button" class="chip"
                [style.background]="mode() === 'optimistic' ? '#c8e6c9' : ''"
                (click)="mode.set('optimistic')">optimistic</button>
        <button type="button" class="chip"
                [style.background]="mode() === 'pessimistic' ? '#c8e6c9' : ''"
                (click)="mode.set('pessimistic')">pessimistic</button>
        <label style="margin-inline-start:12px">
          <input type="checkbox"
                 [checked]="shouldFail()"
                 (change)="shouldFail.set($any($event.target).checked)" />
          simulate error
        </label>
        <label style="margin-inline-start:12px">
          latency
          <input type="range" min="100" max="2000" step="100"
                 [value]="latencyMs()"
                 (input)="latencyMs.set(+$any($event.target).value)" />
          {{ latencyMs() }}ms
        </label>
      </div>
      <mat-stepper
        cngxMatStepper
        [(activeStepIndex)]="active"
        [commitAction]="commitAction"
        [commitMode]="mode()"
        cngxToastOn
        [toastError]="'Step transition failed'"
        cngxBannerOn
        bannerId="mat-stepper:commit-error"
        [bannerError]="'Step transition refused by the server.'"
        aria-label="Async stepper"
      >
        <mat-step label="Personal info"><p>Personal info form.</p></mat-step>
        <mat-step label="Account"><p>Account details form.</p></mat-step>
        <mat-step label="Confirmation"><p>Confirm and submit.</p></mat-step>
      </mat-stepper>
      <div class="event-grid" style="margin-top:12px">
        <div class="event-row"><span class="event-label">Active step</span><span class="event-value">{{ active() }}</span></div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class MatStepperInstrumentationVanillaMatStepperUpgradedByAddingCngxmatstepper {
  protected readonly _exTitle: string = 'Mat-stepper — instrumentation directive';
  protected readonly _exDescription: string = 'Add <code>cngxMatStepper</code> to an existing <code>&lt;mat-stepper&gt;</code> and the cngx commit-action lifecycle, the <code>CNGX_STATEFUL</code> producer, and the bridge directive composition (<code>&lt;cngx-toast-on /&gt;</code>, <code>&lt;cngx-banner-on /&gt;</code>) light up — without rewriting your template. One attribute upgrade, sibling-additive to <code>&lt;cngx-mat-stepper&gt;</code>. Identical commit semantics to <code>&lt;cngx-stepper&gt;</code>: <code>[commitMode]="optimistic"</code> advances Material immediately and rolls back on rejection; <code>[commitMode]="pessimistic"</code> keeps Material on the origin step until the action resolves.';
  protected readonly _exSectionTitle: string = 'Vanilla <mat-stepper> upgraded by adding cngxMatStepper';
  protected readonly _exSubtitle: string = 'The <code>&lt;mat-stepper&gt;</code> stays unchanged — <code>cngxMatStepper</code> is the only addition. The commit lifecycle, the <code>CNGX_STATEFUL</code> producer, and the toast + banner bridges work identically to <code>&lt;cngx-stepper&gt;</code>. Toggle the mode and "simulate error" to exercise the four quadrants.';
  protected readonly _exTs: string = `import { Observable } from 'rxjs';
import { MatStepperModule } from '@angular/material/stepper';
import { type CngxStepperCommitAction } from '@cngx/common/stepper';
import { CngxMatStepperBridge } from '@cngx/ui/mat-stepper';
import { CngxToastOn, CngxBannerOn } from '@cngx/ui/feedback';

protected readonly active = signal(0);
protected readonly mode = signal<'optimistic' | 'pessimistic'>('optimistic');
protected readonly shouldFail = signal(false);
protected readonly latencyMs = signal(600);

protected readonly commitAction: CngxStepperCommitAction = (from, to) => {
  const ms = this.latencyMs();
  const fail = this.shouldFail();
  return new Observable<boolean>((sub) => {
    const handle = setTimeout(() => {
      if (fail) {
        sub.error(new Error('Server refused step ' + from + ' → ' + to));
      } else {
        sub.next(true);
        sub.complete();
      }
    }, ms);
    return () => clearTimeout(handle);
  });
};`;
  protected readonly _exHtml: string = `<div class="event-row" style="gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap">
  <button type="button" class="chip"
          [style.background]="mode() === 'optimistic' ? '#c8e6c9' : ''"
          (click)="mode.set('optimistic')">optimistic</button>
  <button type="button" class="chip"
          [style.background]="mode() === 'pessimistic' ? '#c8e6c9' : ''"
          (click)="mode.set('pessimistic')">pessimistic</button>
  <label style="margin-inline-start:12px">
    <input type="checkbox"
           [checked]="shouldFail()"
           (change)="shouldFail.set($any($event.target).checked)" />
    simulate error
  </label>
  <label style="margin-inline-start:12px">
    latency
    <input type="range" min="100" max="2000" step="100"
           [value]="latencyMs()"
           (input)="latencyMs.set(+$any($event.target).value)" />
    {{ latencyMs() }}ms
  </label>
</div>
<mat-stepper
  cngxMatStepper
  [(activeStepIndex)]="active"
  [commitAction]="commitAction"
  [commitMode]="mode()"
  cngxToastOn
  [toastError]="'Step transition failed'"
  cngxBannerOn
  bannerId="mat-stepper:commit-error"
  [bannerError]="'Step transition refused by the server.'"
  aria-label="Async stepper"
>
  <mat-step label="Personal info"><p>Personal info form.</p></mat-step>
  <mat-step label="Account"><p>Account details form.</p></mat-step>
  <mat-step label="Confirmation"><p>Confirm and submit.</p></mat-step>
</mat-stepper>`;
  protected readonly active = signal(0);
    protected readonly mode = signal<'optimistic' | 'pessimistic'>('optimistic');
    protected readonly shouldFail = signal(false);
    protected readonly latencyMs = signal(600);

    protected readonly commitAction: CngxStepperCommitAction = (from, to) => {
      const ms = this.latencyMs();
      const fail = this.shouldFail();
      return new Observable<boolean>((sub) => {
        const handle = setTimeout(() => {
          if (fail) {
            sub.error(new Error('Server refused step ' + from + ' → ' + to));
          } else {
            sub.next(true);
            sub.complete();
          }
        }, ms);
        return () => clearTimeout(handle);
      });
    };
}
