// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/a11y/aria-expanded-demo/aria-expanded-demo.story.ts#section[0] "CngxAriaExpanded — Disclosure Pattern"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxAriaExpanded } from '@cngx/common/a11y';

@Component({
  selector: 'app-aria-expanded-disclosure-pattern',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxAriaExpanded],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div>
        <button
          [cngxAriaExpanded]="open()"
          controls="details-panel"
          class="sort-btn"
          (click)="open.set(!open())"
          style="display: flex; align-items: center; gap: 6px;"
        >
          <span>Toggle details</span>
          <span [style.transform]="open() ? 'rotate(180deg)' : 'rotate(0)'" style="transition: transform 0.2s">&#x25BC;</span>
        </button>

        <div
          id="details-panel"
          role="region"
          style="
            margin-top: 8px;
            padding: 12px 16px;
            border: 1px solid var(--cngx-border, #ddd);
            border-radius: 6px;
            background: var(--cngx-surface-alt, #f8f9fa);
          "
          [style.display]="open() ? 'block' : 'none'"
        >
          Panel content — only shown when open. A screen reader announces
          <code>aria-expanded="true"</code> on the button and can navigate
          to the controlled region via <code>aria-controls</code>.
        </div>

        <div class="event-grid" style="margin-top: 12px">
          <div class="event-row">
            <span class="event-label">aria-expanded</span>
            <span class="event-value">{{ open() }}</span>
          </div>
          <div class="event-row">
            <span class="event-label">aria-controls</span>
            <span class="event-value">details-panel</span>
          </div>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class AriaExpandedDisclosurePattern {
  protected readonly _exTitle: string = 'AriaExpanded';
  protected readonly _exDescription: string = 'Manages aria-expanded and aria-controls attributes for disclosure patterns (accordions, dropdowns, details panels).';
  protected readonly _exSectionTitle: string = 'CngxAriaExpanded — Disclosure Pattern';
  protected readonly _exSubtitle: string = '<code>[cngxAriaExpanded]</code> sets <code>aria-expanded</code> on the host element. Combine with <code>[controls]</code> to add <code>aria-controls</code>, linking the trigger to its controlled panel by ID.';
  protected readonly _exTs: string = `import { CngxAriaExpanded } from '@cngx/common/a11y';

protected open = signal(false);
protected panels = signal<Record<string, boolean>>({ specs: false, reviews: false, shipping: false });

protected togglePanel(key: string): void {
  this.panels.update(p => ({ ...p, [key]: !p[key] }));
}`;
  protected readonly _exHtml: string = `<div>
  <button
    [cngxAriaExpanded]="open()"
    controls="details-panel"
    class="sort-btn"
    (click)="open.set(!open())"
    style="display: flex; align-items: center; gap: 6px;"
  >
    <span>Toggle details</span>
    <span [style.transform]="open() ? 'rotate(180deg)' : 'rotate(0)'" style="transition: transform 0.2s">&#x25BC;</span>
  </button>

  <div
    id="details-panel"
    role="region"
    style="
      margin-top: 8px;
      padding: 12px 16px;
      border: 1px solid var(--cngx-border, #ddd);
      border-radius: 6px;
      background: var(--cngx-surface-alt, #f8f9fa);
    "
    [style.display]="open() ? 'block' : 'none'"
  >
    Panel content — only shown when open. A screen reader announces
    <code>aria-expanded="true"</code> on the button and can navigate
    to the controlled region via <code>aria-controls</code>.
  </div>

  <div class="event-grid" style="margin-top: 12px">
    <div class="event-row">
      <span class="event-label">aria-expanded</span>
      <span class="event-value">{{ open() }}</span>
    </div>
    <div class="event-row">
      <span class="event-label">aria-controls</span>
      <span class="event-value">details-panel</span>
    </div>
  </div>
</div>`;
  protected open = signal(false);
    protected panels = signal<Record<string, boolean>>({ specs: false, reviews: false, shipping: false });

    protected togglePanel(key: string): void {
      this.panels.update(p => ({ ...p, [key]: !p[key] }));
    }
}
