// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/interactive/checkbox-demo/checkbox-demo.story.ts#section[1] "Tri-state — Select-all pattern"

import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { CngxCheckbox } from '@cngx/common/interactive';

@Component({
  selector: 'app-checkbox-tri-state-select-all-pattern',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxCheckbox],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-checkbox
        [value]="allChecked()"
        [indeterminate]="groupIndeterminate()"
        (valueChange)="toggleAll($event)"
      >Select all</cngx-checkbox>
      <div class="children">
        <cngx-checkbox [(value)]="itemA">Item A</cngx-checkbox>
        <cngx-checkbox [(value)]="itemB">Item B</cngx-checkbox>
        <cngx-checkbox [(value)]="itemC">Item C</cngx-checkbox>
      </div>
      <p class="caption">aria-checked = <code>{{ groupIndeterminate() ? 'mixed' : allChecked() ? 'true' : 'false' }}</code></p>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class CheckboxTriStateSelectAllPattern {
  protected readonly _exTitle: string = 'Checkbox';
  protected readonly _exDescription: string = 'Single-value boolean checkbox atom with WAI-ARIA tristate semantics. Composes <code>cngx-checkbox-indicator</code> from @cngx/common/display for the visual state. Click on an indeterminate checkbox advances to <code>value=true, indeterminate=false</code> in a single step — there is no path that lands the checkbox back in <code>mixed</code> from a user click.';
  protected readonly _exSectionTitle: string = 'Tri-state — Select-all pattern';
  protected readonly _exSubtitle: string = 'The header checkbox is <code>indeterminate</code> when some-but-not-all items are selected. Clicking it cascades: indeterminate → checked (selects all), checked → unchecked (clears all), unchecked → checked (selects all).';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exTs: string = `import { CngxCheckbox } from '@cngx/common/interactive';

protected readonly accept = signal(false);
protected readonly itemA = signal(true);
protected readonly itemB = signal(false);
protected readonly itemC = signal(false);
protected readonly allChecked = computed(() => this.itemA() && this.itemB() && this.itemC());
protected readonly someChecked = computed(() => this.itemA() || this.itemB() || this.itemC());
protected readonly groupIndeterminate = computed(() => this.someChecked() && !this.allChecked());
protected toggleAll(next: boolean): void {
  this.itemA.set(next);
  this.itemB.set(next);
  this.itemC.set(next);
}`;
  protected readonly _exHtml: string = `<cngx-checkbox
  [value]="allChecked()"
  [indeterminate]="groupIndeterminate()"
  (valueChange)="toggleAll($event)"
>Select all</cngx-checkbox>
<div class="children">
  <cngx-checkbox [(value)]="itemA">Item A</cngx-checkbox>
  <cngx-checkbox [(value)]="itemB">Item B</cngx-checkbox>
  <cngx-checkbox [(value)]="itemC">Item C</cngx-checkbox>
</div>
<p class="caption">aria-checked = <code>{{ groupIndeterminate() ? 'mixed' : allChecked() ? 'true' : 'false' }}</code></p>`;
  protected readonly accept = signal(false);
    protected readonly itemA = signal(true);
    protected readonly itemB = signal(false);
    protected readonly itemC = signal(false);
    protected readonly allChecked = computed(() => this.itemA() && this.itemB() && this.itemC());
    protected readonly someChecked = computed(() => this.itemA() || this.itemB() || this.itemC());
    protected readonly groupIndeterminate = computed(() => this.someChecked() && !this.allChecked());
    protected toggleAll(next: boolean): void {
      this.itemA.set(next);
      this.itemB.set(next);
      this.itemC.set(next);
    }
}
