// @generated by scripts/generate-examples.mjs — do not edit manually
import type { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: 'active-descendant/listbox-with-items-input',
    loadComponent: () => import('./features/active-descendant/listbox-with-items-input.component').then((m) => m.ActiveDescendantListboxWithItemsInput),
    data: { lib: 'common', category: 'a11y', demo: "Active Descendant", section: "Listbox with items input" },
  },
  {
    path: 'active-descendant/typeahead',
    loadComponent: () => import('./features/active-descendant/typeahead.component').then((m) => m.ActiveDescendantTypeahead),
    data: { lib: 'common', category: 'a11y', demo: "Active Descendant", section: "Typeahead" },
  },
  {
    path: 'alert-stack/basic-stack',
    loadComponent: () => import('./features/alert-stack/basic-stack.component').then((m) => m.AlertStackBasicStack),
    data: { lib: 'ui', category: 'feedback', demo: "Alert Stack", section: "Basic Stack" },
  },
  {
    path: 'alert-stack/dialog-use-case',
    loadComponent: () => import('./features/alert-stack/dialog-use-case.component').then((m) => m.AlertStackDialogUseCase),
    data: { lib: 'ui', category: 'feedback', demo: "Alert Stack", section: "Dialog Use Case" },
  },
  {
    path: 'alert-stack/overflow-collapse',
    loadComponent: () => import('./features/alert-stack/overflow-collapse.component').then((m) => m.AlertStackOverflowCollapse),
    data: { lib: 'ui', category: 'feedback', demo: "Alert Stack", section: "Overflow Collapse" },
  },
  {
    path: 'aria-expanded/accordion-multiple-panels',
    loadComponent: () => import('./features/aria-expanded/accordion-multiple-panels.component').then((m) => m.AriaExpandedAccordionMultiplePanels),
    data: { lib: 'common', category: 'a11y', demo: "AriaExpanded", section: "Accordion — Multiple Panels" },
  },
  {
    path: 'aria-expanded/disclosure-pattern',
    loadComponent: () => import('./features/aria-expanded/disclosure-pattern.component').then((m) => m.AriaExpandedDisclosurePattern),
    data: { lib: 'common', category: 'a11y', demo: "AriaExpanded", section: "CngxAriaExpanded — Disclosure Pattern" },
  },
  {
    path: 'async-button/random-outcome',
    loadComponent: () => import('./features/async-button/random-outcome.component').then((m) => m.AsyncButtonRandomOutcome),
    data: { lib: 'ui', category: '', demo: "ActionButton", section: "Random Outcome" },
  },
  {
    path: 'async-button/string-labels',
    loadComponent: () => import('./features/async-button/string-labels.component').then((m) => m.AsyncButtonStringLabels),
    data: { lib: 'ui', category: '', demo: "ActionButton", section: "String Labels" },
  },
  {
    path: 'async-button/template-slots',
    loadComponent: () => import('./features/async-button/template-slots.component').then((m) => m.AsyncButtonTemplateSlots),
    data: { lib: 'ui', category: '', demo: "ActionButton", section: "Template Slots" },
  },
  {
    path: 'autofocus/conditional-focus',
    loadComponent: () => import('./features/autofocus/conditional-focus.component').then((m) => m.AutofocusConditionalFocus),
    data: { lib: 'common', category: 'a11y', demo: "Autofocus", section: "Conditional Focus" },
  },
  {
    path: 'autofocus/focus-on-insert',
    loadComponent: () => import('./features/autofocus/focus-on-insert.component').then((m) => m.AutofocusFocusOnInsert),
    data: { lib: 'common', category: 'a11y', demo: "Autofocus", section: "Focus on Insert" },
  },
  {
    path: 'autosize/basic-autosize',
    loadComponent: () => import('./features/autosize/basic-autosize.component').then((m) => m.AutosizeBasicAutosize),
    data: { lib: 'forms', category: 'input', demo: "Autosize Textarea", section: "Basic Autosize" },
  },
  {
    path: 'autosize/min-max-rows',
    loadComponent: () => import('./features/autosize/min-max-rows.component').then((m) => m.AutosizeMinMaxRows),
    data: { lib: 'forms', category: 'input', demo: "Autosize Textarea", section: "Min / Max Rows" },
  },
  {
    path: 'avatar/cascade-image-initials-fallback',
    loadComponent: () => import('./features/avatar/cascade-image-initials-fallback.component').then((m) => m.AvatarCascadeImageInitialsFallback),
    data: { lib: 'common', category: 'display', demo: "Avatar", section: "Cascade: image, initials, fallback" },
  },
  {
    path: 'avatar/shapes-and-status',
    loadComponent: () => import('./features/avatar/shapes-and-status.component').then((m) => m.AvatarShapesAndStatus),
    data: { lib: 'common', category: 'display', demo: "Avatar", section: "Shapes and status" },
  },
  {
    path: 'avatar/sizes',
    loadComponent: () => import('./features/avatar/sizes.component').then((m) => m.AvatarSizes),
    data: { lib: 'common', category: 'display', demo: "Avatar", section: "Sizes" },
  },
  {
    path: 'backdrop/overlay-with-inert',
    loadComponent: () => import('./features/backdrop/overlay-with-inert.component').then((m) => m.BackdropOverlayWithInert),
    data: { lib: 'common', category: 'layout', demo: "Backdrop", section: "CngxBackdrop — Overlay with inert" },
  },
  {
    path: 'badge/colors-and-dot-mode',
    loadComponent: () => import('./features/badge/colors-and-dot-mode.component').then((m) => m.BadgeColorsAndDotMode),
    data: { lib: 'common', category: 'display', demo: "Badge", section: "Colors and dot mode" },
  },
  {
    path: 'badge/counts-with-overflow',
    loadComponent: () => import('./features/badge/counts-with-overflow.component').then((m) => m.BadgeCountsWithOverflow),
    data: { lib: 'common', category: 'display', demo: "Badge", section: "Counts with overflow" },
  },
  {
    path: 'badge/inline-and-hidden',
    loadComponent: () => import('./features/badge/inline-and-hidden.component').then((m) => m.BadgeInlineAndHidden),
    data: { lib: 'common', category: 'display', demo: "Badge", section: "Inline and hidden" },
  },
  {
    path: 'bullet/async-state-machine',
    loadComponent: () => import('./features/bullet/async-state-machine.component').then((m) => m.BulletAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Bullet", section: "Async state machine" },
  },
  {
    path: 'bullet/performance-vs-target',
    loadComponent: () => import('./features/bullet/performance-vs-target.component').then((m) => m.BulletPerformanceVsTarget),
    data: { lib: 'common', category: 'chart', demo: "Bullet", section: "Performance vs target" },
  },
  {
    path: 'button-multi-toggle-group/basic-multi-filter-toolbar',
    loadComponent: () => import('./features/button-multi-toggle-group/basic-multi-filter-toolbar.component').then((m) => m.ButtonMultiToggleGroupBasicMultiFilterToolbar),
    data: { lib: 'common', category: 'interactive', demo: "Button toggle group (multi)", section: "Basic — multi-filter toolbar" },
  },
  {
    path: 'button-multi-toggle-group/disabled-group-cascade-vs-per-toggle',
    loadComponent: () => import('./features/button-multi-toggle-group/disabled-group-cascade-vs-per-toggle.component').then((m) => m.ButtonMultiToggleGroupDisabledGroupCascadeVsPerToggle),
    data: { lib: 'common', category: 'interactive', demo: "Button toggle group (multi)", section: "Disabled — group cascade vs per-toggle" },
  },
  {
    path: 'button-toggle-group/basic-view-switcher',
    loadComponent: () => import('./features/button-toggle-group/basic-view-switcher.component').then((m) => m.ButtonToggleGroupBasicViewSwitcher),
    data: { lib: 'common', category: 'interactive', demo: "Button toggle group (single)", section: "Basic — view switcher" },
  },
  {
    path: 'button-toggle-group/disabled-group-cascade-vs-per-toggle',
    loadComponent: () => import('./features/button-toggle-group/disabled-group-cascade-vs-per-toggle.component').then((m) => m.ButtonToggleGroupDisabledGroupCascadeVsPerToggle),
    data: { lib: 'common', category: 'interactive', demo: "Button toggle group (single)", section: "Disabled — group cascade vs per-toggle" },
  },
  {
    path: 'button-toggle-group/vertical-orientation',
    loadComponent: () => import('./features/button-toggle-group/vertical-orientation.component').then((m) => m.ButtonToggleGroupVerticalOrientation),
    data: { lib: 'common', category: 'interactive', demo: "Button toggle group (single)", section: "Vertical orientation" },
  },
  {
    path: 'card-grid/basic-grid',
    loadComponent: () => import('./features/card-grid/basic-grid.component').then((m) => m.CardGridBasicGrid),
    data: { lib: 'common', category: 'card', demo: "Card Grid", section: "Basic Grid" },
  },
  {
    path: 'card-grid/density-variants',
    loadComponent: () => import('./features/card-grid/density-variants.component').then((m) => m.CardGridDensityVariants),
    data: { lib: 'common', category: 'card', demo: "Card Grid", section: "Density Variants" },
  },
  {
    path: 'card-grid/empty-state-with-reason',
    loadComponent: () => import('./features/card-grid/empty-state-with-reason.component').then((m) => m.CardGridEmptyStateWithReason),
    data: { lib: 'common', category: 'card', demo: "Card Grid", section: "Empty State with Reason" },
  },
  {
    path: 'checkbox-group/basic-select-all-master-projected-leaves',
    loadComponent: () => import('./features/checkbox-group/basic-select-all-master-projected-leaves.component').then((m) => m.CheckboxGroupBasicSelectAllMasterProjectedLeaves),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox group", section: "Basic — select-all master + projected leaves" },
  },
  {
    path: 'checkbox-group/disabled-cascade',
    loadComponent: () => import('./features/checkbox-group/disabled-cascade.component').then((m) => m.CheckboxGroupDisabledCascade),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox group", section: "Disabled cascade" },
  },
  {
    path: 'checkbox/basic-two-way-binding',
    loadComponent: () => import('./features/checkbox/basic-two-way-binding.component').then((m) => m.CheckboxBasicTwoWayBinding),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox", section: "Basic — two-way binding" },
  },
  {
    path: 'checkbox/custom-check-dash-glyphs',
    loadComponent: () => import('./features/checkbox/custom-check-dash-glyphs.component').then((m) => m.CheckboxCustomCheckDashGlyphs),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox", section: "Custom check + dash glyphs" },
  },
  {
    path: 'checkbox/disabled',
    loadComponent: () => import('./features/checkbox/disabled.component').then((m) => m.CheckboxDisabled),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox", section: "Disabled" },
  },
  {
    path: 'checkbox/tri-state-select-all-pattern',
    loadComponent: () => import('./features/checkbox/tri-state-select-all-pattern.component').then((m) => m.CheckboxTriStateSelectAllPattern),
    data: { lib: 'common', category: 'interactive', demo: "Checkbox", section: "Tri-state — Select-all pattern" },
  },
  {
    path: 'chip-group/basic-pick-exactly-one-size',
    loadComponent: () => import('./features/chip-group/basic-pick-exactly-one-size.component').then((m) => m.ChipGroupBasicPickExactlyOneSize),
    data: { lib: 'common', category: 'interactive', demo: "Chip group (single-select)", section: "Basic — pick exactly one size" },
  },
  {
    path: 'chip-input/async-validation-with-supersede-semantics',
    loadComponent: () => import('./features/chip-input/async-validation-with-supersede-semantics.component').then((m) => m.ChipInputAsyncValidationWithSupersedeSemantics),
    data: { lib: 'common', category: 'interactive', demo: "Chip input (tokenizing)", section: "Async validation with supersede semantics" },
  },
  {
    path: 'chip-input/synchronous-tokenization',
    loadComponent: () => import('./features/chip-input/synchronous-tokenization.component').then((m) => m.ChipInputSynchronousTokenization),
    data: { lib: 'common', category: 'interactive', demo: "Chip input (tokenizing)", section: "Synchronous tokenization" },
  },
  {
    path: 'chip-interaction/basic-toggle-on-click-space-or-enter',
    loadComponent: () => import('./features/chip-interaction/basic-toggle-on-click-space-or-enter.component').then((m) => m.ChipInteractionBasicToggleOnClickSpaceOrEnter),
    data: { lib: 'common', category: 'interactive', demo: "Chip interaction (standalone)", section: "Basic — toggle on click, Space, or Enter" },
  },
  {
    path: 'chip-interaction/disabled-state',
    loadComponent: () => import('./features/chip-interaction/disabled-state.component').then((m) => m.ChipInteractionDisabledState),
    data: { lib: 'common', category: 'interactive', demo: "Chip interaction (standalone)", section: "Disabled state" },
  },
  {
    path: 'chip-interaction/removable-with-removerequest-on-backspace-delete',
    loadComponent: () => import('./features/chip-interaction/removable-with-removerequest-on-backspace-delete.component').then((m) => m.ChipInteractionRemovableWithRemoverequestOnBackspaceDelete),
    data: { lib: 'common', category: 'interactive', demo: "Chip interaction (standalone)", section: "Removable with (removeRequest) on Backspace / Delete" },
  },
  {
    path: 'click-outside/dropdown',
    loadComponent: () => import('./features/click-outside/dropdown.component').then((m) => m.ClickOutsideDropdown),
    data: { lib: 'common', category: 'interactive', demo: "ClickOutside", section: "CngxClickOutside — Dropdown" },
  },
  {
    path: 'click-outside/enabled-toggle',
    loadComponent: () => import('./features/click-outside/enabled-toggle.component').then((m) => m.ClickOutsideEnabledToggle),
    data: { lib: 'common', category: 'interactive', demo: "ClickOutside", section: "CngxClickOutside — enabled toggle" },
  },
  {
    path: 'context-menu/right-click-target-zone',
    loadComponent: () => import('./features/context-menu/right-click-target-zone.component').then((m) => m.ContextMenuRightClickTargetZone),
    data: { lib: 'common', category: 'interactive', demo: "Context Menu Trigger", section: "Right-click target zone" },
  },
  {
    path: 'copy-block/api-key',
    loadComponent: () => import('./features/copy-block/api-key.component').then((m) => m.CopyBlockApiKey),
    data: { lib: 'common', category: 'interactive', demo: "Copy Block", section: "API Key" },
  },
  {
    path: 'copy-block/code-snippet',
    loadComponent: () => import('./features/copy-block/code-snippet.component').then((m) => m.CopyBlockCodeSnippet),
    data: { lib: 'common', category: 'interactive', demo: "Copy Block", section: "Code Snippet" },
  },
  {
    path: 'copy-text/copy-token',
    loadComponent: () => import('./features/copy-text/copy-token.component').then((m) => m.CopyTextCopyToken),
    data: { lib: 'common', category: 'interactive', demo: "Copy Text", section: "Copy Token" },
  },
  {
    path: 'copy-text/copy-url-with-sr-announcement',
    loadComponent: () => import('./features/copy-text/copy-url-with-sr-announcement.component').then((m) => m.CopyTextCopyUrlWithSrAnnouncement),
    data: { lib: 'common', category: 'interactive', demo: "Copy Text", section: "Copy URL with SR Announcement" },
  },
  {
    path: 'deviation-bar/async-state-machine',
    loadComponent: () => import('./features/deviation-bar/async-state-machine.component').then((m) => m.DeviationBarAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Deviation Bar", section: "Async state machine" },
  },
  {
    path: 'deviation-bar/variance-readings',
    loadComponent: () => import('./features/deviation-bar/variance-readings.component').then((m) => m.DeviationBarVarianceReadings),
    data: { lib: 'common', category: 'chart', demo: "Deviation Bar", section: "Variance readings" },
  },
  {
    path: 'disclosure/basic-uncontrolled',
    loadComponent: () => import('./features/disclosure/basic-uncontrolled.component').then((m) => m.DisclosureBasicUncontrolled),
    data: { lib: 'common', category: 'interactive', demo: "Disclosure", section: "Basic — Uncontrolled" },
  },
  {
    path: 'disclosure/controlled-mode',
    loadComponent: () => import('./features/disclosure/controlled-mode.component').then((m) => m.DisclosureControlledMode),
    data: { lib: 'common', category: 'interactive', demo: "Disclosure", section: "Controlled Mode" },
  },
  {
    path: 'disclosure/faq-accordion',
    loadComponent: () => import('./features/disclosure/faq-accordion.component').then((m) => m.DisclosureFaqAccordion),
    data: { lib: 'common', category: 'interactive', demo: "Disclosure", section: "FAQ Accordion" },
  },
  {
    path: 'divider/horizontal-vs-vertical',
    loadComponent: () => import('./features/divider/horizontal-vs-vertical.component').then((m) => m.DividerHorizontalVsVertical),
    data: { lib: 'common', category: 'display', demo: "Divider", section: "Horizontal vs vertical" },
  },
  {
    path: 'divider/inset',
    loadComponent: () => import('./features/divider/inset.component').then((m) => m.DividerInset),
    data: { lib: 'common', category: 'display', demo: "Divider", section: "Inset" },
  },
  {
    path: 'donut/async-state-machine',
    loadComponent: () => import('./features/donut/async-state-machine.component').then((m) => m.DonutAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Donut", section: "Async state machine" },
  },
  {
    path: 'donut/score-gauges',
    loadComponent: () => import('./features/donut/score-gauges.component').then((m) => m.DonutScoreGauges),
    data: { lib: 'common', category: 'chart', demo: "Donut", section: "Score gauges" },
  },
  {
    path: 'empty-state/default-no-icon-projected',
    loadComponent: () => import('./features/empty-state/default-no-icon-projected.component').then((m) => m.EmptyStateDefaultNoIconProjected),
    data: { lib: 'ui', category: 'ui', demo: "Empty State", section: "Default (no icon projected)" },
  },
  {
    path: 'empty-state/inside-a-card-grid',
    loadComponent: () => import('./features/empty-state/inside-a-card-grid.component').then((m) => m.EmptyStateInsideACardGrid),
    data: { lib: 'ui', category: 'ui', demo: "Empty State", section: "Inside a Card Grid" },
  },
  {
    path: 'empty-state/inside-a-list',
    loadComponent: () => import('./features/empty-state/inside-a-list.component').then((m) => m.EmptyStateInsideAList),
    data: { lib: 'ui', category: 'ui', demo: "Empty State", section: "Inside a List" },
  },
  {
    path: 'empty-state/inside-a-table',
    loadComponent: () => import('./features/empty-state/inside-a-table.component').then((m) => m.EmptyStateInsideATable),
    data: { lib: 'ui', category: 'ui', demo: "Empty State", section: "Inside a Table" },
  },
  {
    path: 'empty-state/with-custom-icon-actions',
    loadComponent: () => import('./features/empty-state/with-custom-icon-actions.component').then((m) => m.EmptyStateWithCustomIconActions),
    data: { lib: 'ui', category: 'ui', demo: "Empty State", section: "With custom icon + actions" },
  },
  {
    path: 'error-aggregator/cngx-card-host-no-scope-errors-visible-immediately',
    loadComponent: () => import('./features/error-aggregator/cngx-card-host-no-scope-errors-visible-immediately.component').then((m) => m.ErrorAggregatorCngxCardHostNoScopeErrorsVisibleImmediately),
    data: { lib: 'common', category: 'interactive', demo: "Error Aggregator", section: "cngx-card host (no scope — errors visible immediately)" },
  },
  {
    path: 'error-aggregator/cngx-popover-panel-host',
    loadComponent: () => import('./features/error-aggregator/cngx-popover-panel-host.component').then((m) => m.ErrorAggregatorCngxPopoverPanelHost),
    data: { lib: 'common', category: 'interactive', demo: "Error Aggregator", section: "cngx-popover-panel host" },
  },
  {
    path: 'error-aggregator/material-mat-tab-label-with-error-count-badge',
    loadComponent: () => import('./features/error-aggregator/material-mat-tab-label-with-error-count-badge.component').then((m) => m.ErrorAggregatorMaterialMatTabLabelWithErrorCountBadge),
    data: { lib: 'common', category: 'interactive', demo: "Error Aggregator", section: "Material mat-tab label with error-count badge" },
  },
  {
    path: 'error-aggregator/native-form-scope-reveal-on-submit',
    loadComponent: () => import('./features/error-aggregator/native-form-scope-reveal-on-submit.component').then((m) => m.ErrorAggregatorNativeFormScopeRevealOnSubmit),
    data: { lib: 'common', category: 'interactive', demo: "Error Aggregator", section: "Native form + scope reveal-on-submit" },
  },
  {
    path: 'error-state/basic-boolean-flag-flips-aria-invalid-aria-errormessage',
    loadComponent: () => import('./features/error-state/basic-boolean-flag-flips-aria-invalid-aria-errormessage.component').then((m) => m.ErrorStateBasicBooleanFlagFlipsAriaInvalidAriaErrormessage),
    data: { lib: 'common', category: 'interactive', demo: "Error State", section: "Basic — boolean flag flips aria-invalid + aria-errormessage" },
  },
  {
    path: 'error-state/without-message-id-class-hook-aria-invalid-only',
    loadComponent: () => import('./features/error-state/without-message-id-class-hook-aria-invalid-only.component').then((m) => m.ErrorStateWithoutMessageIdClassHookAriaInvalidOnly),
    data: { lib: 'common', category: 'interactive', demo: "Error State", section: "Without message id — class hook + aria-invalid only" },
  },
  {
    path: 'expandable-text/auto-toggle',
    loadComponent: () => import('./features/expandable-text/auto-toggle.component').then((m) => m.ExpandableTextAutoToggle),
    data: { lib: 'common', category: 'layout', demo: "Expandable Text", section: "Auto-Toggle" },
  },
  {
    path: 'expandable-text/custom-labels',
    loadComponent: () => import('./features/expandable-text/custom-labels.component').then((m) => m.ExpandableTextCustomLabels),
    data: { lib: 'common', category: 'layout', demo: "Expandable Text", section: "Custom Labels" },
  },
  {
    path: 'expandable-text/custom-toggle-template',
    loadComponent: () => import('./features/expandable-text/custom-toggle-template.component').then((m) => m.ExpandableTextCustomToggleTemplate),
    data: { lib: 'common', category: 'layout', demo: "Expandable Text", section: "Custom Toggle Template" },
  },
  {
    path: 'file-drop/image-upload',
    loadComponent: () => import('./features/file-drop/image-upload.component').then((m) => m.FileDropImageUpload),
    data: { lib: 'forms', category: 'input', demo: "File Drop", section: "Image Upload" },
  },
  {
    path: 'filter-builder-async-state/loading-error-content-branches-via-cngx-async-container',
    loadComponent: () => import('./features/filter-builder-async-state/loading-error-content-branches-via-cngx-async-container.component').then((m) => m.FilterBuilderAsyncStateLoadingErrorContentBranchesViaCngxAsyncContainer),
    data: { lib: 'forms', category: 'filter-builder', demo: "Filter Builder — async-container wrap", section: "Loading + error + content branches via <cngx-async-container>" },
  },
  {
    path: 'filter-builder-json/builder-json',
    loadComponent: () => import('./features/filter-builder-json/builder-json.component').then((m) => m.FilterBuilderJsonBuilderJson),
    data: { lib: 'forms', category: 'filter-builder', demo: "Filter Builder — JSON form component", section: "Builder ↔ JSON" },
  },
  {
    path: 'filter-builder/basic-two-way-binding-json-inspection',
    loadComponent: () => import('./features/filter-builder/basic-two-way-binding-json-inspection.component').then((m) => m.FilterBuilderBasicTwoWayBindingJsonInspection),
    data: { lib: 'forms', category: 'filter-builder', demo: "Filter Builder", section: "Basic — two-way binding + JSON inspection" },
  },
  {
    path: 'filter-builder/seeded-tree-and-or-composition',
    loadComponent: () => import('./features/filter-builder/seeded-tree-and-or-composition.component').then((m) => m.FilterBuilderSeededTreeAndOrComposition),
    data: { lib: 'forms', category: 'filter-builder', demo: "Filter Builder", section: "Seeded tree — and+or composition" },
  },
  {
    path: 'filter-chips/custom-chip-decoration-via-cngxfilterchip',
    loadComponent: () => import('./features/filter-chips/custom-chip-decoration-via-cngxfilterchip.component').then((m) => m.FilterChipsCustomChipDecorationViaCngxfilterchip),
    data: { lib: 'common', category: 'data', demo: "Filter chips", section: "Custom chip decoration via *cngxFilterChip" },
  },
  {
    path: 'filter-chips/multi-role-filter-wired-to-a-list',
    loadComponent: () => import('./features/filter-chips/multi-role-filter-wired-to-a-list.component').then((m) => m.FilterChipsMultiRoleFilterWiredToAList),
    data: { lib: 'common', category: 'data', demo: "Filter chips", section: "Multi-role filter wired to a list" },
  },
  {
    path: 'filter-row-standalone/single-row-with-value',
    loadComponent: () => import('./features/filter-row-standalone/single-row-with-value.component').then((m) => m.FilterRowStandaloneSingleRowWithValue),
    data: { lib: 'forms', category: 'filter-builder', demo: "Filter Row — minimal", section: "Single row with [(value)]" },
  },
  {
    path: 'focus-restore/inline-details',
    loadComponent: () => import('./features/focus-restore/inline-details.component').then((m) => m.FocusRestoreInlineDetails),
    data: { lib: 'common', category: 'a11y', demo: "Focus Restore", section: "Inline Details" },
  },
  {
    path: 'focus-restore/panel-with-automatic-restore',
    loadComponent: () => import('./features/focus-restore/panel-with-automatic-restore.component').then((m) => m.FocusRestorePanelWithAutomaticRestore),
    data: { lib: 'common', category: 'a11y', demo: "Focus Restore", section: "Panel with Automatic Restore" },
  },
  {
    path: 'focus-trap/modal-dialog',
    loadComponent: () => import('./features/focus-trap/modal-dialog.component').then((m) => m.FocusTrapModalDialog),
    data: { lib: 'common', category: 'a11y', demo: "FocusTrap", section: "CngxFocusTrap — Modal Dialog" },
  },
  {
    path: 'focus-trap/slide-out-drawer',
    loadComponent: () => import('./features/focus-trap/slide-out-drawer.component').then((m) => m.FocusTrapSlideOutDrawer),
    data: { lib: 'common', category: 'a11y', demo: "FocusTrap", section: "CngxFocusTrap — Slide-out Drawer" },
  },
  {
    path: 'focus-visible/form-fields-custom-focus-ring',
    loadComponent: () => import('./features/focus-visible/form-fields-custom-focus-ring.component').then((m) => m.FocusVisibleFormFieldsCustomFocusRing),
    data: { lib: 'common', category: 'a11y', demo: "FocusVisible", section: "Form Fields — Custom Focus Ring" },
  },
  {
    path: 'focus-visible/keyboard-vs-pointer',
    loadComponent: () => import('./features/focus-visible/keyboard-vs-pointer.component').then((m) => m.FocusVisibleKeyboardVsPointer),
    data: { lib: 'common', category: 'a11y', demo: "FocusVisible", section: "CngxFocusVisible — Keyboard vs Pointer" },
  },
  {
    path: 'highlight/live-search-highlighting',
    loadComponent: () => import('./features/highlight/live-search-highlighting.component').then((m) => m.HighlightLiveSearchHighlighting),
    data: { lib: 'common', category: 'layout', demo: "Highlight", section: "Live Search Highlighting" },
  },
  {
    path: 'highlight/multiple-paragraphs',
    loadComponent: () => import('./features/highlight/multiple-paragraphs.component').then((m) => m.HighlightMultipleParagraphs),
    data: { lib: 'common', category: 'layout', demo: "Highlight", section: "Multiple Paragraphs" },
  },
  {
    path: 'icon/decorative-vs-informative',
    loadComponent: () => import('./features/icon/decorative-vs-informative.component').then((m) => m.IconDecorativeVsInformative),
    data: { lib: 'common', category: 'display', demo: "Icon", section: "Decorative vs informative" },
  },
  {
    path: 'icon/sizes',
    loadComponent: () => import('./features/icon/sizes.component').then((m) => m.IconSizes),
    data: { lib: 'common', category: 'display', demo: "Icon", section: "Sizes" },
  },
  {
    path: 'infinite-scroll/scrollable-list',
    loadComponent: () => import('./features/infinite-scroll/scrollable-list.component').then((m) => m.InfiniteScrollScrollableList),
    data: { lib: 'common', category: 'layout', demo: "Infinite Scroll", section: "Scrollable List" },
  },
  {
    path: 'input/character-counter',
    loadComponent: () => import('./features/input/character-counter.component').then((m) => m.InputCharacterCounter),
    data: { lib: 'forms', category: 'input', demo: "Input Directives", section: "Character Counter" },
  },
  {
    path: 'input/password-visibility-toggle',
    loadComponent: () => import('./features/input/password-visibility-toggle.component').then((m) => m.InputPasswordVisibilityToggle),
    data: { lib: 'forms', category: 'input', demo: "Input Directives", section: "Password Visibility Toggle" },
  },
  {
    path: 'input/smart-autocomplete-and-spellcheck',
    loadComponent: () => import('./features/input/smart-autocomplete-and-spellcheck.component').then((m) => m.InputSmartAutocompleteAndSpellcheck),
    data: { lib: 'forms', category: 'input', demo: "Input Directives", section: "Smart Autocomplete and Spellcheck" },
  },
  {
    path: 'intersection-observer/scroll-sentinel',
    loadComponent: () => import('./features/intersection-observer/scroll-sentinel.component').then((m) => m.IntersectionObserverScrollSentinel),
    data: { lib: 'common', category: 'layout', demo: "IntersectionObserver", section: "CngxIntersectionObserver — Scroll Sentinel" },
  },
  {
    path: 'keyboard-shortcut/global-shortcut',
    loadComponent: () => import('./features/keyboard-shortcut/global-shortcut.component').then((m) => m.KeyboardShortcutGlobalShortcut),
    data: { lib: 'common', category: 'interactive', demo: "Keyboard Shortcut", section: "Global Shortcut" },
  },
  {
    path: 'keyboard-shortcut/self-scoped-shortcut',
    loadComponent: () => import('./features/keyboard-shortcut/self-scoped-shortcut.component').then((m) => m.KeyboardShortcutSelfScopedShortcut),
    data: { lib: 'common', category: 'interactive', demo: "Keyboard Shortcut", section: "Self-Scoped Shortcut" },
  },
  {
    path: 'layout-skeleton/basic-skeleton',
    loadComponent: () => import('./features/layout-skeleton/basic-skeleton.component').then((m) => m.LayoutSkeletonBasicSkeleton),
    data: { lib: 'common', category: 'layout', demo: "Skeleton Loading", section: "Basic Skeleton" },
  },
  {
    path: 'layout-skeleton/skeleton-container',
    loadComponent: () => import('./features/layout-skeleton/skeleton-container.component').then((m) => m.LayoutSkeletonSkeletonContainer),
    data: { lib: 'common', category: 'layout', demo: "Skeleton Loading", section: "Skeleton Container" },
  },
  {
    path: 'listbox-search/command-palette',
    loadComponent: () => import('./features/listbox-search/command-palette.component').then((m) => m.ListboxSearchCommandPalette),
    data: { lib: 'common', category: 'interactive', demo: "Listbox Search", section: "Command palette" },
  },
  {
    path: 'listbox-trigger/select-dropdown',
    loadComponent: () => import('./features/listbox-trigger/select-dropdown.component').then((m) => m.ListboxTriggerSelectDropdown),
    data: { lib: 'common', category: 'interactive', demo: "Listbox Trigger", section: "Select dropdown" },
  },
  {
    path: 'listbox/multi-select',
    loadComponent: () => import('./features/listbox/multi-select.component').then((m) => m.ListboxMultiSelect),
    data: { lib: 'common', category: 'interactive', demo: "Listbox", section: "Multi-select" },
  },
  {
    path: 'listbox/single-select',
    loadComponent: () => import('./features/listbox/single-select.component').then((m) => m.ListboxSingleSelect),
    data: { lib: 'common', category: 'interactive', demo: "Listbox", section: "Single select" },
  },
  {
    path: 'live-region/form-validation-assertive-error-announcements',
    loadComponent: () => import('./features/live-region/form-validation-assertive-error-announcements.component').then((m) => m.LiveRegionFormValidationAssertiveErrorAnnouncements),
    data: { lib: 'common', category: 'a11y', demo: "LiveRegion", section: "Form Validation — Assertive Error Announcements" },
  },
  {
    path: 'live-region/polite-vs-assertive',
    loadComponent: () => import('./features/live-region/polite-vs-assertive.component').then((m) => m.LiveRegionPoliteVsAssertive),
    data: { lib: 'common', category: 'a11y', demo: "LiveRegion", section: "CngxLiveRegion — Polite vs Assertive" },
  },
  {
    path: 'loading-indicator/bar-variant',
    loadComponent: () => import('./features/loading-indicator/bar-variant.component').then((m) => m.LoadingIndicatorBarVariant),
    data: { lib: 'ui', category: 'feedback', demo: "Loading Indicator", section: "Bar Variant" },
  },
  {
    path: 'loading-indicator/spinner-variant',
    loadComponent: () => import('./features/loading-indicator/spinner-variant.component').then((m) => m.LoadingIndicatorSpinnerVariant),
    data: { lib: 'ui', category: 'feedback', demo: "Loading Indicator", section: "Spinner Variant" },
  },
  {
    path: 'loading-overlay/overlay-with-form',
    loadComponent: () => import('./features/loading-overlay/overlay-with-form.component').then((m) => m.LoadingOverlayOverlayWithForm),
    data: { lib: 'ui', category: 'feedback', demo: "Loading Overlay", section: "Overlay with Form" },
  },
  {
    path: 'long-press/custom-threshold',
    loadComponent: () => import('./features/long-press/custom-threshold.component').then((m) => m.LongPressCustomThreshold),
    data: { lib: 'common', category: 'interactive', demo: "Long Press", section: "Custom Threshold" },
  },
  {
    path: 'long-press/long-press-with-visual-feedback',
    loadComponent: () => import('./features/long-press/long-press-with-visual-feedback.component').then((m) => m.LongPressLongPressWithVisualFeedback),
    data: { lib: 'common', category: 'interactive', demo: "Long Press", section: "Long Press with Visual Feedback" },
  },
  {
    path: 'mask/custom-pattern',
    loadComponent: () => import('./features/mask/custom-pattern.component').then((m) => m.MaskCustomPattern),
    data: { lib: 'forms', category: 'input', demo: "Input Mask", section: "Custom Pattern" },
  },
  {
    path: 'mask/custom-tokens-and-transform',
    loadComponent: () => import('./features/mask/custom-tokens-and-transform.component').then((m) => m.MaskCustomTokensAndTransform),
    data: { lib: 'forms', category: 'input', demo: "Input Mask", section: "Custom Tokens and Transform" },
  },
  {
    path: 'mask/locale-presets',
    loadComponent: () => import('./features/mask/locale-presets.component').then((m) => m.MaskLocalePresets),
    data: { lib: 'forms', category: 'input', demo: "Input Mask", section: "Locale Presets" },
  },
  {
    path: 'mat-paginator/headless-custom-pagination-controls',
    loadComponent: () => import('./features/mat-paginator/headless-custom-pagination-controls.component').then((m) => m.MatPaginatorHeadlessCustomPaginationControls),
    data: { lib: 'ui', category: '', demo: "MatPaginator", section: "Headless — Custom Pagination Controls" },
  },
  {
    path: 'mat-paginator/material-paginator',
    loadComponent: () => import('./features/mat-paginator/material-paginator.component').then((m) => m.MatPaginatorMaterialPaginator),
    data: { lib: 'ui', category: '', demo: "MatPaginator", section: "CngxMatPaginator — Material Paginator" },
  },
  {
    path: 'mat-stepper-instrumentation/vanilla-mat-stepper-upgraded-by-adding-cngxmatstepper',
    loadComponent: () => import('./features/mat-stepper-instrumentation/vanilla-mat-stepper-upgraded-by-adding-cngxmatstepper.component').then((m) => m.MatStepperInstrumentationVanillaMatStepperUpgradedByAddingCngxmatstepper),
    data: { lib: 'ui', category: 'mat-stepper', demo: "Mat-stepper — instrumentation directive", section: "Vanilla <mat-stepper> upgraded by adding cngxMatStepper" },
  },
  {
    path: 'mat-stepper-router-sync/deep-linking-against-material',
    loadComponent: () => import('./features/mat-stepper-router-sync/deep-linking-against-material.component').then((m) => m.MatStepperRouterSyncDeepLinkingAgainstMaterial),
    data: { lib: 'ui', category: 'mat-stepper', demo: "Mat-Stepper — router sync", section: "Deep-linking against Material" },
  },
  {
    path: 'material/mat-select-via-cngxbindfield-reactive-forms',
    loadComponent: () => import('./features/material/mat-select-via-cngxbindfield-reactive-forms.component').then((m) => m.MaterialMatSelectViaCngxbindfieldReactiveForms),
    data: { lib: 'forms', category: 'field', demo: "Material Integration", section: "mat-select via CngxBindField + Reactive Forms" },
  },
  {
    path: 'material/matinput-via-cngxbindfield',
    loadComponent: () => import('./features/material/matinput-via-cngxbindfield.component').then((m) => m.MaterialMatinputViaCngxbindfield),
    data: { lib: 'forms', category: 'field', demo: "Material Integration", section: "matInput via CngxBindField" },
  },
  {
    path: 'media-query/viewport-breakpoints',
    loadComponent: () => import('./features/media-query/viewport-breakpoints.component').then((m) => m.MediaQueryViewportBreakpoints),
    data: { lib: 'common', category: 'layout', demo: "MediaQuery", section: "CngxMediaQuery — Viewport Breakpoints" },
  },
  {
    path: 'menu-checkable/text-formatting-menu',
    loadComponent: () => import('./features/menu-checkable/text-formatting-menu.component').then((m) => m.MenuCheckableTextFormattingMenu),
    data: { lib: 'common', category: 'interactive', demo: "Checkable Menu Items", section: "Text formatting menu" },
  },
  {
    path: 'menu-submenu/two-level-submenu',
    loadComponent: () => import('./features/menu-submenu/two-level-submenu.component').then((m) => m.MenuSubmenuTwoLevelSubmenu),
    data: { lib: 'common', category: 'interactive', demo: "Menu Submenu", section: "Two-level submenu" },
  },
  {
    path: 'menu-trigger/dropdown-menu',
    loadComponent: () => import('./features/menu-trigger/dropdown-menu.component').then((m) => m.MenuTriggerDropdownMenu),
    data: { lib: 'common', category: 'interactive', demo: "Menu Trigger", section: "Dropdown menu" },
  },
  {
    path: 'menu/action-menu-with-separator',
    loadComponent: () => import('./features/menu/action-menu-with-separator.component').then((m) => m.MenuActionMenuWithSeparator),
    data: { lib: 'common', category: 'interactive', demo: "Menu", section: "Action menu with separator" },
  },
  {
    path: 'metric/inside-a-card',
    loadComponent: () => import('./features/metric/inside-a-card.component').then((m) => m.MetricInsideACard),
    data: { lib: 'common', category: 'data', demo: "Metric", section: "Inside a Card" },
  },
  {
    path: 'metric/standalone-metrics',
    loadComponent: () => import('./features/metric/standalone-metrics.component').then((m) => m.MetricStandaloneMetrics),
    data: { lib: 'common', category: 'data', demo: "Metric", section: "Standalone Metrics" },
  },
  {
    path: 'mini-area/async-state-machine',
    loadComponent: () => import('./features/mini-area/async-state-machine.component').then((m) => m.MiniAreaAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Mini Area", section: "Async state machine" },
  },
  {
    path: 'mini-area/inline-area-trends',
    loadComponent: () => import('./features/mini-area/inline-area-trends.component').then((m) => m.MiniAreaInlineAreaTrends),
    data: { lib: 'common', category: 'chart', demo: "Mini Area", section: "Inline area trends" },
  },
  {
    path: 'mini-bar/async-state-machine',
    loadComponent: () => import('./features/mini-bar/async-state-machine.component').then((m) => m.MiniBarAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Mini Bar", section: "Async state machine" },
  },
  {
    path: 'mini-bar/basic-readings',
    loadComponent: () => import('./features/mini-bar/basic-readings.component').then((m) => m.MiniBarBasicReadings),
    data: { lib: 'common', category: 'chart', demo: "Mini Bar", section: "Basic readings" },
  },
  {
    path: 'multi-chip-group/multi-select-chips-with-selection-count',
    loadComponent: () => import('./features/multi-chip-group/multi-select-chips-with-selection-count.component').then((m) => m.MultiChipGroupMultiSelectChipsWithSelectionCount),
    data: { lib: 'common', category: 'interactive', demo: "Multi chip group (multi-select)", section: "Multi-select chips with selection count" },
  },
  {
    path: 'nav/nav-badge-counts-and-dots',
    loadComponent: () => import('./features/nav/nav-badge-counts-and-dots.component').then((m) => m.NavNavBadgeCountsAndDots),
    data: { lib: 'common', category: 'interactive', demo: "Nav", section: "Nav Badge — Counts and Dots" },
  },
  {
    path: 'nav/nav-group-accordion-sections',
    loadComponent: () => import('./features/nav/nav-group-accordion-sections.component').then((m) => m.NavNavGroupAccordionSections),
    data: { lib: 'common', category: 'interactive', demo: "Nav", section: "Nav Group — Accordion Sections" },
  },
  {
    path: 'nav/nav-links-active-state-depth',
    loadComponent: () => import('./features/nav/nav-links-active-state-depth.component').then((m) => m.NavNavLinksActiveStateDepth),
    data: { lib: 'common', category: 'interactive', demo: "Nav", section: "Nav Links — Active State + Depth" },
  },
  {
    path: 'numeric/basic-numeric-input',
    loadComponent: () => import('./features/numeric/basic-numeric-input.component').then((m) => m.NumericBasicNumericInput),
    data: { lib: 'forms', category: 'input', demo: "Numeric Input", section: "Basic Numeric Input" },
  },
  {
    path: 'numeric/locale-formatting',
    loadComponent: () => import('./features/numeric/locale-formatting.component').then((m) => m.NumericLocaleFormatting),
    data: { lib: 'forms', category: 'input', demo: "Numeric Input", section: "Locale Formatting" },
  },
  {
    path: 'numeric/min-max-step-decimals',
    loadComponent: () => import('./features/numeric/min-max-step-decimals.component').then((m) => m.NumericMinMaxStepDecimals),
    data: { lib: 'forms', category: 'input', demo: "Numeric Input", section: "Min / Max / Step / Decimals" },
  },
  {
    path: 'option/flat-options-with-ad',
    loadComponent: () => import('./features/option/flat-options-with-ad.component').then((m) => m.OptionFlatOptionsWithAd),
    data: { lib: 'common', category: 'interactive', demo: "Option", section: "Flat options with AD" },
  },
  {
    path: 'option/grouped-options',
    loadComponent: () => import('./features/option/grouped-options.component').then((m) => m.OptionGroupedOptions),
    data: { lib: 'common', category: 'interactive', demo: "Option", section: "Grouped options" },
  },
  {
    path: 'otp/4-digit-pin',
    loadComponent: () => import('./features/otp/4-digit-pin.component').then((m) => m.Otp4DigitPin),
    data: { lib: 'forms', category: 'input', demo: "OTP Input", section: "4-Digit PIN" },
  },
  {
    path: 'otp/6-digit-otp',
    loadComponent: () => import('./features/otp/6-digit-otp.component').then((m) => m.Otp6DigitOtp),
    data: { lib: 'forms', category: 'input', demo: "OTP Input", section: "6-Digit OTP" },
  },
  {
    path: 'paginate-list/paginated-list-cngxpaginate-cngxmatpaginator',
    loadComponent: () => import('./features/paginate-list/paginated-list-cngxpaginate-cngxmatpaginator.component').then((m) => m.PaginateListPaginatedListCngxpaginateCngxmatpaginator),
    data: { lib: 'common', category: 'data', demo: "Paginate — List", section: "Paginated List — CngxPaginate + CngxMatPaginator" },
  },
  {
    path: 'paginate-list/uncontrolled-mode-zero-class-boilerplate',
    loadComponent: () => import('./features/paginate-list/uncontrolled-mode-zero-class-boilerplate.component').then((m) => m.PaginateListUncontrolledModeZeroClassBoilerplate),
    data: { lib: 'common', category: 'data', demo: "Paginate — List", section: "Uncontrolled Mode — Zero Class Boilerplate" },
  },
  {
    path: 'popover-panel/content-states',
    loadComponent: () => import('./features/popover-panel/content-states.component').then((m) => m.PopoverPanelContentStates),
    data: { lib: 'common', category: 'popover', demo: "Popover Panel", section: "Content States" },
  },
  {
    path: 'popover-panel/variants',
    loadComponent: () => import('./features/popover-panel/variants.component').then((m) => m.PopoverPanelVariants),
    data: { lib: 'common', category: 'popover', demo: "Popover Panel", section: "Variants" },
  },
  {
    path: 'popover-panel/with-footer-actions',
    loadComponent: () => import('./features/popover-panel/with-footer-actions.component').then((m) => m.PopoverPanelWithFooterActions),
    data: { lib: 'common', category: 'popover', demo: "Popover Panel", section: "With Footer Actions" },
  },
  {
    path: 'popover/click-popover',
    loadComponent: () => import('./features/popover/click-popover.component').then((m) => m.PopoverClickPopover),
    data: { lib: 'common', category: 'popover', demo: "Popover", section: "Click Popover" },
  },
  {
    path: 'popover/controlled-open',
    loadComponent: () => import('./features/popover/controlled-open.component').then((m) => m.PopoverControlledOpen),
    data: { lib: 'common', category: 'popover', demo: "Popover", section: "Controlled Open" },
  },
  {
    path: 'popover/escape-mode',
    loadComponent: () => import('./features/popover/escape-mode.component').then((m) => m.PopoverEscapeMode),
    data: { lib: 'common', category: 'popover', demo: "Popover", section: "Escape & Mode" },
  },
  {
    path: 'popover/placement-variants',
    loadComponent: () => import('./features/popover/placement-variants.component').then((m) => m.PopoverPlacementVariants),
    data: { lib: 'common', category: 'popover', demo: "Popover", section: "Placement Variants" },
  },
  {
    path: 'press-ripple/buttons-with-press-ripple',
    loadComponent: () => import('./features/press-ripple/buttons-with-press-ripple.component').then((m) => m.PressRippleButtonsWithPressRipple),
    data: { lib: 'common', category: 'interactive', demo: "Press + Ripple", section: "Buttons with Press + Ripple" },
  },
  {
    path: 'pressable/press-feedback-on-buttons',
    loadComponent: () => import('./features/pressable/press-feedback-on-buttons.component').then((m) => m.PressablePressFeedbackOnButtons),
    data: { lib: 'common', category: 'interactive', demo: "Pressable", section: "Press Feedback on Buttons" },
  },
  {
    path: 'pressable/tappable-card',
    loadComponent: () => import('./features/pressable/tappable-card.component').then((m) => m.PressableTappableCard),
    data: { lib: 'common', category: 'interactive', demo: "Pressable", section: "Tappable Card" },
  },
  {
    path: 'progress/circular-variant',
    loadComponent: () => import('./features/progress/circular-variant.component').then((m) => m.ProgressCircularVariant),
    data: { lib: 'ui', category: 'feedback', demo: "Progress", section: "Circular Variant" },
  },
  {
    path: 'progress/linear-determinate',
    loadComponent: () => import('./features/progress/linear-determinate.component').then((m) => m.ProgressLinearDeterminate),
    data: { lib: 'ui', category: 'feedback', demo: "Progress", section: "Linear — Determinate" },
  },
  {
    path: 'progress/linear-indeterminate',
    loadComponent: () => import('./features/progress/linear-indeterminate.component').then((m) => m.ProgressLinearIndeterminate),
    data: { lib: 'ui', category: 'feedback', demo: "Progress", section: "Linear — Indeterminate" },
  },
  {
    path: 'radio-indicator/custom-dotglyph',
    loadComponent: () => import('./features/radio-indicator/custom-dotglyph.component').then((m) => m.RadioIndicatorCustomDotglyph),
    data: { lib: 'common', category: 'display', demo: "Radio indicator", section: "Custom dotGlyph" },
  },
  {
    path: 'radio-indicator/default-unchecked-vs-checked',
    loadComponent: () => import('./features/radio-indicator/default-unchecked-vs-checked.component').then((m) => m.RadioIndicatorDefaultUncheckedVsChecked),
    data: { lib: 'common', category: 'display', demo: "Radio indicator", section: "Default — unchecked vs checked" },
  },
  {
    path: 'radio-indicator/disabled',
    loadComponent: () => import('./features/radio-indicator/disabled.component').then((m) => m.RadioIndicatorDisabled),
    data: { lib: 'common', category: 'display', demo: "Radio indicator", section: "Disabled" },
  },
  {
    path: 'radio-indicator/sizes',
    loadComponent: () => import('./features/radio-indicator/sizes.component').then((m) => m.RadioIndicatorSizes),
    data: { lib: 'common', category: 'display', demo: "Radio indicator", section: "Sizes" },
  },
  {
    path: 'radio-indicator/theming-via-css-custom-properties',
    loadComponent: () => import('./features/radio-indicator/theming-via-css-custom-properties.component').then((m) => m.RadioIndicatorThemingViaCssCustomProperties),
    data: { lib: 'common', category: 'display', demo: "Radio indicator", section: "Theming via CSS custom properties" },
  },
  {
    path: 'radio/basic-vertical-group',
    loadComponent: () => import('./features/radio/basic-vertical-group.component').then((m) => m.RadioBasicVerticalGroup),
    data: { lib: 'common', category: 'interactive', demo: "Radio group", section: "Basic — vertical group" },
  },
  {
    path: 'radio/custom-dot-glyph',
    loadComponent: () => import('./features/radio/custom-dot-glyph.component').then((m) => m.RadioCustomDotGlyph),
    data: { lib: 'common', category: 'interactive', demo: "Radio group", section: "Custom dot glyph" },
  },
  {
    path: 'radio/disabled-group-cascades-per-radio-overrides',
    loadComponent: () => import('./features/radio/disabled-group-cascades-per-radio-overrides.component').then((m) => m.RadioDisabledGroupCascadesPerRadioOverrides),
    data: { lib: 'common', category: 'interactive', demo: "Radio group", section: "Disabled — group cascades, per-radio overrides" },
  },
  {
    path: 'radio/orientation-horizontal',
    loadComponent: () => import('./features/radio/orientation-horizontal.component').then((m) => m.RadioOrientationHorizontal),
    data: { lib: 'common', category: 'interactive', demo: "Radio group", section: "Orientation — horizontal" },
  },
  {
    path: 'reduced-motion/animation-toggle',
    loadComponent: () => import('./features/reduced-motion/animation-toggle.component').then((m) => m.ReducedMotionAnimationToggle),
    data: { lib: 'common', category: 'a11y', demo: "ReducedMotion", section: "CngxReducedMotion — Animation Toggle" },
  },
  {
    path: 'reduced-motion/toast-notifications-motion-aware',
    loadComponent: () => import('./features/reduced-motion/toast-notifications-motion-aware.component').then((m) => m.ReducedMotionToastNotificationsMotionAware),
    data: { lib: 'common', category: 'a11y', demo: "ReducedMotion", section: "Toast Notifications — Motion-aware" },
  },
  {
    path: 'resize-observer/live-size',
    loadComponent: () => import('./features/resize-observer/live-size.component').then((m) => m.ResizeObserverLiveSize),
    data: { lib: 'common', category: 'layout', demo: "ResizeObserver", section: "CngxResizeObserver — Live Size" },
  },
  {
    path: 'retry/optimistic-instant-like-toggle',
    loadComponent: () => import('./features/retry/optimistic-instant-like-toggle.component').then((m) => m.RetryOptimisticInstantLikeToggle),
    data: { lib: 'common', category: 'interactive', demo: "Retry + Optimistic", section: "optimistic() — Instant Like Toggle" },
  },
  {
    path: 'retry/withretry-cngxasyncclick',
    loadComponent: () => import('./features/retry/withretry-cngxasyncclick.component').then((m) => m.RetryWithretryCngxasyncclick),
    data: { lib: 'common', category: 'interactive', demo: "Retry + Optimistic", section: "withRetry + CngxAsyncClick" },
  },
  {
    path: 'ripple/button-ripples',
    loadComponent: () => import('./features/ripple/button-ripples.component').then((m) => m.RippleButtonRipples),
    data: { lib: 'common', category: 'interactive', demo: "Ripple", section: "Button Ripples" },
  },
  {
    path: 'ripple/card-with-ripple',
    loadComponent: () => import('./features/ripple/card-with-ripple.component').then((m) => m.RippleCardWithRipple),
    data: { lib: 'common', category: 'interactive', demo: "Ripple", section: "Card with Ripple" },
  },
  {
    path: 'roving-tabindex/horizontal-toolbar',
    loadComponent: () => import('./features/roving-tabindex/horizontal-toolbar.component').then((m) => m.RovingTabindexHorizontalToolbar),
    data: { lib: 'common', category: 'a11y', demo: "Roving Tabindex", section: "Horizontal Toolbar" },
  },
  {
    path: 'roving-tabindex/vertical-menu',
    loadComponent: () => import('./features/roving-tabindex/vertical-menu.component').then((m) => m.RovingTabindexVerticalMenu),
    data: { lib: 'common', category: 'a11y', demo: "Roving Tabindex", section: "Vertical Menu" },
  },
  {
    path: 'scroll-lock/toggle',
    loadComponent: () => import('./features/scroll-lock/toggle.component').then((m) => m.ScrollLockToggle),
    data: { lib: 'common', category: 'layout', demo: "ScrollLock", section: "CngxScrollLock — Toggle" },
  },
  {
    path: 'scroll-spy/scroll-based-navigation',
    loadComponent: () => import('./features/scroll-spy/scroll-based-navigation.component').then((m) => m.ScrollSpyScrollBasedNavigation),
    data: { lib: 'common', category: 'layout', demo: "Scroll Spy", section: "Scroll-Based Navigation" },
  },
  {
    path: 'sidenav/dual-sidebar-master-detail',
    loadComponent: () => import('./features/sidenav/dual-sidebar-master-detail.component').then((m) => m.SidenavDualSidebarMasterDetail),
    data: { lib: 'ui', category: '', demo: "Sidenav", section: "Dual Sidebar -- Master/Detail" },
  },
  {
    path: 'sidenav/full-navigation-sidebar',
    loadComponent: () => import('./features/sidenav/full-navigation-sidebar.component').then((m) => m.SidenavFullNavigationSidebar),
    data: { lib: 'ui', category: '', demo: "Sidenav", section: "Full Navigation Sidebar" },
  },
  {
    path: 'sidenav/material-theming-light-vs-dark',
    loadComponent: () => import('./features/sidenav/material-theming-light-vs-dark.component').then((m) => m.SidenavMaterialThemingLightVsDark),
    data: { lib: 'ui', category: '', demo: "Sidenav", section: "Material Theming -- Light vs Dark" },
  },
  {
    path: 'sparkline/async-state-machine',
    loadComponent: () => import('./features/sparkline/async-state-machine.component').then((m) => m.SparklineAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Sparkline", section: "Async state machine" },
  },
  {
    path: 'sparkline/basic-sparklines',
    loadComponent: () => import('./features/sparkline/basic-sparklines.component').then((m) => m.SparklineBasicSparklines),
    data: { lib: 'common', category: 'chart', demo: "Sparkline", section: "Basic sparklines" },
  },
  {
    path: 'sparkline/with-area-fill',
    loadComponent: () => import('./features/sparkline/with-area-fill.component').then((m) => m.SparklineWithAreaFill),
    data: { lib: 'common', category: 'chart', demo: "Sparkline", section: "With area fill" },
  },
  {
    path: 'speak-button/material-integration-theme-scss-mat-icon-button',
    loadComponent: () => import('./features/speak-button/material-integration-theme-scss-mat-icon-button.component').then((m) => m.SpeakButtonMaterialIntegrationThemeScssMatIconButton),
    data: { lib: 'ui', category: '', demo: "SpeakButton", section: "Material Integration — Theme SCSS + mat-icon-button" },
  },
  {
    path: 'speak-button/styled-speaker-icon',
    loadComponent: () => import('./features/speak-button/styled-speaker-icon.component').then((m) => m.SpeakButtonStyledSpeakerIcon),
    data: { lib: 'ui', category: '', demo: "SpeakButton", section: "CngxSpeakButton — Styled Speaker Icon" },
  },
  {
    path: 'speak-button/theming-css-custom-properties',
    loadComponent: () => import('./features/speak-button/theming-css-custom-properties.component').then((m) => m.SpeakButtonThemingCssCustomProperties),
    data: { lib: 'ui', category: '', demo: "SpeakButton", section: "Theming — CSS Custom Properties" },
  },
  {
    path: 'speak/form-error-read-aloud-on-demand',
    loadComponent: () => import('./features/speak/form-error-read-aloud-on-demand.component').then((m) => m.SpeakFormErrorReadAloudOnDemand),
    data: { lib: 'common', category: 'interactive', demo: "Speak", section: "Form Error — Read-aloud on Demand" },
  },
  {
    path: 'speak/headless-read-aloud',
    loadComponent: () => import('./features/speak/headless-read-aloud.component').then((m) => m.SpeakHeadlessReadAloud),
    data: { lib: 'common', category: 'interactive', demo: "Speak", section: "CngxSpeak — Headless Read-aloud" },
  },
  {
    path: 'stacked-bar/async-state-machine',
    loadComponent: () => import('./features/stacked-bar/async-state-machine.component').then((m) => m.StackedBarAsyncStateMachine),
    data: { lib: 'common', category: 'chart', demo: "Stacked Bar", section: "Async state machine" },
  },
  {
    path: 'stacked-bar/proportional-share-strips',
    loadComponent: () => import('./features/stacked-bar/proportional-share-strips.component').then((m) => m.StackedBarProportionalShareStrips),
    data: { lib: 'common', category: 'chart', demo: "Stacked Bar", section: "Proportional share strips" },
  },
  {
    path: 'stepper-custom-labels/mixing-code-label-code-input-with-code-cngxsteplabel-code-slot',
    loadComponent: () => import('./features/stepper-custom-labels/mixing-code-label-code-input-with-code-cngxsteplabel-code-slot.component').then((m) => m.StepperCustomLabelsMixingCodeLabelCodeInputWithCodeCngxsteplabelCodeSlot),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — custom labels", section: "Mixing <code>[label]</code> Input with <code>cngxStepLabel</code> slot" },
  },
  {
    path: 'stepper-error-aggregation/per-step-error-badges',
    loadComponent: () => import('./features/stepper-error-aggregation/per-step-error-badges.component').then((m) => m.StepperErrorAggregationPerStepErrorBadges),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — error aggregation", section: "Per-step error badges" },
  },
  {
    path: 'stepper-hierarchical/group-nested-steps-trailing-root-step',
    loadComponent: () => import('./features/stepper-hierarchical/group-nested-steps-trailing-root-step.component').then((m) => m.StepperHierarchicalGroupNestedStepsTrailingRootStep),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — hierarchical sub-steps", section: "Group + nested steps + trailing root step" },
  },
  {
    path: 'stepper-horizontal/three-step-wizard',
    loadComponent: () => import('./features/stepper-horizontal/three-step-wizard.component').then((m) => m.StepperHorizontalThreeStepWizard),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — horizontal", section: "Three-step wizard" },
  },
  {
    path: 'stepper-linear/linear-gating-with-completion-checkboxes',
    loadComponent: () => import('./features/stepper-linear/linear-gating-with-completion-checkboxes.component').then((m) => m.StepperLinearLinearGatingWithCompletionCheckboxes),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — linear mode", section: "Linear gating with completion checkboxes" },
  },
  {
    path: 'stepper-router-sync/deep-linking-with-fragment-queryparam-modes',
    loadComponent: () => import('./features/stepper-router-sync/deep-linking-with-fragment-queryparam-modes.component').then((m) => m.StepperRouterSyncDeepLinkingWithFragmentQueryparamModes),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — router sync", section: "Deep-linking with fragment + queryParam modes" },
  },
  {
    path: 'stepper-vertical/vertical-sidebar-layout',
    loadComponent: () => import('./features/stepper-vertical/vertical-sidebar-layout.component').then((m) => m.StepperVerticalVerticalSidebarLayout),
    data: { lib: 'ui', category: 'stepper', demo: "Stepper — vertical", section: "Vertical sidebar layout" },
  },
  {
    path: 'sticky-header/sticky-header-with-shadow',
    loadComponent: () => import('./features/sticky-header/sticky-header-with-shadow.component').then((m) => m.StickyHeaderStickyHeaderWithShadow),
    data: { lib: 'common', category: 'layout', demo: "Sticky Header", section: "Sticky Header with Shadow" },
  },
  {
    path: 'swipe-dismiss/directional-swipe',
    loadComponent: () => import('./features/swipe-dismiss/directional-swipe.component').then((m) => m.SwipeDismissDirectionalSwipe),
    data: { lib: 'common', category: 'interactive', demo: "SwipeDismiss", section: "CngxSwipeDismiss — Directional Swipe" },
  },
  {
    path: 'tab-error-aggregation/per-tab-error-badges',
    loadComponent: () => import('./features/tab-error-aggregation/per-tab-error-badges.component').then((m) => m.TabErrorAggregationPerTabErrorBadges),
    data: { lib: 'ui', category: 'tabs', demo: "Tabs — error aggregation", section: "Per-tab error badges" },
  },
  {
    path: 'tab-group-vertical/vertical-sidebar-tabs',
    loadComponent: () => import('./features/tab-group-vertical/vertical-sidebar-tabs.component').then((m) => m.TabGroupVerticalVerticalSidebarTabs),
    data: { lib: 'ui', category: 'tabs', demo: "Tabs — vertical", section: "Vertical sidebar tabs" },
  },
  {
    path: 'tab-group/three-tab-navigation',
    loadComponent: () => import('./features/tab-group/three-tab-navigation.component').then((m) => m.TabGroupThreeTabNavigation),
    data: { lib: 'ui', category: 'tabs', demo: "Tabs — horizontal", section: "Three-tab navigation" },
  },
  {
    path: 'tab-overflow/8-tabs-in-a-narrow-container',
    loadComponent: () => import('./features/tab-overflow/8-tabs-in-a-narrow-container.component').then((m) => m.TabOverflow8TabsInANarrowContainer),
    data: { lib: 'ui', category: 'tabs', demo: "Tabs — overflow dropdown", section: "8 tabs in a narrow container" },
  },
  {
    path: 'toggle/basic-two-way-binding',
    loadComponent: () => import('./features/toggle/basic-two-way-binding.component').then((m) => m.ToggleBasicTwoWayBinding),
    data: { lib: 'common', category: 'interactive', demo: "Toggle", section: "Basic — two-way binding" },
  },
  {
    path: 'toggle/custom-thumb-glyph',
    loadComponent: () => import('./features/toggle/custom-thumb-glyph.component').then((m) => m.ToggleCustomThumbGlyph),
    data: { lib: 'common', category: 'interactive', demo: "Toggle", section: "Custom thumb glyph" },
  },
  {
    path: 'toggle/disabled-with-reason',
    loadComponent: () => import('./features/toggle/disabled-with-reason.component').then((m) => m.ToggleDisabledWithReason),
    data: { lib: 'common', category: 'interactive', demo: "Toggle", section: "Disabled with reason" },
  },
  {
    path: 'toggle/label-position',
    loadComponent: () => import('./features/toggle/label-position.component').then((m) => m.ToggleLabelPosition),
    data: { lib: 'common', category: 'interactive', demo: "Toggle", section: "Label position" },
  },
  {
    path: 'tooltip/basic-tooltip',
    loadComponent: () => import('./features/tooltip/basic-tooltip.component').then((m) => m.TooltipBasicTooltip),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Basic Tooltip" },
  },
  {
    path: 'tooltip/custom-delay',
    loadComponent: () => import('./features/tooltip/custom-delay.component').then((m) => m.TooltipCustomDelay),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Custom Delay" },
  },
  {
    path: 'tooltip/disabled-state',
    loadComponent: () => import('./features/tooltip/disabled-state.component').then((m) => m.TooltipDisabledState),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Disabled State" },
  },
  {
    path: 'tooltip/keyboard-navigation',
    loadComponent: () => import('./features/tooltip/keyboard-navigation.component').then((m) => m.TooltipKeyboardNavigation),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Keyboard Navigation" },
  },
  {
    path: 'tooltip/placement',
    loadComponent: () => import('./features/tooltip/placement.component').then((m) => m.TooltipPlacement),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Placement" },
  },
  {
    path: 'tooltip/programmatic-control',
    loadComponent: () => import('./features/tooltip/programmatic-control.component').then((m) => m.TooltipProgrammaticControl),
    data: { lib: 'common', category: 'popover', demo: "Tooltip", section: "Programmatic Control" },
  },
  {
    path: 'trend/composed-with-metric-in-a-card',
    loadComponent: () => import('./features/trend/composed-with-metric-in-a-card.component').then((m) => m.TrendComposedWithMetricInACard),
    data: { lib: 'common', category: 'data', demo: "Trend", section: "Composed with Metric in a Card" },
  },
  {
    path: 'trend/trend-directions',
    loadComponent: () => import('./features/trend/trend-directions.component').then((m) => m.TrendTrendDirections),
    data: { lib: 'common', category: 'data', demo: "Trend", section: "Trend Directions" },
  },
  {
    path: 'truncate/short-text-no-toggle',
    loadComponent: () => import('./features/truncate/short-text-no-toggle.component').then((m) => m.TruncateShortTextNoToggle),
    data: { lib: 'common', category: 'layout', demo: "Truncate", section: "Short Text — No Toggle" },
  },
  {
    path: 'truncate/truncated-text-with-toggle',
    loadComponent: () => import('./features/truncate/truncated-text-with-toggle.component').then((m) => m.TruncateTruncatedTextWithToggle),
    data: { lib: 'common', category: 'layout', demo: "Truncate", section: "Truncated Text with Toggle" },
  },
  {
    path: 'ui-skeleton/card-skeleton',
    loadComponent: () => import('./features/ui-skeleton/card-skeleton.component').then((m) => m.UiSkeletonCardSkeleton),
    data: { lib: 'ui', category: '', demo: "SkeletonContainer", section: "Card Skeleton" },
  },
  {
    path: 'ui-skeleton/template-context',
    loadComponent: () => import('./features/ui-skeleton/template-context.component').then((m) => m.UiSkeletonTemplateContext),
    data: { lib: 'ui', category: '', demo: "SkeletonContainer", section: "Template Context" },
  },
  {
    path: 'utilities/copy-to-clipboard',
    loadComponent: () => import('./features/utilities/copy-to-clipboard.component').then((m) => m.UtilitiesCopyToClipboard),
    data: { lib: 'forms', category: 'input', demo: "Input Utilities", section: "Copy to Clipboard" },
  },
  {
    path: 'utilities/input-clear',
    loadComponent: () => import('./features/utilities/input-clear.component').then((m) => m.UtilitiesInputClear),
    data: { lib: 'forms', category: 'input', demo: "Input Utilities", section: "Input Clear" },
  },
  {
    path: 'utilities/input-format',
    loadComponent: () => import('./features/utilities/input-format.component').then((m) => m.UtilitiesInputFormat),
    data: { lib: 'forms', category: 'input', demo: "Input Utilities", section: "Input Format" },
  },
  {
    path: '',
    loadComponent: () => import('./home/home.component').then((m) => m.HomeComponent),
  },
  { path: '**', redirectTo: '' },
];
