// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/ui/feedback/loading-overlay-demo/loading-overlay-demo.story.ts

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ExampleCardComponent } from '../../../../shared/example-card.component';
import { DocShellComponent } from '../../../../shared/doc-shell.component';
import { CngxLoadingOverlay } from '@cngx/ui/feedback';

@Component({
  selector: 'app-loading-overlay-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxLoadingOverlay,
  ],
  template: `
    <app-doc-shell title="Loading Overlay"
      description="Content container that blocks interaction with inert, renders backdrop + spinner, and manages focus save/restore."
      [apiComponents]="['CngxLoadingOverlay']">
      <app-example-card title="Overlay with Form"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0">
        
  <button (click)="handleLoad()" class="chip" style="margin-bottom:16px">
    {{ isLoading() ? 'Saving...' : 'Save (3s)' }}
  </button>

  <cngx-loading-overlay [loading]="isLoading()" label="Saving form">
    <div style="border:1px solid var(--cngx-border,#ddd);border-radius:8px;padding:24px;display:flex;flex-direction:column;gap:12px">
      <input placeholder="Name" style="padding:8px 12px;border:1px solid var(--cngx-border,#ddd);border-radius:6px" />
      <input placeholder="Email" style="padding:8px 12px;border:1px solid var(--cngx-border,#ddd);border-radius:6px" />
      <button type="button" class="chip">A button inside the overlay</button>
    </div>
  </cngx-loading-overlay>
      </app-example-card>
    </app-doc-shell>
  `,
})
export class LoadingOverlayDemoComponent {
  protected readonly _s0 = 'Click "Save" to overlay the form. Focus inside is saved and restored after loading completes.';
  protected readonly _srcHtml0 = `<button (click)="handleLoad()" class="chip" style="margin-bottom:16px">
    {{ isLoading() ? 'Saving...' : 'Save (3s)' }}
  </button>

  <cngx-loading-overlay [loading]="isLoading()" label="Saving form">
    <div style="border:1px solid var(--cngx-border,#ddd);border-radius:8px;padding:24px;display:flex;flex-direction:column;gap:12px">
      <input placeholder="Name" style="padding:8px 12px;border:1px solid var(--cngx-border,#ddd);border-radius:6px" />
      <input placeholder="Email" style="padding:8px 12px;border:1px solid var(--cngx-border,#ddd);border-radius:6px" />
      <button type="button" class="chip">A button inside the overlay</button>
    </div>
  </cngx-loading-overlay>`;
  protected readonly _srcTs0 = `import { CngxLoadingOverlay } from '@cngx/ui/feedback';


  protected readonly isLoading = signal(false);

  protected handleLoad(): void {
    this.isLoading.set(true);
    setTimeout(() => this.isLoading.set(false), 3000);
  }`;

  protected readonly isLoading = signal(false);

  protected handleLoad(): void {
    this.isLoading.set(true);
    setTimeout(() => this.isLoading.set(false), 3000);
  }
  
}
