// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/ui/feedback/toast-demo/toast-demo.story.ts#section[3] "Declarative (<cngx-toast>)"

import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CngxToaster, CngxToast } from '@cngx/ui/feedback';
import { createManualState } from '@cngx/common/data';
import { SampleToastBody } from './sample-toast-body';

@Component({
  selector: 'app-toast-declarative-cngx-toast',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxToast],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div style="display:flex;gap:8px">
        <button (click)="triggerSave()" class="chip">Save Item</button>
        <button (click)="triggerDelete()" class="chip">Delete Item</button>
      </div>

      <cngx-toast severity="success" message="Item saved" [when]="showSaved()" />
      <cngx-toast severity="warning" message="Item deleted — this cannot be undone" [when]="showDeleted()" [duration]="8000" />
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class ToastDeclarativeCngxToast {
  protected readonly _exTitle: string = 'Toast';
  protected readonly _exDescription: string = 'Programmatic and declarative toast notifications with dedup, timer pause on hover/touch, and severity-based styling.';
  protected readonly _exSectionTitle: string = 'Declarative (<cngx-toast>)';
  protected readonly _exSubtitle: string = 'Place <code>&lt;cngx-toast&gt;</code> in your template. It renders nothing — pushes into the global outlet when <code>[when]</code> becomes <code>true</code>.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'organism' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'audience', value: 'a11y' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'async-state' }, { dim: 'focus', value: 'composition' }, { dim: 'focus', value: 'a11y-pattern' }];
  protected readonly _exTs: string = `import { CngxToaster, CngxToast } from '@cngx/ui/feedback';
import { createManualState } from '@cngx/common/data';
import { SampleToastBody } from './sample-toast-body';

private readonly toaster = inject(CngxToaster);

// ── Programmatic demos ──
protected showSuccess(): void {
  this.toaster.show({ message: 'Item saved successfully', severity: 'success' });
}

protected showError(): void {
  this.toaster.show({ message: 'Failed to save item', severity: 'error' });
}

protected showInfo(): void {
  this.toaster.show({ message: 'New version available', severity: 'info' });
}

protected showWarning(): void {
  this.toaster.show({ message: 'Disk space running low', severity: 'warning' });
}

protected showWithAction(): void {
  this.toaster.show({
    message: 'Item deleted',
    severity: 'info',
    action: { label: 'Undo', handler: () => this.toaster.show({ message: 'Undo successful', severity: 'success' }) },
  });
}

// ── Title + Description demos ──
protected showTitleSuccess(): void {
  this.toaster.show({
    message: 'Profile updated',
    title: 'Saved',
    description: 'Your profile changes have been saved successfully.',
    severity: 'success',
    duration: 5000,
  });
}

protected showTitleError(): void {
  this.toaster.show({
    message: 'Save failed',
    title: 'Server Error',
    description: 'The server responded with 503 Service Unavailable. Please try again in a few minutes.',
    severity: 'error',
  });
}

protected showTitleWithAction(): void {
  this.toaster.show({
    message: 'Connection lost',
    title: 'Offline',
    description: 'Changes saved locally. They will sync when you reconnect.',
    severity: 'warning',
    action: { label: 'Retry now', handler: () => this.toaster.show({ message: 'Reconnecting...', severity: 'info' }) },
  });
}

// ── Custom Component (Stufe 2) demo ──
protected showCustomComponent(): void {
  this.toaster.show({
    message: 'Validation failed',
    title: '3 Errors',
    severity: 'error',
    content: SampleToastBody,
    contentInputs: { fields: ['Name is required', 'Email is invalid', 'ZIP must be 5 digits'] },
  });
}

protected showCustomNoTitle(): void {
  this.toaster.show({
    message: 'Details',
    severity: 'info',
    content: SampleToastBody,
    contentInputs: { fields: ['Build #1234 completed', 'Tests: 754 passed, 0 failed', 'Coverage: 92%'] },
  });
}

protected showDuplicates(): void {
  for (let i = 0; i < 5; i++) {
    this.toaster.show({ message: 'Batch operation complete', severity: 'success' });
  }
}

protected clearAll(): void {
  this.toaster.dismissAll();
}

// ── Declarative <cngx-toast> demos ──
protected readonly showSaved = signal(false);
protected readonly showDeleted = signal(false);

protected triggerSave(): void {
  this.showSaved.set(true);
  setTimeout(() => this.showSaved.set(false), 100);
}

protected triggerDelete(): void {
  this.showDeleted.set(true);
  setTimeout(() => this.showDeleted.set(false), 100);
}

// ── Declarative [cngxToastOn] demo ──
protected readonly saveState = createManualState<string>();

protected simulateSave(): void {
  this.saveState.set('pending');
  setTimeout(() => this.saveState.setSuccess('done'), 1500);
}

protected simulateError(): void {
  this.saveState.set('pending');
  setTimeout(() => this.saveState.setError('Network timeout'), 1500);
}`;
  protected readonly _exHtml: string = `<div style="display:flex;gap:8px">
  <button (click)="triggerSave()" class="chip">Save Item</button>
  <button (click)="triggerDelete()" class="chip">Delete Item</button>
</div>

<cngx-toast severity="success" message="Item saved" [when]="showSaved()" />
<cngx-toast severity="warning" message="Item deleted — this cannot be undone" [when]="showDeleted()" [duration]="8000" />`;
  private readonly toaster = inject(CngxToaster);

    // ── Programmatic demos ──
    protected showSuccess(): void {
      this.toaster.show({ message: 'Item saved successfully', severity: 'success' });
    }

    protected showError(): void {
      this.toaster.show({ message: 'Failed to save item', severity: 'error' });
    }

    protected showInfo(): void {
      this.toaster.show({ message: 'New version available', severity: 'info' });
    }

    protected showWarning(): void {
      this.toaster.show({ message: 'Disk space running low', severity: 'warning' });
    }

    protected showWithAction(): void {
      this.toaster.show({
        message: 'Item deleted',
        severity: 'info',
        action: { label: 'Undo', handler: () => this.toaster.show({ message: 'Undo successful', severity: 'success' }) },
      });
    }

    // ── Title + Description demos ──
    protected showTitleSuccess(): void {
      this.toaster.show({
        message: 'Profile updated',
        title: 'Saved',
        description: 'Your profile changes have been saved successfully.',
        severity: 'success',
        duration: 5000,
      });
    }

    protected showTitleError(): void {
      this.toaster.show({
        message: 'Save failed',
        title: 'Server Error',
        description: 'The server responded with 503 Service Unavailable. Please try again in a few minutes.',
        severity: 'error',
      });
    }

    protected showTitleWithAction(): void {
      this.toaster.show({
        message: 'Connection lost',
        title: 'Offline',
        description: 'Changes saved locally. They will sync when you reconnect.',
        severity: 'warning',
        action: { label: 'Retry now', handler: () => this.toaster.show({ message: 'Reconnecting...', severity: 'info' }) },
      });
    }

    // ── Custom Component (Stufe 2) demo ──
    protected showCustomComponent(): void {
      this.toaster.show({
        message: 'Validation failed',
        title: '3 Errors',
        severity: 'error',
        content: SampleToastBody,
        contentInputs: { fields: ['Name is required', 'Email is invalid', 'ZIP must be 5 digits'] },
      });
    }

    protected showCustomNoTitle(): void {
      this.toaster.show({
        message: 'Details',
        severity: 'info',
        content: SampleToastBody,
        contentInputs: { fields: ['Build #1234 completed', 'Tests: 754 passed, 0 failed', 'Coverage: 92%'] },
      });
    }

    protected showDuplicates(): void {
      for (let i = 0; i < 5; i++) {
        this.toaster.show({ message: 'Batch operation complete', severity: 'success' });
      }
    }

    protected clearAll(): void {
      this.toaster.dismissAll();
    }

    // ── Declarative <cngx-toast> demos ──
    protected readonly showSaved = signal(false);
    protected readonly showDeleted = signal(false);

    protected triggerSave(): void {
      this.showSaved.set(true);
      setTimeout(() => this.showSaved.set(false), 100);
    }

    protected triggerDelete(): void {
      this.showDeleted.set(true);
      setTimeout(() => this.showDeleted.set(false), 100);
    }

    // ── Declarative [cngxToastOn] demo ──
    protected readonly saveState = createManualState<string>();

    protected simulateSave(): void {
      this.saveState.set('pending');
      setTimeout(() => this.saveState.setSuccess('done'), 1500);
    }

    protected simulateError(): void {
      this.saveState.set('pending');
      setTimeout(() => this.saveState.setError('Network timeout'), 1500);
    }
}
