// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/forms/filter-expression-row-demo/filter-expression-row-demo.story.ts

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ExampleCardComponent } from '../../../shared/example-card.component';
import { DocShellComponent } from '../../../shared/doc-shell.component';
import { JsonPipe } from '@angular/common';
import { computed, effect, untracked } from '@angular/core';
import { createManualState } from '@cngx/common/data';
import { CngxAsyncContainer, CngxAsyncSkeletonTpl, CngxAsyncContentTpl, CngxAsyncEmptyTpl, CngxAsyncErrorTpl } from '@cngx/ui/feedback';
import { CngxFilterRow, createFilterGroup, toFilterPredicate, type FilterExpression } from '@cngx/forms/filter-builder';
import { FILTER_BUILDER_FIELDS, FILTER_BUILDER_PEOPLE, type FilterBuilderPerson } from '../../../fixtures';

@Component({
  selector: 'app-filter-expression-row-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxFilterRow,
    CngxAsyncContainer,
    CngxAsyncSkeletonTpl,
    CngxAsyncContentTpl,
    CngxAsyncEmptyTpl,
    CngxAsyncErrorTpl,
    JsonPipe,
  ],
  template: `
    <app-doc-shell title="Filter Row — standalone"
      description="One <cngx-filter-row> on top of a CngxAsyncContainer-wrapped roster. The user picks a field, an operator, and a value; every mutation re-fetches with the same skeleton UX as the initial load."
      overview="<p><code>CngxFilterRow</code> is the dedicated single-row surface for ad-hoc filter contexts: a side panel, a top-of-table quick filter, or any place where a full <code>&lt;cngx-filter-builder&gt;</code> tree is overkill but the user still needs to pick the field. One row owns one <code>FilterExpression | null</code>.</p><p>The roster lives in <code>dataState.data()</code> and renders <em>only</em> from inside <code>cngxAsyncContent</code>. The skeleton, empty, and error templates own the other branches. A request token dedupes superseded fetches when the user types fast.</p><p><strong>Note:</strong> per-column header filters with one fixed field per column are a different UX (clear vs. remove semantics, no field picker, predicate writes directly into a parent <code>CngxFilter</code> aggregator). That is a separate artifact tracked for the table sprint — do not lift this row into a column header.</p>"
      [apiComponents]="['CngxFilterRow', 'CngxAsyncContainer']">
      <app-example-card title="Ad-hoc filter on top of an async-wrapped roster"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0"
        [sourceCss]="_srcCss0">
        
  <div class="demo-actions">
    <button type="button" (click)="refetch()">Refetch</button>
    <button type="button" (click)="failNextFetch()">Fail next</button>
  </div>

  <div class="demo-filter-bar">
    <cngx-filter-row [fields]="fields" [(value)]="filter" />
  </div>

  <cngx-async-container [state]="dataState" ariaLabel="Roster">
    <ng-template cngxAsyncSkeleton>
      <div class="demo-skeleton">
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
      </div>
    </ng-template>

    <ng-template cngxAsyncEmpty>
      <p class="demo-empty">No rows match the current filter.</p>
    </ng-template>

    <ng-template cngxAsyncContent let-rows>
      <table class="demo-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Age</th>
            <th>Active</th>
          </tr>
        </thead>
        <tbody>
          @for (p of rows; track p.name) {
            <tr>
              <td>{{ p.name }}</td>
              <td>{{ p.role }}</td>
              <td>{{ p.age }}</td>
              <td>{{ p.active ? 'yes' : 'no' }}</td>
            </tr>
          }
        </tbody>
      </table>
    </ng-template>

    <ng-template cngxAsyncError let-err>
      <div role="alert" class="demo-error">
        <strong>Roster load failed:</strong> {{ (err)?.message ?? 'unknown error' }}
      </div>
    </ng-template>
  </cngx-async-container>

  <div class="status-row">
    <span class="status-badge">Status: {{ dataState.status() }}</span>
    <span class="status-badge">Showing: {{ (dataState.data() ?? []).length }}</span>
  </div>
      
      </app-example-card>
      <app-example-card title="Raw [(value)] contract"
        [subtitle]="_s1"
        [sourceHtml]="_srcHtml1"
        [sourceTs]="_srcTs1">
        
  <cngx-filter-row [fields]="[nameField]" [(value)]="filter" />
  <pre class="code-block">{{ filter() | json }}</pre>
      
      </app-example-card>
    </app-doc-shell>
  `,
})
export class FilterExpressionRowDemoComponent {
  protected readonly _s0 = 'Pick a field, operator, and value in the row above the table. The roster re-fetches on every mutation; the table renders only inside <code>cngxAsyncContent</code>.';
  protected readonly _s1 = 'The same row, no async wrap. Shows the bare two-way binding: the row reads / writes <code>FilterExpression | null</code> directly. Remove writes <code>null</code> back.';
  protected readonly _srcHtml0 = `<div class="demo-actions">
    <button type="button" (click)="refetch()">Refetch</button>
    <button type="button" (click)="failNextFetch()">Fail next</button>
  </div>

  <div class="demo-filter-bar">
    <cngx-filter-row [fields]="fields" [(value)]="filter" />
  </div>

  <cngx-async-container [state]="dataState" ariaLabel="Roster">
    <ng-template cngxAsyncSkeleton>
      <div class="demo-skeleton">
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
        <div class="demo-skeleton-row"></div>
      </div>
    </ng-template>

    <ng-template cngxAsyncEmpty>
      <p class="demo-empty">No rows match the current filter.</p>
    </ng-template>

    <ng-template cngxAsyncContent let-rows>
      <table class="demo-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Age</th>
            <th>Active</th>
          </tr>
        </thead>
        <tbody>
          @for (p of rows; track p.name) {
            <tr>
              <td>{{ p.name }}</td>
              <td>{{ p.role }}</td>
              <td>{{ p.age }}</td>
              <td>{{ p.active ? 'yes' : 'no' }}</td>
            </tr>
          }
        </tbody>
      </table>
    </ng-template>

    <ng-template cngxAsyncError let-err>
      <div role="alert" class="demo-error">
        <strong>Roster load failed:</strong> {{ (err)?.message ?? 'unknown error' }}
      </div>
    </ng-template>
  </cngx-async-container>

  <div class="status-row">
    <span class="status-badge">Status: {{ dataState.status() }}</span>
    <span class="status-badge">Showing: {{ (dataState.data() ?? []).length }}</span>
  </div>`;
  protected readonly _srcTs0 = `import { computed, effect, untracked } from '@angular/core';
import { createManualState } from '@cngx/common/data';
import { CngxAsyncContainer, CngxAsyncSkeletonTpl, CngxAsyncContentTpl, CngxAsyncEmptyTpl, CngxAsyncErrorTpl } from '@cngx/ui/feedback';
import { CngxFilterRow, createFilterGroup, toFilterPredicate, type FilterExpression } from '@cngx/forms/filter-builder';
import { FILTER_BUILDER_FIELDS, FILTER_BUILDER_PEOPLE, type FilterBuilderPerson } from '../../../fixtures';


  protected readonly fields = FILTER_BUILDER_FIELDS;
  protected readonly nameField = FILTER_BUILDER_FIELDS.find((f) => f.key === 'name')!;
  protected readonly filter = signal<FilterExpression | null>(null);
  protected readonly dataState = createManualState<readonly FilterBuilderPerson[]>();

  protected readonly predicate = computed<((item: FilterBuilderPerson) => boolean) | null>(() => {
    const f = this.filter();
    if (!f) {
      return null;
    }
    return toFilterPredicate(createFilterGroup('and', [f]), this.fields);
  });

  private fetchToken = 0;
  private failNext = false;

  constructor() {
    effect(() => {
      const fn = this.predicate();
      untracked(() => this.fetchPeople(fn));
    });
  }

  private fetchPeople(predicate: ((item: FilterBuilderPerson) => boolean) | null): void {
    const myToken = ++this.fetchToken;
    // reset() flips isFirstLoad back to true so resolveAsyncView returns
    // 'skeleton', not the thin refresh-bar. Same UX every fetch.
    this.dataState.reset();
    this.dataState.set('loading');
    setTimeout(() => {
      if (myToken !== this.fetchToken) {
        return;
      }
      if (this.failNext) {
        this.failNext = false;
        this.dataState.setError(new Error('Roster fetch failed'));
        return;
      }
      const items = predicate ? FILTER_BUILDER_PEOPLE.filter(predicate) : FILTER_BUILDER_PEOPLE;
      this.dataState.setSuccess(items);
    }, 500);
  }

  protected refetch(): void {
    this.fetchPeople(this.predicate());
  }

  protected failNextFetch(): void {
    this.failNext = true;
    this.refetch();
  }`;
  protected readonly _srcCss0 = `.demo-actions { display: flex; gap: 8px; margin: 12px 0; }
.demo-actions button { padding: 4px 10px; cursor: pointer; }
.demo-filter-bar {
  padding: 8px 12px;
  background: var(--cngx-surface-variant, #f5f5f5);
  border: 1px solid var(--cngx-border, #ddd);
  border-bottom: none;
}
.demo-table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
.demo-table th, .demo-table td { padding: 6px 10px; border-bottom: 1px solid var(--cngx-border, #ddd); text-align: left; vertical-align: top; }
.demo-table th { background: var(--cngx-surface-variant, #f5f5f5); font-weight: 600; }
.demo-skeleton { display: flex; flex-direction: column; gap: 8px; padding: 8px 0; }
.demo-skeleton-row {
  height: 24px;
  background: var(--cngx-skeleton-bg, #e0e0e0);
  border-radius: 4px;
  opacity: 0.6;
}
.demo-empty { color: var(--cngx-fg-muted, #666); font-style: italic; padding: 12px 0; }
.demo-error {
  color: var(--cngx-error, #b00020);
  padding: 8px 12px;
  border: 1px solid currentColor;
  border-radius: 4px;
  background: rgba(176, 0, 32, 0.05);
}`;
  protected readonly _srcHtml1 = `<cngx-filter-row [fields]="[nameField]" [(value)]="filter" />
  <pre class="code-block">{{ filter() | json }}</pre>`;
  protected readonly _srcTs1 = `import { computed, effect, untracked } from '@angular/core';
import { createManualState } from '@cngx/common/data';
import { CngxAsyncContainer, CngxAsyncSkeletonTpl, CngxAsyncContentTpl, CngxAsyncEmptyTpl, CngxAsyncErrorTpl } from '@cngx/ui/feedback';
import { CngxFilterRow, createFilterGroup, toFilterPredicate, type FilterExpression } from '@cngx/forms/filter-builder';
import { FILTER_BUILDER_FIELDS, FILTER_BUILDER_PEOPLE, type FilterBuilderPerson } from '../../../fixtures';


  protected readonly fields = FILTER_BUILDER_FIELDS;
  protected readonly nameField = FILTER_BUILDER_FIELDS.find((f) => f.key === 'name')!;
  protected readonly filter = signal<FilterExpression | null>(null);
  protected readonly dataState = createManualState<readonly FilterBuilderPerson[]>();

  protected readonly predicate = computed<((item: FilterBuilderPerson) => boolean) | null>(() => {
    const f = this.filter();
    if (!f) {
      return null;
    }
    return toFilterPredicate(createFilterGroup('and', [f]), this.fields);
  });

  private fetchToken = 0;
  private failNext = false;

  constructor() {
    effect(() => {
      const fn = this.predicate();
      untracked(() => this.fetchPeople(fn));
    });
  }

  private fetchPeople(predicate: ((item: FilterBuilderPerson) => boolean) | null): void {
    const myToken = ++this.fetchToken;
    // reset() flips isFirstLoad back to true so resolveAsyncView returns
    // 'skeleton', not the thin refresh-bar. Same UX every fetch.
    this.dataState.reset();
    this.dataState.set('loading');
    setTimeout(() => {
      if (myToken !== this.fetchToken) {
        return;
      }
      if (this.failNext) {
        this.failNext = false;
        this.dataState.setError(new Error('Roster fetch failed'));
        return;
      }
      const items = predicate ? FILTER_BUILDER_PEOPLE.filter(predicate) : FILTER_BUILDER_PEOPLE;
      this.dataState.setSuccess(items);
    }, 500);
  }

  protected refetch(): void {
    this.fetchPeople(this.predicate());
  }

  protected failNextFetch(): void {
    this.failNext = true;
    this.refetch();
  }`;

  protected readonly fields = FILTER_BUILDER_FIELDS;
  protected readonly nameField = FILTER_BUILDER_FIELDS.find((f) => f.key === 'name')!;
  protected readonly filter = signal<FilterExpression | null>(null);
  protected readonly dataState = createManualState<readonly FilterBuilderPerson[]>();

  protected readonly predicate = computed<((item: FilterBuilderPerson) => boolean) | null>(() => {
    const f = this.filter();
    if (!f) {
      return null;
    }
    return toFilterPredicate(createFilterGroup('and', [f]), this.fields);
  });

  private fetchToken = 0;
  private failNext = false;

  constructor() {
    effect(() => {
      const fn = this.predicate();
      untracked(() => this.fetchPeople(fn));
    });
  }

  private fetchPeople(predicate: ((item: FilterBuilderPerson) => boolean) | null): void {
    const myToken = ++this.fetchToken;
    // reset() flips isFirstLoad back to true so resolveAsyncView returns
    // 'skeleton', not the thin refresh-bar. Same UX every fetch.
    this.dataState.reset();
    this.dataState.set('loading');
    setTimeout(() => {
      if (myToken !== this.fetchToken) {
        return;
      }
      if (this.failNext) {
        this.failNext = false;
        this.dataState.setError(new Error('Roster fetch failed'));
        return;
      }
      const items = predicate ? FILTER_BUILDER_PEOPLE.filter(predicate) : FILTER_BUILDER_PEOPLE;
      this.dataState.setSuccess(items);
    }, 500);
  }

  protected refetch(): void {
    this.fetchPeople(this.predicate());
  }

  protected failNextFetch(): void {
    this.failNext = true;
    this.refetch();
  }
  
}
