// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/data/data-source-demo/data-source-demo.story.ts#section[0] "CngxDataSource — Signal → Observable Bridge"

import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { injectDataSource } from '@cngx/common';
import { PEOPLE, type Person } from '../../fixtures';

@Component({
  selector: 'app-data-source-signal-observable-bridge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="table-wrap">
        <table class="demo-table">
          <thead>
            <tr><th>Name</th><th>Role</th><th>Location</th></tr>
          </thead>
          <tbody>
            @for (row of rows(); track row.name) {
              <tr><td>{{ row.name }}</td><td>{{ row.role }}</td><td>{{ row.location }}</td></tr>
            }
          </tbody>
        </table>
      </div>
      <div class="button-row">
        <button type="button" (click)="shuffle()">Shuffle</button>
        <button type="button" (click)="reset()">Reset</button>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class DataSourceSignalObservableBridge {
  protected readonly _exTitle: string = 'DataSource';
  protected readonly _exDescription: string = '';
  protected readonly _exSectionTitle: string = 'CngxDataSource — Signal → Observable Bridge';
  protected readonly _exSubtitle: string = '<code>injectDataSource(signal)</code> is a thin CDK <code>DataSource</code> wrapper. Every time the signal changes, <code>connect()</code> emits a new value. Use <code>toSignal(ds.connect())</code> to drive a template directly. Zero logic — consumer wires up sort/filter/search via a <code>computed()</code> passed as the signal.';
  protected readonly _exTs: string = `import { toSignal } from '@angular/core/rxjs-interop';
import { injectDataSource } from '@cngx/common';
import { PEOPLE, type Person } from '../../fixtures';

private readonly items = signal(PEOPLE);
private readonly ds = injectDataSource(this.items);

protected readonly rows = toSignal(this.ds.connect(), { initialValue: [] as Person[] });

// Paginated variant — page state owned by component signals
protected readonly pageIndex = signal(0);
protected readonly pageSize  = signal(3);

protected readonly paginated = computed((): Person[] =>
  PEOPLE.slice(
    this.pageIndex() * this.pageSize(),
    (this.pageIndex() + 1) * this.pageSize(),
  ),
);

protected readonly totalPeople = PEOPLE.length;

protected shuffle(): void {
  this.items.update((list) => [...list].sort(() => Math.random() - 0.5));
}

protected reset(): void {
  this.items.set(PEOPLE);
}

protected setPage(i: number): void {
  const max = Math.max(0, Math.ceil(PEOPLE.length / this.pageSize()) - 1);
  this.pageIndex.set(Math.max(0, Math.min(i, max)));
}

protected setPageSize(s: number): void {
  this.pageSize.set(s);
  this.pageIndex.set(0);
}`;
  protected readonly _exHtml: string = `<div class="table-wrap">
  <table class="demo-table">
    <thead>
      <tr><th>Name</th><th>Role</th><th>Location</th></tr>
    </thead>
    <tbody>
      @for (row of rows(); track row.name) {
        <tr><td>{{ row.name }}</td><td>{{ row.role }}</td><td>{{ row.location }}</td></tr>
      }
    </tbody>
  </table>
</div>
<div class="button-row">
  <button type="button" (click)="shuffle()">Shuffle</button>
  <button type="button" (click)="reset()">Reset</button>
</div>`;
  private readonly items = signal(PEOPLE);
    private readonly ds = injectDataSource(this.items);

    protected readonly rows = toSignal(this.ds.connect(), { initialValue: [] as Person[] });

    // Paginated variant — page state owned by component signals
    protected readonly pageIndex = signal(0);
    protected readonly pageSize  = signal(3);

    protected readonly paginated = computed((): Person[] =>
      PEOPLE.slice(
        this.pageIndex() * this.pageSize(),
        (this.pageIndex() + 1) * this.pageSize(),
      ),
    );

    protected readonly totalPeople = PEOPLE.length;

    protected shuffle(): void {
      this.items.update((list) => [...list].sort(() => Math.random() - 0.5));
    }

    protected reset(): void {
      this.items.set(PEOPLE);
    }

    protected setPage(i: number): void {
      const max = Math.max(0, Math.ceil(PEOPLE.length / this.pageSize()) - 1);
      this.pageIndex.set(Math.max(0, Math.min(i, max)));
    }

    protected setPageSize(s: number): void {
      this.pageSize.set(s);
      this.pageIndex.set(0);
    }
}
