// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/data/recycler-demo/recycler-demo.story.ts#section[3] "Infinite Scroll + Recycler"

import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { injectRecycler } from '@cngx/common/data';
import { CngxInfiniteScroll } from '@cngx/common/layout';

@Component({
  selector: 'app-recycler-infinite-scroll-recycler',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxInfiniteScroll],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="status-row" style="margin-bottom:8px">
        <span class="status-badge">Loaded: {{ infiniteItems().length }}</span>
        <span class="status-badge">
          Visible: {{ infRecycler.firstVisible() + 1 }}&ndash;{{ infRecycler.lastVisible() + 1 }}
        </span>
        <span class="status-badge">DOM: {{ infRecycler.end() - infRecycler.start() }}</span>
        @if (infiniteLoading()) {
          <span class="status-badge">Loading...</span>
        }
      </div>
      <div class="inf-scroll"
           style="height:300px;overflow-y:auto;border:1px solid var(--cngx-color-border,#e0e0e0);border-radius:8px">
        <div [style.paddingTop.px]="infRecycler.offsetBefore()"
             [style.paddingBottom.px]="infRecycler.offsetAfter()">
          @for (item of infVisible(); track item) {
            <div style="height:48px;display:flex;align-items:center;padding:0 16px;border-bottom:1px solid var(--cngx-color-border,#e0e0e0)">
              {{ item }}
            </div>
          }
        </div>
        <div cngxInfiniteScroll
             [enabled]="infiniteHasMore()"
             [loading]="infiniteLoading()"
             [root]="'.inf-scroll'"
             (loadMore)="handleLoadMore()"
             style="padding:8px;text-align:center;color:var(--cngx-text-muted,#999)">
          @if (infiniteLoading()) {
            Loading more...
          } @else if (!infiniteHasMore()) {
            All 500 items loaded.
          }
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class RecyclerInfiniteScrollRecycler {
  protected readonly _exTitle: string = 'Recycler — DOM Recycling';
  protected readonly _exDescription: string = 'Signal-based virtualizer for long lists. Items outside the viewport are removed from the DOM. Consumer renders with @for and two spacer containers.';
  protected readonly _exSectionTitle: string = 'Infinite Scroll + Recycler';
  protected readonly _exSubtitle: string = 'Combine <code>CngxInfiniteScroll</code> with the recycler for large HTTP-loaded lists. The sentinel sits outside the spacer container. Items append to the array — scrolling back up never re-fetches because already-loaded items stay in memory.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exTs: string = `import { injectRecycler } from '@cngx/common/data';
import { CngxInfiniteScroll } from '@cngx/common/layout';

protected readonly allItems = signal(
  Array.from({ length: 5000 }, (_, i) => ({
    id: i,
    name: 'Item ' + (i + 1),
    description: 'Description for item ' + (i + 1),
  })),
);

protected readonly recycler = injectRecycler({
  scrollElement: '.recycler-scroll',
  totalCount: () => this.allItems().length,
  estimateSize: 48,
  overscan: 10,
});

protected readonly visibleItems = this.recycler.sliced(this.allItems);

protected readonly targetIndex = signal(0);

protected handleScrollTo(): void {
  this.recycler.scrollToIndex(this.targetIndex());
}



protected readonly infiniteItems = signal<string[]>([]);
protected readonly infiniteLoading = signal(false);
protected readonly infiniteHasMore = computed(() => this.infiniteItems().length < 500);
private infinitePage = 0;

protected readonly infRecycler = injectRecycler({
  scrollElement: '.inf-scroll',
  totalCount: () => this.infiniteItems().length,
  estimateSize: 48,
  overscan: 5,
});

protected readonly infVisible = this.infRecycler.sliced(this.infiniteItems);

protected handleLoadMore(): void {
  if (this.infiniteLoading() || !this.infiniteHasMore()) { return; }
  this.infiniteLoading.set(true);
  setTimeout(() => {
    const start = this.infinitePage * 50;
    const page = Array.from({ length: 50 }, (_, i) => 'Item ' + (start + i + 1));
    this.infiniteItems.update(prev => [...prev, ...page]);
    this.infiniteLoading.set(false);
    this.infinitePage++;
  }, 300);
}`;
  protected readonly _exHtml: string = `<div class="status-row" style="margin-bottom:8px">
  <span class="status-badge">Loaded: {{ infiniteItems().length }}</span>
  <span class="status-badge">
    Visible: {{ infRecycler.firstVisible() + 1 }}&ndash;{{ infRecycler.lastVisible() + 1 }}
  </span>
  <span class="status-badge">DOM: {{ infRecycler.end() - infRecycler.start() }}</span>
  @if (infiniteLoading()) {
    <span class="status-badge">Loading...</span>
  }
</div>
<div class="inf-scroll"
     style="height:300px;overflow-y:auto;border:1px solid var(--cngx-color-border,#e0e0e0);border-radius:8px">
  <div [style.paddingTop.px]="infRecycler.offsetBefore()"
       [style.paddingBottom.px]="infRecycler.offsetAfter()">
    @for (item of infVisible(); track item) {
      <div style="height:48px;display:flex;align-items:center;padding:0 16px;border-bottom:1px solid var(--cngx-color-border,#e0e0e0)">
        {{ item }}
      </div>
    }
  </div>
  <div cngxInfiniteScroll
       [enabled]="infiniteHasMore()"
       [loading]="infiniteLoading()"
       [root]="'.inf-scroll'"
       (loadMore)="handleLoadMore()"
       style="padding:8px;text-align:center;color:var(--cngx-text-muted,#999)">
    @if (infiniteLoading()) {
      Loading more...
    } @else if (!infiniteHasMore()) {
      All 500 items loaded.
    }
  </div>
</div>`;
  protected readonly allItems = signal(
      Array.from({ length: 5000 }, (_, i) => ({
        id: i,
        name: 'Item ' + (i + 1),
        description: 'Description for item ' + (i + 1),
      })),
    );

    protected readonly recycler = injectRecycler({
      scrollElement: '.recycler-scroll',
      totalCount: () => this.allItems().length,
      estimateSize: 48,
      overscan: 10,
    });

    protected readonly visibleItems = this.recycler.sliced(this.allItems);

    protected readonly targetIndex = signal(0);

    protected handleScrollTo(): void {
      this.recycler.scrollToIndex(this.targetIndex());
    }

  protected readonly infiniteItems = signal<string[]>([]);
    protected readonly infiniteLoading = signal(false);
    protected readonly infiniteHasMore = computed(() => this.infiniteItems().length < 500);
    private infinitePage = 0;

    protected readonly infRecycler = injectRecycler({
      scrollElement: '.inf-scroll',
      totalCount: () => this.infiniteItems().length,
      estimateSize: 48,
      overscan: 5,
    });

    protected readonly infVisible = this.infRecycler.sliced(this.infiniteItems);

    protected handleLoadMore(): void {
      if (this.infiniteLoading() || !this.infiniteHasMore()) { return; }
      this.infiniteLoading.set(true);
      setTimeout(() => {
        const start = this.infinitePage * 50;
        const page = Array.from({ length: 50 }, (_, i) => 'Item ' + (start + i + 1));
        this.infiniteItems.update(prev => [...prev, ...page]);
        this.infiniteLoading.set(false);
        this.infinitePage++;
      }, 300);
    }
}
