// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: examples/stories/ui/tabs/tab-slot-overrides-demo/tab-slot-overrides-demo.story.ts#section[0] "Custom error badge via <code>*cngxTabErrorBadge</code>"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxTab, CngxTabContent, CngxTabErrorBadge, type CngxTabsCommitAction } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';
import { CngxErrorAggregator, CngxErrorSource } from '@cngx/common/interactive';

@Component({
  selector: 'app-tab-slot-overrides-custom-error-badge-via-code-cngxtaberrorbadge-code',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxTabGroup, CngxTab, CngxTabContent, CngxTabErrorBadge, CngxErrorAggregator, CngxErrorSource],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-tab-group [(activeIndex)]="active" aria-label="Slot-overrides — error badge">
        <ng-template cngxTabErrorBadge let-tab="tab">
          <span class="chip" style="background:#dc2626;color:#fff;font-size:0.7em;padding:0 6px">
            {{ tab.errorAggregator()?.errorCount() }}
          </span>
        </ng-template>
        <fieldset cngxErrorAggregator #profileAgg="cngxErrorAggregator" style="display:contents">
          <input cngxErrorSource="profile-name" [when]="profileInvalid()" hidden />
          <div cngxTab [label]="'Profile'" [errorAggregator]="profileAgg">
            <ng-template cngxTabContent>
              <p>Toggle "profile invalid" below — the badge counter pill appears with the aggregator's error count.</p>
            </ng-template>
          </div>
        </fieldset>
        <div cngxTab [label]="'Account'">
          <ng-template cngxTabContent>
            <p>No aggregator bound — no badge rendered.</p>
          </ng-template>
        </div>
      </cngx-tab-group>
      <div class="event-grid" style="margin-top:var(--demo-grid-gap, 12px);gap:8px">
        <div class="event-row" style="gap:8px">
          <label>
            <input type="checkbox"
                   [checked]="profileInvalid()"
                   (change)="profileInvalid.set($any($event.target).checked)" />
            profile invalid
          </label>
        </div>
        <div class="event-row"><span class="event-label">Active tab</span><span class="event-value">{{ active() }}</span></div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class TabSlotOverridesCustomErrorBadgeViaCodeCngxtaberrorbadgeCode {
  protected readonly _exTitle: string = 'Tabs — slot overrides';
  protected readonly _exDescription: string = 'Override every visual region inside <code>&lt;cngx-tab-group&gt;</code> via the three new slot directives — <code>*cngxTabErrorBadge</code>, <code>*cngxTabRejectionIcon</code>, <code>*cngxTabBusySpinner</code>. Each slot ships a typed context object — destructure via <code>let-tab="tab"</code> / <code>let-failedIndex="failedIndex"</code> / <code>let-originLabel="originLabel"</code> / <code>let-intendedIndex="intendedIndex"</code>. Sibling-shape parity with the stepper Phase-3 slots, so consumer-authored templates port across families with zero re-authoring. The library renders sensible defaults; the slots are purely additive.';
  protected readonly _exSectionTitle: string = 'Custom error badge via <code>*cngxTabErrorBadge</code>';
  protected readonly _exSubtitle: string = 'Replace the default <code>!</code> glyph with a counter pill driven by the tab\'s aggregator. Context is <code>{ tab }</code>; the badge only renders when <code>tab.errorAggregator()?.shouldShow()</code> is truthy, so the slot is purely additive — no visibility plumbing in consumer markup. Toggle the "profile invalid" checkbox to flip the badge.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'organism' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'composition' }, { dim: 'focus', value: 'visual-variants' }];
  protected readonly _exTs: string = `import { CngxTab, CngxTabContent, CngxTabErrorBadge, type CngxTabsCommitAction } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';
import { CngxErrorAggregator, CngxErrorSource } from '@cngx/common/interactive';

protected readonly active = signal(0);
protected readonly profileInvalid = signal(true);`;
  protected readonly _exHtml: string = `<cngx-tab-group [(activeIndex)]="active" aria-label="Slot-overrides — error badge">
  <ng-template cngxTabErrorBadge let-tab="tab">
    <span class="chip" style="background:#dc2626;color:#fff;font-size:0.7em;padding:0 6px">
      {{ tab.errorAggregator()?.errorCount() }}
    </span>
  </ng-template>
  <fieldset cngxErrorAggregator #profileAgg="cngxErrorAggregator" style="display:contents">
    <input cngxErrorSource="profile-name" [when]="profileInvalid()" hidden />
    <div cngxTab [label]="'Profile'" [errorAggregator]="profileAgg">
      <ng-template cngxTabContent>
        <p>Toggle "profile invalid" below — the badge counter pill appears with the aggregator's error count.</p>
      </ng-template>
    </div>
  </fieldset>
  <div cngxTab [label]="'Account'">
    <ng-template cngxTabContent>
      <p>No aggregator bound — no badge rendered.</p>
    </ng-template>
  </div>
</cngx-tab-group>`;
  protected readonly active = signal(0);
    protected readonly profileInvalid = signal(true);
    protected readonly busyAttempts = signal(0);
    protected readonly slowAttempts = signal(0);

    // Reject the first commit attempt onto tab 2 ('Security'); succeed
    // on retry. Drives the *cngxTabRejectionIcon slot — presenter sets
    // lastFailedIndex on the rejection arm and clears it on the next success.
    protected readonly commitAction: CngxTabsCommitAction = (_from, to) => {
      if (to === 2 && this.busyAttempts() === 0) {
        this.busyAttempts.update((n) => n + 1);
        return Promise.reject(new Error('Security check failed — retry'));
      }
      return Promise.resolve(true);
    };

    // Slow commit so the busy-spinner slot stays visible long enough to
    // observe. Resolves after 800ms — drives the *cngxTabBusySpinner slot.
    protected readonly slowCommit: CngxTabsCommitAction = () => {
      this.slowAttempts.update((n) => n + 1);
      return new Promise((resolve) => setTimeout(() => resolve(true), 800));
    };
}
