// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/ui/tabs/tab-slot-overrides-demo/tab-slot-overrides-demo.story.ts#section[2] "Custom busy-spinner via <code>*cngxTabBusySpinner</code>"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxTab, CngxTabBusySpinner, CngxTabContent, type CngxTabsCommitAction } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';

@Component({
  selector: 'app-tab-slot-overrides-custom-busy-spinner-via-code-cngxtabbusyspinner-code',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxTabGroup, CngxTab, CngxTabContent, CngxTabBusySpinner],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-tab-group
        [(activeIndex)]="active"
        [commitAction]="slowCommit"
        commitMode="pessimistic"
        aria-label="Slot-overrides — busy spinner"
      >
        <ng-template cngxTabBusySpinner let-intendedIndex="intendedIndex">
          <span aria-hidden="true" class="chip" style="padding:0 6px;font-size:0.7em;background:#1d4ed8;color:#fff">
            …syncing #{{ intendedIndex }}
          </span>
        </ng-template>
        <div cngxTab [label]="'Form'">
          <ng-template cngxTabContent>
            <p>Tab 1. Click "Review" to advance — the commit takes ~800ms in pessimistic mode.</p>
          </ng-template>
        </div>
        <div cngxTab [label]="'Review'">
          <ng-template cngxTabContent>
            <p>Tab 2. Defaults restored after commit resolves.</p>
          </ng-template>
        </div>
      </cngx-tab-group>
      <div class="event-grid" style="margin-top:var(--demo-grid-gap, 12px)">
        <div class="event-row"><span class="event-label">Slow commit attempts</span><span class="event-value">{{ slowAttempts() }}</span></div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class TabSlotOverridesCustomBusySpinnerViaCodeCngxtabbusyspinnerCode {
  protected readonly _exTitle: string = 'Tabs — slot overrides';
  protected readonly _exDescription: string = 'Override every visual region inside <code>&lt;cngx-tab-group&gt;</code> via the three new slot directives — <code>*cngxTabErrorBadge</code>, <code>*cngxTabRejectionIcon</code>, <code>*cngxTabBusySpinner</code>. Each slot ships a typed context object — destructure via <code>let-tab="tab"</code> / <code>let-failedIndex="failedIndex"</code> / <code>let-originLabel="originLabel"</code> / <code>let-intendedIndex="intendedIndex"</code>. Sibling-shape parity with the stepper Phase-3 slots, so consumer-authored templates port across families with zero re-authoring. The library renders sensible defaults; the slots are purely additive.';
  protected readonly _exSectionTitle: string = 'Custom busy-spinner via <code>*cngxTabBusySpinner</code>';
  protected readonly _exSubtitle: string = 'Replace the default pulse-animation span with branded markup while a commit is in flight. Slot context is <code>{ tab, intendedIndex }</code>; the slot only fires when the tab matches <code>presenter.intendedIndex()</code> with <code>commitState.status() === \'pending\'</code>. Click "Review" to trigger an 800ms pessimistic commit — the spinner slot replaces the default chrome on the target tab.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exTs: string = `import { CngxTab, CngxTabBusySpinner, CngxTabContent, type CngxTabsCommitAction } from '@cngx/common/tabs';
import { CngxTabGroup } from '@cngx/ui/tabs';

protected readonly active = signal(0);
protected readonly profileInvalid = signal(true);
protected readonly busyAttempts = signal(0);
protected readonly slowAttempts = signal(0);

// Reject the first commit attempt onto tab 2 ('Security'); succeed
// on retry. Drives the *cngxTabRejectionIcon slot — presenter sets
// lastFailedIndex on the rejection arm and clears it on the next success.
protected readonly commitAction: CngxTabsCommitAction = (_from, to) => {
  if (to === 2 && this.busyAttempts() === 0) {
    this.busyAttempts.update((n) => n + 1);
    return Promise.reject(new Error('Security check failed — retry'));
  }
  return Promise.resolve(true);
};

// Slow commit so the busy-spinner slot stays visible long enough to
// observe. Resolves after 800ms — drives the *cngxTabBusySpinner slot.
protected readonly slowCommit: CngxTabsCommitAction = () => {
  this.slowAttempts.update((n) => n + 1);
  return new Promise((resolve) => setTimeout(() => resolve(true), 800));
};`;
  protected readonly _exHtml: string = `<cngx-tab-group
  [(activeIndex)]="active"
  [commitAction]="slowCommit"
  commitMode="pessimistic"
  aria-label="Slot-overrides — busy spinner"
>
  <ng-template cngxTabBusySpinner let-intendedIndex="intendedIndex">
    <span aria-hidden="true" class="chip" style="padding:0 6px;font-size:0.7em;background:#1d4ed8;color:#fff">
      …syncing #{{ intendedIndex }}
    </span>
  </ng-template>
  <div cngxTab [label]="'Form'">
    <ng-template cngxTabContent>
      <p>Tab 1. Click "Review" to advance — the commit takes ~800ms in pessimistic mode.</p>
    </ng-template>
  </div>
  <div cngxTab [label]="'Review'">
    <ng-template cngxTabContent>
      <p>Tab 2. Defaults restored after commit resolves.</p>
    </ng-template>
  </div>
</cngx-tab-group>`;
  protected readonly active = signal(0);
    protected readonly profileInvalid = signal(true);
    protected readonly busyAttempts = signal(0);
    protected readonly slowAttempts = signal(0);

    // Reject the first commit attempt onto tab 2 ('Security'); succeed
    // on retry. Drives the *cngxTabRejectionIcon slot — presenter sets
    // lastFailedIndex on the rejection arm and clears it on the next success.
    protected readonly commitAction: CngxTabsCommitAction = (_from, to) => {
      if (to === 2 && this.busyAttempts() === 0) {
        this.busyAttempts.update((n) => n + 1);
        return Promise.reject(new Error('Security check failed — retry'));
      }
      return Promise.resolve(true);
    };

    // Slow commit so the busy-spinner slot stays visible long enough to
    // observe. Resolves after 800ms — drives the *cngxTabBusySpinner slot.
    protected readonly slowCommit: CngxTabsCommitAction = () => {
      this.slowAttempts.update((n) => n + 1);
      return new Promise((resolve) => setTimeout(() => resolve(true), 800));
    };
}
