// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/action-multi-select-demo/action-multi-select-demo.story.ts#section[4] "closeOnCreate=true — confirm-to-create UX"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxActionMultiSelect, type CngxActionMultiSelectChange, type CngxSelectCreateAction, type CngxSelectOptionDef } from '@cngx/forms/select';
import { CngxSelectAction } from '@cngx/forms/select';
import { delay, of, throwError } from 'rxjs';

@Component({
  selector: 'app-action-multi-select-closeoncreate-true-confirm-to-create-ux',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxActionMultiSelect, CngxSelectAction],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-action-multi-select
        [label]="'Invitees'"
        [options]="tags"
        [compareWith]="basicCompare"
        [quickCreateAction]="closeCreate"
        [closeOnCreate]="true"
        [clearable]="true"
        [(values)]="closeValues"
        placeholder="Invite user…"
      >
        <ng-template
          cngxSelectAction
          let-term
          let-commit="commit"
          let-pending="isPending"
        >
          <button
            type="button"
            [disabled]="!term || pending"
            (click)="commit()"
            style="
              width: 100%;
              padding: 0.5rem 0.75rem;
              border: 0;
              border-top: 1px solid var(--cngx-color-border, #e5e7eb);
              background: transparent;
              text-align: left;
              cursor: pointer;
              font: inherit;
            "
          >
            @if (pending) { ⏳ Einladen… }
            @else { + „{{ term || '…' }}" einladen (schließt Panel) }
          </button>
        </ng-template>
      </cngx-action-multi-select>

      <div class="event-grid" style="margin-top:12px">
        <div class="event-row">
          <span class="event-label">Invited</span>
          <span class="event-value">{{ closeValues().map(v => v.name).join(', ') || '—' }}</span>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class ActionMultiSelectCloseoncreateTrueConfirmToCreateUx {
  protected readonly _exTitle: string = 'Action Multi Select';
  protected readonly _exDescription: string = 'CngxActionMultiSelect — multi-value combobox with inline quick-create. Eighth sibling of the select family; reuses createCreateCommitHandler with a dedicated commit controller so toggle/create lifecycles stay independent.';
  protected readonly _exSectionTitle: string = 'closeOnCreate=true — confirm-to-create UX';
  protected readonly _exSubtitle: string = 'Opt into <code>[closeOnCreate]="true"</code> for flows where each create is a discrete transaction — the panel closes after every successful create, matching the single-value <code>CngxActionSelect</code> default. Useful when your UX wants the consumer to pause and confirm before continuing.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exTs: string = `import { CngxActionMultiSelect, type CngxActionMultiSelectChange, type CngxSelectCreateAction, type CngxSelectOptionDef } from '@cngx/forms/select';
import { CngxSelectAction } from '@cngx/forms/select';
import { delay, of, throwError } from 'rxjs';

protected readonly tags: CngxSelectOptionDef<{ id: string; name: string }>[] = [
  { value: { id: 't1', name: 'Design' }, label: 'Design' },
  { value: { id: 't2', name: 'Development' }, label: 'Development' },
  { value: { id: 't3', name: 'QA' }, label: 'QA' },
  { value: { id: 't4', name: 'Docs' }, label: 'Docs' },
  { value: { id: 't5', name: 'Review' }, label: 'Review' },
];

protected readonly basicCompare = (
  a: { id: string; name: string } | undefined,
  b: { id: string; name: string } | undefined,
) => (a?.id ?? null) === (b?.id ?? null);

// Basic — create appends; panel stays open.
protected readonly basicValues = signal<{ id: string; name: string }[]>([]);
protected basicCounter = 0;
protected readonly basicCreate: CngxSelectCreateAction<{ id: string; name: string }> =
  (_term, draft) => ({ id: 'local-' + ++this.basicCounter, name: draft.label });

// Pre-seeded + change log showing toggle vs create branches.
protected readonly seededValues = signal<{ id: string; name: string }[]>([
  { id: 't1', name: 'Design' },
  { id: 't3', name: 'QA' },
]);
protected readonly seededLog = signal<string[]>([]);
protected seededCounter = 0;
protected readonly seededCreate: CngxSelectCreateAction<{ id: string; name: string }> =
  (_term, draft) => ({ id: 'seeded-' + ++this.seededCounter, name: draft.label });
protected handleSeededChange(ev: CngxActionMultiSelectChange<{ id: string; name: string }>): void {
  const ts = new Date().toLocaleTimeString();
  const line = ts + ' → ' + ev.action + ' | values=' + ev.values.map((v) => v.name).join(', ');
  this.seededLog.update((l) => [...l.slice(-4), line]);
}

// Async create + error rollback.
protected readonly asyncValues = signal<{ id: string; name: string }[]>([]);
protected readonly asyncShouldFail = signal(false);
protected readonly asyncLog = signal<string[]>([]);
protected asyncCounter = 0;
protected readonly asyncCreate: CngxSelectCreateAction<{ id: string; name: string }> =
  (_term, draft) => {
    if (this.asyncShouldFail()) {
      return throwError(() => new Error('Server rejected "' + draft.label + '"')).pipe(delay(500));
    }
    return of({ id: 'srv-' + ++this.asyncCounter, name: draft.label }).pipe(delay(500));
  };
protected handleAsyncError(err: unknown): void {
  const msg = err instanceof Error ? err.message : String(err);
  this.asyncLog.update((l) => [...l.slice(-4), new Date().toLocaleTimeString() + ' → ' + msg]);
}

// Dirty-guard — same pattern as CngxActionSelect but with multi semantics.
protected readonly dirtyValues = signal<{ id: string; name: string }[]>([]);
protected readonly dirtyNote = signal('');
protected dirtyCounter = 0;
protected readonly dirtyCreate: CngxSelectCreateAction<{ id: string; name: string }> =
  (_term, draft) => of({ id: 'dirty-' + ++this.dirtyCounter, name: draft.label }).pipe(delay(400));
protected handleDirtyInput(value: string, setDirty: (v: boolean) => void): void {
  this.dirtyNote.set(value);
  setDirty(value.length > 0);
}
protected handleDirtyCancel(setDirty: (v: boolean) => void): void {
  this.dirtyNote.set('');
  setDirty(false);
}

// Close-on-create — opt-in for confirm-to-create workflows.
protected readonly closeValues = signal<{ id: string; name: string }[]>([]);
protected closeCounter = 0;
protected readonly closeCreate: CngxSelectCreateAction<{ id: string; name: string }> =
  (_term, draft) => ({ id: 'close-' + ++this.closeCounter, name: draft.label });`;
  protected readonly _exHtml: string = `<cngx-action-multi-select
  [label]="'Invitees'"
  [options]="tags"
  [compareWith]="basicCompare"
  [quickCreateAction]="closeCreate"
  [closeOnCreate]="true"
  [clearable]="true"
  [(values)]="closeValues"
  placeholder="Invite user…"
>
  <ng-template
    cngxSelectAction
    let-term
    let-commit="commit"
    let-pending="isPending"
  >
    <button
      type="button"
      [disabled]="!term || pending"
      (click)="commit()"
      style="
        width: 100%;
        padding: 0.5rem 0.75rem;
        border: 0;
        border-top: 1px solid var(--cngx-color-border, #e5e7eb);
        background: transparent;
        text-align: left;
        cursor: pointer;
        font: inherit;
      "
    >
      @if (pending) { ⏳ Einladen… }
      @else { + „{{ term || '…' }}" einladen (schließt Panel) }
    </button>
  </ng-template>
</cngx-action-multi-select>`;
  protected readonly tags: CngxSelectOptionDef<{ id: string; name: string }>[] = [
      { value: { id: 't1', name: 'Design' }, label: 'Design' },
      { value: { id: 't2', name: 'Development' }, label: 'Development' },
      { value: { id: 't3', name: 'QA' }, label: 'QA' },
      { value: { id: 't4', name: 'Docs' }, label: 'Docs' },
      { value: { id: 't5', name: 'Review' }, label: 'Review' },
    ];

    protected readonly basicCompare = (
      a: { id: string; name: string } | undefined,
      b: { id: string; name: string } | undefined,
    ) => (a?.id ?? null) === (b?.id ?? null);

    // Basic — create appends; panel stays open.
    protected readonly basicValues = signal<{ id: string; name: string }[]>([]);
    protected basicCounter = 0;
    protected readonly basicCreate: CngxSelectCreateAction<{ id: string; name: string }> =
      (_term, draft) => ({ id: 'local-' + ++this.basicCounter, name: draft.label });

    // Pre-seeded + change log showing toggle vs create branches.
    protected readonly seededValues = signal<{ id: string; name: string }[]>([
      { id: 't1', name: 'Design' },
      { id: 't3', name: 'QA' },
    ]);
    protected readonly seededLog = signal<string[]>([]);
    protected seededCounter = 0;
    protected readonly seededCreate: CngxSelectCreateAction<{ id: string; name: string }> =
      (_term, draft) => ({ id: 'seeded-' + ++this.seededCounter, name: draft.label });
    protected handleSeededChange(ev: CngxActionMultiSelectChange<{ id: string; name: string }>): void {
      const ts = new Date().toLocaleTimeString();
      const line = ts + ' → ' + ev.action + ' | values=' + ev.values.map((v) => v.name).join(', ');
      this.seededLog.update((l) => [...l.slice(-4), line]);
    }

    // Async create + error rollback.
    protected readonly asyncValues = signal<{ id: string; name: string }[]>([]);
    protected readonly asyncShouldFail = signal(false);
    protected readonly asyncLog = signal<string[]>([]);
    protected asyncCounter = 0;
    protected readonly asyncCreate: CngxSelectCreateAction<{ id: string; name: string }> =
      (_term, draft) => {
        if (this.asyncShouldFail()) {
          return throwError(() => new Error('Server rejected "' + draft.label + '"')).pipe(delay(500));
        }
        return of({ id: 'srv-' + ++this.asyncCounter, name: draft.label }).pipe(delay(500));
      };
    protected handleAsyncError(err: unknown): void {
      const msg = err instanceof Error ? err.message : String(err);
      this.asyncLog.update((l) => [...l.slice(-4), new Date().toLocaleTimeString() + ' → ' + msg]);
    }

    // Dirty-guard — same pattern as CngxActionSelect but with multi semantics.
    protected readonly dirtyValues = signal<{ id: string; name: string }[]>([]);
    protected readonly dirtyNote = signal('');
    protected dirtyCounter = 0;
    protected readonly dirtyCreate: CngxSelectCreateAction<{ id: string; name: string }> =
      (_term, draft) => of({ id: 'dirty-' + ++this.dirtyCounter, name: draft.label }).pipe(delay(400));
    protected handleDirtyInput(value: string, setDirty: (v: boolean) => void): void {
      this.dirtyNote.set(value);
      setDirty(value.length > 0);
    }
    protected handleDirtyCancel(setDirty: (v: boolean) => void): void {
      this.dirtyNote.set('');
      setDirty(false);
    }

    // Close-on-create — opt-in for confirm-to-create workflows.
    protected readonly closeValues = signal<{ id: string; name: string }[]>([]);
    protected closeCounter = 0;
    protected readonly closeCreate: CngxSelectCreateAction<{ id: string; name: string }> =
      (_term, draft) => ({ id: 'close-' + ++this.closeCounter, name: draft.label });
}
