// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/dialog/dialog-demo/dialog-demo.story.ts#section[9] "Bottom Sheet"

import { ChangeDetectionStrategy, Component, computed, viewChild } from '@angular/core';
import { CngxDialog, CngxDialogTitle, CngxDialogClose, CngxBottomSheet } from '@cngx/common/dialog';
import { CngxSwipeDismiss } from '@cngx/common/interactive';

@Component({
  selector: 'app-dialog-bottom-sheet',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxDialog, CngxDialogTitle, CngxDialogClose, CngxBottomSheet, CngxSwipeDismiss],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <button class="chip" (click)="sheetDlg.open()">Open Bottom Sheet</button>

      <dialog cngxDialog cngxBottomSheet [cngxSwipeDismiss]="'down'" #sheetDlg="cngxDialog">
        <h2 cngxDialogTitle>Share Options</h2>
        <div style="display: flex; flex-direction: column; gap: 12px; margin-top: 12px;">
          <button class="chip" [cngxDialogClose]="'copy'" style="text-align: left;">Copy Link</button>
          <button class="chip" [cngxDialogClose]="'email'" style="text-align: left;">Send via Email</button>
          <button class="chip" [cngxDialogClose]="'message'" style="text-align: left;">Send Message</button>
        </div>
        <button class="chip" cngxDialogClose style="margin-top: 16px; width: 100%;">Cancel</button>
      </dialog>

      <div class="status-row" style="margin-top: 12px">
        <span class="status-badge">state: {{ sheetDlg.lifecycle() }}</span>
        <span class="status-badge">result: {{ sheetDlg.result() ?? '-' }}</span>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class DialogBottomSheet {
  protected readonly _exTitle: string = 'Dialog';
  protected readonly _exDescription: string = 'Signal-driven state machine for native &lt;dialog&gt;. Typed results, deterministic focus return, ARIA communication, CSS transition support, and opt-in draggable behavior.';
  protected readonly _exSectionTitle: string = 'Bottom Sheet';
  protected readonly _exSubtitle: string = '<code>CngxBottomSheet</code> is a molecule directive that positions the dialog at the viewport bottom with a drag handle (via <code>::before</code>) and slide-up animation. Add <code>[cngxSwipeDismiss]</code> for swipe-to-dismiss — the directive auto-wires it. Themed via <code>bottom-sheet-theme.scss</code> with CSS custom properties.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxDialog', 'CngxDialogTitle', 'CngxDialogDescription', 'CngxDialogClose', 'CngxDialogDraggable', 'CngxDialogStack'];
  protected readonly _exTs: string = `import { CngxDialog, CngxDialogTitle, CngxDialogClose, CngxBottomSheet } from '@cngx/common/dialog';
import { CngxSwipeDismiss } from '@cngx/common/interactive';

// Fake form data for the form dialog demo
protected readonly formData = { name: '', email: '' };

// ── Programmatic demo ──────────────────────────────────────────
protected readonly progDialog = viewChild<CngxDialog<'saved' | 'discarded'>>('progDialog');

protected readonly progMessage = computed(() => {
  const result = this.progDialog()?.result();
  if (result === undefined) return 'No dialog result yet.';
  if (result === 'dismissed') return 'Dialog was dismissed (Escape or backdrop).';
  return 'Dialog returned: ' + String(result);
});

protected handleOpenProgrammatic(): void {
  this.progDialog()?.open();
}

protected handleSaveProgrammatic(): void {
  this.progDialog()?.close('saved');
}

protected handleDiscardProgrammatic(): void {
  this.progDialog()?.close('discarded');
}`;
  protected readonly _exHtml: string = `<button class="chip" (click)="sheetDlg.open()">Open Bottom Sheet</button>

<dialog cngxDialog cngxBottomSheet [cngxSwipeDismiss]="'down'" #sheetDlg="cngxDialog">
  <h2 cngxDialogTitle>Share Options</h2>
  <div style="display: flex; flex-direction: column; gap: 12px; margin-top: 12px;">
    <button class="chip" [cngxDialogClose]="'copy'" style="text-align: left;">Copy Link</button>
    <button class="chip" [cngxDialogClose]="'email'" style="text-align: left;">Send via Email</button>
    <button class="chip" [cngxDialogClose]="'message'" style="text-align: left;">Send Message</button>
  </div>
  <button class="chip" cngxDialogClose style="margin-top: 16px; width: 100%;">Cancel</button>
</dialog>

<div class="status-row" style="margin-top: 12px">
  <span class="status-badge">state: {{ sheetDlg.lifecycle() }}</span>
  <span class="status-badge">result: {{ sheetDlg.result() ?? '-' }}</span>
</div>`;
  // Fake form data for the form dialog demo
    protected readonly formData = { name: '', email: '' };

    // ── Programmatic demo ──────────────────────────────────────────
    protected readonly progDialog = viewChild<CngxDialog<'saved' | 'discarded'>>('progDialog');

    protected readonly progMessage = computed(() => {
      const result = this.progDialog()?.result();
      if (result === undefined) return 'No dialog result yet.';
      if (result === 'dismissed') return 'Dialog was dismissed (Escape or backdrop).';
      return 'Dialog returned: ' + String(result);
    });

    protected handleOpenProgrammatic(): void {
      this.progDialog()?.open();
    }

    protected handleSaveProgrammatic(): void {
      this.progDialog()?.close('saved');
    }

    protected handleDiscardProgrammatic(): void {
      this.progDialog()?.close('discarded');
    }
}
