// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/dialog/dialog-demo/dialog-demo.story.ts#section[1] "Programmatic Control"

import { ChangeDetectionStrategy, Component, computed, viewChild } from '@angular/core';
import { CngxDialog, CngxDialogTitle } from '@cngx/common/dialog';

@Component({
  selector: 'app-dialog-programmatic-control',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxDialog, CngxDialogTitle],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="button-row">
        <button class="chip" (click)="handleOpenProgrammatic()">Open from Code</button>
      </div>

      <dialog cngxDialog #progDialog="cngxDialog">
        <h2 cngxDialogTitle>Unsaved Changes</h2>
        <p style="margin: 12px 0;">You have unsaved changes. What would you like to do?</p>
        <div class="button-row" style="justify-content: flex-end;">
          <button class="chip" (click)="handleDiscardProgrammatic()">Discard</button>
          <button class="chip chip--active" (click)="handleSaveProgrammatic()">Save</button>
        </div>
      </dialog>

      <div class="code-block" style="margin-top: 12px">
        {{ progMessage() }}
      </div>
      <div class="status-row" style="margin-top: 8px">
        <span class="status-badge">state: {{ progDialog.lifecycle() }}</span>
        <span class="status-badge">result: {{ progDialog.result() ?? 'undefined' }}</span>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class DialogProgrammaticControl {
  protected readonly _exTitle: string = 'Dialog';
  protected readonly _exDescription: string = 'Signal-driven state machine for native &lt;dialog&gt;. Typed results, deterministic focus return, ARIA communication, CSS transition support, and opt-in draggable behavior.';
  protected readonly _exSectionTitle: string = 'Programmatic Control';
  protected readonly _exSubtitle: string = 'Open and close from component code via <code>viewChild</code>. The <code>result()</code> signal feeds into <code>computed()</code> — no subscriptions, no event handlers, pure reactive derivation.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxDialog', 'CngxDialogTitle', 'CngxDialogDescription', 'CngxDialogClose', 'CngxDialogDraggable', 'CngxDialogStack'];
  protected readonly _exTs: string = `import { CngxDialog, CngxDialogTitle } from '@cngx/common/dialog';

// Fake form data for the form dialog demo
protected readonly formData = { name: '', email: '' };

// ── Programmatic demo ──────────────────────────────────────────
protected readonly progDialog = viewChild<CngxDialog<'saved' | 'discarded'>>('progDialog');

protected readonly progMessage = computed(() => {
  const result = this.progDialog()?.result();
  if (result === undefined) return 'No dialog result yet.';
  if (result === 'dismissed') return 'Dialog was dismissed (Escape or backdrop).';
  return 'Dialog returned: ' + String(result);
});

protected handleOpenProgrammatic(): void {
  this.progDialog()?.open();
}

protected handleSaveProgrammatic(): void {
  this.progDialog()?.close('saved');
}

protected handleDiscardProgrammatic(): void {
  this.progDialog()?.close('discarded');
}`;
  protected readonly _exHtml: string = `<div class="button-row">
  <button class="chip" (click)="handleOpenProgrammatic()">Open from Code</button>
</div>

<dialog cngxDialog #progDialog="cngxDialog">
  <h2 cngxDialogTitle>Unsaved Changes</h2>
  <p style="margin: 12px 0;">You have unsaved changes. What would you like to do?</p>
  <div class="button-row" style="justify-content: flex-end;">
    <button class="chip" (click)="handleDiscardProgrammatic()">Discard</button>
    <button class="chip chip--active" (click)="handleSaveProgrammatic()">Save</button>
  </div>
</dialog>

<div class="code-block" style="margin-top: 12px">
  {{ progMessage() }}
</div>
<div class="status-row" style="margin-top: 8px">
  <span class="status-badge">state: {{ progDialog.lifecycle() }}</span>
  <span class="status-badge">result: {{ progDialog.result() ?? 'undefined' }}</span>
</div>`;
  // Fake form data for the form dialog demo
    protected readonly formData = { name: '', email: '' };

    // ── Programmatic demo ──────────────────────────────────────────
    protected readonly progDialog = viewChild<CngxDialog<'saved' | 'discarded'>>('progDialog');

    protected readonly progMessage = computed(() => {
      const result = this.progDialog()?.result();
      if (result === undefined) return 'No dialog result yet.';
      if (result === 'dismissed') return 'Dialog was dismissed (Escape or backdrop).';
      return 'Dialog returned: ' + String(result);
    });

    protected handleOpenProgrammatic(): void {
      this.progDialog()?.open();
    }

    protected handleSaveProgrammatic(): void {
      this.progDialog()?.close('saved');
    }

    protected handleDiscardProgrammatic(): void {
      this.progDialog()?.close('discarded');
    }
}
