// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/display/avatar-demo/avatar-demo.story.ts#section[1] "Cascade: image, initials, fallback"

import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CngxAvatar } from '@cngx/common/display';

@Component({
  selector: 'app-avatar-cascade-image-initials-fallback',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxAvatar],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="row">
        <cngx-avatar src="https://i.pravatar.cc/80?u=jane" alt="Jane" initials="JD"></cngx-avatar>
        <cngx-avatar src="https://example.com/broken.jpg" initials="JD"></cngx-avatar>
        <cngx-avatar>
          <span aria-hidden="true" style="font-size:1.25em">?</span>
        </cngx-avatar>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class AvatarCascadeImageInitialsFallback {
  protected readonly _exTitle: string = 'Avatar';
  protected readonly _exDescription: string = 'Avatar display atom with image / initials / content fallback cascade and optional status indicator.';
  protected readonly _exSectionTitle: string = 'Cascade: image, initials, fallback';
  protected readonly _exSubtitle: string = 'Image takes priority. If it errors (try the second one), initials render. The third falls back to projected content.';
  protected readonly _exTs: string = `import { CngxAvatar } from '@cngx/common/display';`;
  protected readonly _exHtml: string = `<div class="row">
  <cngx-avatar src="https://i.pravatar.cc/80?u=jane" alt="Jane" initials="JD"></cngx-avatar>
  <cngx-avatar src="https://example.com/broken.jpg" initials="JD"></cngx-avatar>
  <cngx-avatar>
    <span aria-hidden="true" style="font-size:1.25em">?</span>
  </cngx-avatar>
</div>`;
}
