// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/filter-builder-json-demo/filter-builder-json-demo.story.ts#section[0] "Builder ↔ JSON"

import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { CngxFilterBuilder, createEmptyFilterRoot, createFilterExpression, createFilterGroup, type FilterFieldDef, type FilterGroup } from '@cngx/forms/filter-builder';

@Component({
  selector: 'app-filter-builder-json-builder-json',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxFilterBuilder],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="json-demo">
        <div class="json-demo__builder">
          <cngx-filter-builder [fields]="fields" [(value)]="tree" />
          <div class="json-demo__actions">
            <button type="button" (click)="resetTree()">Reset</button>
            <button type="button" (click)="seedExamplePreset()">Seed preset</button>
          </div>
        </div>
        <div class="json-demo__output">
          <div class="json-demo__status">
            <span class="status-badge">Nodes: {{ nodeCount() }}</span>
          </div>
          <pre class="code-block">{{ jsonOut() }}</pre>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class FilterBuilderJsonBuilderJson {
  protected readonly _exTitle: string = 'Filter Builder — JSON form component';
  protected readonly _exDescription: string = '&lt;cngx-filter-builder&gt; driven as a pure form component: the consumer reads the tree as JSON, ships it to a backend, or stores it as a preset. No table, no predicate evaluation — the builder is the sole UI for assembling a serialisable FilterGroup.';
  protected readonly _exSectionTitle: string = 'Builder ↔ JSON';
  protected readonly _exSubtitle: string = 'Build a tree on the left; copy the JSON on the right. No table, no predicate — the FilterGroup IS the form value.';
  protected readonly _exTs: string = `import { CngxFilterBuilder, createEmptyFilterRoot, createFilterExpression, createFilterGroup, type FilterFieldDef, type FilterGroup } from '@cngx/forms/filter-builder';

protected readonly fields: readonly FilterFieldDef[] = [
  { key: 'name', label: 'Name', editorType: 'string' },
  { key: 'age', label: 'Age', editorType: 'number' },
  { key: 'active', label: 'Active', editorType: 'boolean' },
  { key: 'role', label: 'Role', editorType: 'string' },
];
protected readonly tree = signal<FilterGroup>(createEmptyFilterRoot());
protected readonly jsonOut = computed(() => JSON.stringify(this.tree(), null, 2));
protected readonly nodeCount = computed(() => this.countNodes(this.tree()));

private countNodes(group: FilterGroup): number {
  let n = 1;
  for (const child of group.filters) {
    n += child.type === 'group' ? this.countNodes(child) : 1;
  }
  return n;
}

protected resetTree(): void {
  this.tree.set(createEmptyFilterRoot());
}

protected seedExamplePreset(): void {
  this.tree.set(
    createFilterGroup('and', [
      createFilterExpression('role', 'eq', 'Engineer'),
      createFilterGroup('or', [
        createFilterExpression('age', 'gte', 30),
        createFilterExpression('active', 'eq', true),
      ]),
    ]),
  );
}`;
  protected readonly _exHtml: string = `<div class="json-demo">
  <div class="json-demo__builder">
    <cngx-filter-builder [fields]="fields" [(value)]="tree" />
    <div class="json-demo__actions">
      <button type="button" (click)="resetTree()">Reset</button>
      <button type="button" (click)="seedExamplePreset()">Seed preset</button>
    </div>
  </div>
  <div class="json-demo__output">
    <div class="json-demo__status">
      <span class="status-badge">Nodes: {{ nodeCount() }}</span>
    </div>
    <pre class="code-block">{{ jsonOut() }}</pre>
  </div>
</div>`;
  protected readonly fields: readonly FilterFieldDef[] = [
      { key: 'name', label: 'Name', editorType: 'string' },
      { key: 'age', label: 'Age', editorType: 'number' },
      { key: 'active', label: 'Active', editorType: 'boolean' },
      { key: 'role', label: 'Role', editorType: 'string' },
    ];
    protected readonly tree = signal<FilterGroup>(createEmptyFilterRoot());
    protected readonly jsonOut = computed(() => JSON.stringify(this.tree(), null, 2));
    protected readonly nodeCount = computed(() => this.countNodes(this.tree()));

    private countNodes(group: FilterGroup): number {
      let n = 1;
      for (const child of group.filters) {
        n += child.type === 'group' ? this.countNodes(child) : 1;
      }
      return n;
    }

    protected resetTree(): void {
      this.tree.set(createEmptyFilterRoot());
    }

    protected seedExamplePreset(): void {
      this.tree.set(
        createFilterGroup('and', [
          createFilterExpression('role', 'eq', 'Engineer'),
          createFilterGroup('or', [
            createFilterExpression('age', 'gte', 30),
            createFilterExpression('active', 'eq', true),
          ]),
        ]),
      );
    }
}
