// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/ui/sidenav-demo/sidenav-demo.story.ts#section[2] "Material Theming -- Light vs Dark"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxSidenavLayout, CngxSidenav, CngxSidenavContent, CngxSidenavHeader, CngxSidenavFooter } from '@cngx/ui';
import { CngxNavLink, CngxNavLabel } from '@cngx/common';

@Component({
  selector: 'app-sidenav-material-theming-light-vs-dark',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxSidenavLayout, CngxSidenav, CngxSidenavContent, CngxSidenavHeader, CngxSidenavFooter, CngxNavLink],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
        <!-- Light theme (M3 light via sidenav-theme.scss) -->
        <div>
          <div style="font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted, #888); margin-bottom: 0.5rem;">Light (M3)</div>
          <cngx-sidenav-layout style="height: 300px; border-radius: 6px; overflow: hidden;">
            <cngx-sidenav position="start" [opened]="true" mode="side" width="170px">
              <cngx-sidenav-header>Workspace</cngx-sidenav-header>
              @for (item of ['Dashboard', 'Inbox', 'Calendar', 'Settings']; track item) {
                <a cngxNavLink [active]="item === 'Dashboard'">
                  {{ item }}
                </a>
              }
              <cngx-sidenav-footer>v2.1</cngx-sidenav-footer>
            </cngx-sidenav>
            <cngx-sidenav-content style="padding: var(--cngx-sidenav-padding, 16px);">
              <p style="font-size: 0.8rem; margin: 0; opacity: 0.6;">M3 light surface tokens via <code>sidenav.theme($theme)</code>.</p>
            </cngx-sidenav-content>
          </cngx-sidenav-layout>
        </div>

        <!-- Dark theme (M3 dark via data-theme="dark") -->
        <div data-theme="dark" style="background: var(--bg, #121212); color: var(--text-primary, #e0e0e0); border-radius: 6px;">
          <div style="font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted, #888); margin-bottom: 0.5rem; padding: 0.5rem 0.5rem 0;">Dark (M3)</div>
          <cngx-sidenav-layout style="height: 300px; border-radius: 6px; overflow: hidden;">
            <cngx-sidenav position="start" [opened]="true" mode="side" width="170px">
              <cngx-sidenav-header>Workspace</cngx-sidenav-header>
              @for (item of ['Dashboard', 'Inbox', 'Calendar', 'Settings']; track item) {
                <a cngxNavLink [active]="item === 'Dashboard'">
                  {{ item }}
                </a>
              }
              <cngx-sidenav-footer>v2.1</cngx-sidenav-footer>
            </cngx-sidenav>
            <cngx-sidenav-content style="padding: var(--cngx-sidenav-padding, 16px);">
              <p style="font-size: 0.8rem; margin: 0; opacity: 0.6;">M3 dark surface tokens via <code>sidenav.theme($dark-theme)</code>.</p>
            </cngx-sidenav-content>
          </cngx-sidenav-layout>
        </div>
      </div>

      <pre class="code-block" style="margin-top: 1rem;"><code>@use '@angular/material' as mat;
    @use '@cngx/ui/sidenav/sidenav-theme' as sidenav;

    $theme: mat.define-theme((color: (primary: mat.$azure-palette)));
    $dark:  mat.define-theme((color: (primary: mat.$azure-palette, theme-type: dark)));

    html &#123;
      @include mat.all-component-themes($theme);
      @include sidenav.theme($theme);
    &#125;

    [data-theme='dark'] &#123;
      @include mat.all-component-colors($dark);
      @include sidenav.theme($dark);
    &#125;</code></pre>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class SidenavMaterialThemingLightVsDark {
  protected readonly _exTitle: string = 'Sidenav';
  protected readonly _exDescription: string = 'Declarative sidebar organism with Material theming, nav atoms (links, groups, badges, labels), dual sidebar support, and responsive mode switching.';
  protected readonly _exSectionTitle: string = 'Material Theming -- Light vs Dark';
  protected readonly _exSubtitle: string = 'Both panels use the real <code>sidenav-theme.scss</code> mixin applied via <code>styles.scss</code>. The right panel sets <code>data-theme="dark"</code> which activates the dark M3 color tokens. No inline overrides -- purely Material Design 3 system colors.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxSidenav', 'CngxSidenavLayout', 'CngxSidenavContent'];
  protected readonly _exTs: string = `import { CngxSidenavLayout, CngxSidenav, CngxSidenavContent, CngxSidenavHeader, CngxSidenavFooter } from '@cngx/ui';
import { CngxNavLink, CngxNavLabel } from '@cngx/common';

// Demo 1: Full nav
protected readonly navOpen = signal(true);
protected readonly navMode = signal<'over' | 'push' | 'side' | 'mini'>('side');
protected readonly modes: ('over' | 'push' | 'side' | 'mini')[] = ['over', 'push', 'side', 'mini'];
protected readonly activeLink = signal('/dashboard');

// Demo 2: Dual sidebar
protected readonly leftOpen = signal(true);
protected readonly rightOpen = signal(false);
protected readonly selectedItem = signal<string | null>(null);
protected readonly items = ['Order #1042', 'Order #1043', 'Order #1044', 'Order #1045'];

protected selectItem(item: string): void {
  this.selectedItem.set(item);
  this.rightOpen.set(true);
}`;
  protected readonly _exHtml: string = `  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
    <!-- Light theme (M3 light via sidenav-theme.scss) -->
    <div>
      <div style="font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted, #888); margin-bottom: 0.5rem;">Light (M3)</div>
      <cngx-sidenav-layout style="height: 300px; border-radius: 6px; overflow: hidden;">
        <cngx-sidenav position="start" [opened]="true" mode="side" width="170px">
          <cngx-sidenav-header>Workspace</cngx-sidenav-header>
          @for (item of ['Dashboard', 'Inbox', 'Calendar', 'Settings']; track item) {
            <a cngxNavLink [active]="item === 'Dashboard'">
              {{ item }}
            </a>
          }
          <cngx-sidenav-footer>v2.1</cngx-sidenav-footer>
        </cngx-sidenav>
        <cngx-sidenav-content style="padding: var(--cngx-sidenav-padding, 16px);">
          <p style="font-size: 0.8rem; margin: 0; opacity: 0.6;">M3 light surface tokens via <code>sidenav.theme($theme)</code>.</p>
        </cngx-sidenav-content>
      </cngx-sidenav-layout>
    </div>

    <!-- Dark theme (M3 dark via data-theme="dark") -->
    <div data-theme="dark" style="background: var(--bg, #121212); color: var(--text-primary, #e0e0e0); border-radius: 6px;">
      <div style="font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted, #888); margin-bottom: 0.5rem; padding: 0.5rem 0.5rem 0;">Dark (M3)</div>
      <cngx-sidenav-layout style="height: 300px; border-radius: 6px; overflow: hidden;">
        <cngx-sidenav position="start" [opened]="true" mode="side" width="170px">
          <cngx-sidenav-header>Workspace</cngx-sidenav-header>
          @for (item of ['Dashboard', 'Inbox', 'Calendar', 'Settings']; track item) {
            <a cngxNavLink [active]="item === 'Dashboard'">
              {{ item }}
            </a>
          }
          <cngx-sidenav-footer>v2.1</cngx-sidenav-footer>
        </cngx-sidenav>
        <cngx-sidenav-content style="padding: var(--cngx-sidenav-padding, 16px);">
          <p style="font-size: 0.8rem; margin: 0; opacity: 0.6;">M3 dark surface tokens via <code>sidenav.theme($dark-theme)</code>.</p>
        </cngx-sidenav-content>
      </cngx-sidenav-layout>
    </div>
  </div>

  <pre class="code-block" style="margin-top: 1rem;"><code>@use '@angular/material' as mat;
@use '@cngx/ui/sidenav/sidenav-theme' as sidenav;

$theme: mat.define-theme((color: (primary: mat.$azure-palette)));
$dark:  mat.define-theme((color: (primary: mat.$azure-palette, theme-type: dark)));

html &#123;
  @include mat.all-component-themes($theme);
  @include sidenav.theme($theme);
&#125;

[data-theme='dark'] &#123;
  @include mat.all-component-colors($dark);
  @include sidenav.theme($dark);
&#125;</code></pre>`;
  // Demo 1: Full nav
    protected readonly navOpen = signal(true);
    protected readonly navMode = signal<'over' | 'push' | 'side' | 'mini'>('side');
    protected readonly modes: ('over' | 'push' | 'side' | 'mini')[] = ['over', 'push', 'side', 'mini'];
    protected readonly activeLink = signal('/dashboard');

    // Demo 2: Dual sidebar
    protected readonly leftOpen = signal(true);
    protected readonly rightOpen = signal(false);
    protected readonly selectedItem = signal<string | null>(null);
    protected readonly items = ['Order #1042', 'Order #1043', 'Order #1044', 'Order #1045'];

    protected selectItem(item: string): void {
      this.selectedItem.set(item);
      this.rightOpen.set(true);
    }
}
