// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/layout/drawer-demo/drawer-demo.story.ts#section[1] "Direction — All Four Sides"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxDrawer, CngxDrawerPanel, CngxDrawerContent, type DrawerMode } from '@cngx/common';

@Component({
  selector: 'app-drawer-direction-all-four-sides',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxDrawer, CngxDrawerPanel, CngxDrawerContent],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="filter-row">
        <span class="filter-label">Position:</span>
        @for (d of directions; track d) {
          <button class="chip" [class.chip--active]="direction() === d"
                  (click)="direction.set(d)">{{ d }}</button>
        }
      </div>

      <div cngxDrawer #dirDrawer="cngxDrawer" class="drawer-container drawer-container--bordered">
        <button class="sort-btn" (click)="dirDrawer.toggle()">
          Toggle {{ direction() }} drawer
        </button>

        <div class="drawer-layout drawer-layout--relative">
          <aside [cngxDrawerPanel]="dirDrawer" [position]="direction()"
                 [enabled]="dirDrawer.opened()"
                 class="drawer-panel drawer-panel--direction"
                 [class.drawer-panel--horizontal]="direction() === 'left' || direction() === 'right'"
                 [class.drawer-panel--vertical]="direction() === 'top' || direction() === 'bottom'">
            <div class="drawer-panel-content">
              <strong>{{ direction() }} panel</strong>
              <button class="sort-btn" (click)="dirDrawer.close()">Close</button>
            </div>
          </aside>

          <main [cngxDrawerContent]="dirDrawer" class="drawer-main drawer-main--tall">
            <p>Content shifts when the drawer opens. Direction: <strong>{{ direction() }}</strong></p>
          </main>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class DrawerDirectionAllFourSides {
  protected readonly _exTitle: string = 'Drawer';
  protected readonly _exDescription: string = 'Headless drawer/sidebar system: CngxDrawer (state), CngxDrawerPanel (sliding panel), CngxDrawerContent (content offset). Supports left/right/top/bottom, focus trapping, click-outside close, Escape key, and controlled+uncontrolled modes.';
  protected readonly _exSectionTitle: string = 'Direction — All Four Sides';
  protected readonly _exSubtitle: string = 'Change <code>[position]</code> to <code>left</code>, <code>right</code>, <code>top</code>, or <code>bottom</code>. The directives only set CSS classes — the consumer provides the transition.';
  protected readonly _exTs: string = `import { CngxDrawer, CngxDrawerPanel, CngxDrawerContent, type DrawerMode } from '@cngx/common';

// Controlled drawer
protected readonly controlledOpen = signal(false);

// Direction playground
protected readonly direction = signal<'left' | 'right' | 'top' | 'bottom'>('left');
protected readonly directions: ('left' | 'right' | 'top' | 'bottom')[] = ['left', 'right', 'top', 'bottom'];

// Mode playground
protected readonly mode = signal<DrawerMode>('over');
protected readonly modes: DrawerMode[] = ['over', 'push', 'side'];

// Event log
protected readonly events = signal<string[]>([]);
protected logEvent(name: string): void {
  this.events.update(e => [name + ' @ ' + new Date().toLocaleTimeString(), ...e].slice(0, 5));
}`;
  protected readonly _exHtml: string = `<div class="filter-row">
  <span class="filter-label">Position:</span>
  @for (d of directions; track d) {
    <button class="chip" [class.chip--active]="direction() === d"
            (click)="direction.set(d)">{{ d }}</button>
  }
</div>

<div cngxDrawer #dirDrawer="cngxDrawer" class="drawer-container drawer-container--bordered">
  <button class="sort-btn" (click)="dirDrawer.toggle()">
    Toggle {{ direction() }} drawer
  </button>

  <div class="drawer-layout drawer-layout--relative">
    <aside [cngxDrawerPanel]="dirDrawer" [position]="direction()"
           [enabled]="dirDrawer.opened()"
           class="drawer-panel drawer-panel--direction"
           [class.drawer-panel--horizontal]="direction() === 'left' || direction() === 'right'"
           [class.drawer-panel--vertical]="direction() === 'top' || direction() === 'bottom'">
      <div class="drawer-panel-content">
        <strong>{{ direction() }} panel</strong>
        <button class="sort-btn" (click)="dirDrawer.close()">Close</button>
      </div>
    </aside>

    <main [cngxDrawerContent]="dirDrawer" class="drawer-main drawer-main--tall">
      <p>Content shifts when the drawer opens. Direction: <strong>{{ direction() }}</strong></p>
    </main>
  </div>
</div>`;
  // Controlled drawer
    protected readonly controlledOpen = signal(false);

    // Direction playground
    protected readonly direction = signal<'left' | 'right' | 'top' | 'bottom'>('left');
    protected readonly directions: ('left' | 'right' | 'top' | 'bottom')[] = ['left', 'right', 'top', 'bottom'];

    // Mode playground
    protected readonly mode = signal<DrawerMode>('over');
    protected readonly modes: DrawerMode[] = ['over', 'push', 'side'];

    // Event log
    protected readonly events = signal<string[]>([]);
    protected logEvent(name: string): void {
      this.events.update(e => [name + ' @ ' + new Date().toLocaleTimeString(), ...e].slice(0, 5));
    }
}
