// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: examples/stories/common/card/card-grid-demo/card-grid-demo.story.ts#section[1] "Density Variants"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxCard, CngxCardBody, CngxCardGrid } from '@cngx/common/card';

@Component({
  selector: 'app-card-grid-density-variants',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxCard, CngxCardBody, CngxCardGrid],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="button-row" style="margin-bottom:12px">
        <button [class.chip--active]="density() === 'compact'" class="chip"
                (click)="density.set('compact')">Compact</button>
        <button [class.chip--active]="density() === 'default'" class="chip"
                (click)="density.set('default')">Default</button>
        <button [class.chip--active]="density() === 'comfortable'" class="chip"
                (click)="density.set('comfortable')">Comfortable</button>
      </div>
      <cngx-card-grid minWidth="140px" [density]="density()">
        @for (item of items(); track item) {
          <cngx-card>
            <div cngxCardBody style="font-size:0.875rem">{{ item }}</div>
          </cngx-card>
        }
      </cngx-card-grid>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class CardGridDensityVariants {
  protected readonly _exTitle: string = 'Card Grid';
  protected readonly _exDescription: string = 'Responsive card grid with intrinsic sizing, keyboard navigation via roving tabindex, density levels, and reason-based empty state template selection.';
  protected readonly _exSectionTitle: string = 'Density Variants';
  protected readonly _exSubtitle: string = 'Toggle density to see gap and padding changes. <code>compact</code> for dashboards, <code>comfortable</code> for browsing.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'molecule' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'visual-variants' }, { dim: 'focus', value: 'composition' }];
  protected readonly _exTs: string = `import { CngxCard, CngxCardBody, CngxCardGrid } from '@cngx/common/card';

protected items = signal(['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta']);
protected density = signal<'compact' | 'default' | 'comfortable'>('default');`;
  protected readonly _exHtml: string = `<div class="button-row" style="margin-bottom:12px">
  <button [class.chip--active]="density() === 'compact'" class="chip"
          (click)="density.set('compact')">Compact</button>
  <button [class.chip--active]="density() === 'default'" class="chip"
          (click)="density.set('default')">Default</button>
  <button [class.chip--active]="density() === 'comfortable'" class="chip"
          (click)="density.set('comfortable')">Comfortable</button>
</div>
<cngx-card-grid minWidth="140px" [density]="density()">
  @for (item of items(); track item) {
    <cngx-card>
      <div cngxCardBody style="font-size:0.875rem">{{ item }}</div>
    </cngx-card>
  }
</cngx-card-grid>`;
  protected items = signal(['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta']);
    protected emptyItems = signal<string[]>([]);
    protected emptyReason = signal<'first-use' | 'no-results' | 'cleared' | undefined>('first-use');
    protected density = signal<'compact' | 'default' | 'comfortable'>('default');
}
