// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/numeric-demo/numeric-demo.story.ts#section[0] "Basic Numeric Input"

import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CngxNumericInput } from '@cngx/forms/input';

@Component({
  selector: 'app-numeric-basic-numeric-input',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxNumericInput],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="demo-form">
        <div class="demo-field">
          <label class="demo-label">Amount</label>
          <input cngxNumericInput #num="cngxNumericInput" class="demo-input" />
          <div class="status-row">
            <span class="status-badge">Value: {{ num.numericValue() }}</span>
            <span class="status-badge">Valid: {{ num.isValid() }}</span>
          </div>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class NumericBasicNumericInput {
  protected readonly _exTitle: string = 'Numeric Input';
  protected readonly _exDescription: string = 'Locale-aware numeric input with Intl.NumberFormat formatting, arrow key increment/decrement, min/max clamping, and decimal control.';
  protected readonly _exSectionTitle: string = 'Basic Numeric Input';
  protected readonly _exSubtitle: string = 'Type digits, use Arrow Up/Down to increment. Shift+Arrow for x10. Value is formatted with thousands separator on blur.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxNumericInput'];
  protected readonly _exTs: string = `import { CngxNumericInput } from '@cngx/forms/input';`;
  protected readonly _exHtml: string = `<div class="demo-form">
  <div class="demo-field">
    <label class="demo-label">Amount</label>
    <input cngxNumericInput #num="cngxNumericInput" class="demo-input" />
    <div class="status-row">
      <span class="status-badge">Value: {{ num.numericValue() }}</span>
      <span class="status-badge">Valid: {{ num.isValid() }}</span>
    </div>
  </div>
</div>`;
}
