// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/numeric-demo/numeric-demo.story.ts#section[1] "Min / Max / Step / Decimals"

import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CngxNumericInput } from '@cngx/forms/input';

@Component({
  selector: 'app-numeric-min-max-step-decimals',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxNumericInput],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="demo-form">
        <div class="demo-field">
          <label class="demo-label">Percentage (0-100, step 5)</label>
          <input cngxNumericInput [min]="0" [max]="100" [step]="5" [decimals]="0"
            #pct="cngxNumericInput" class="demo-input" />
          <div class="status-row">
            <span class="status-badge">{{ pct.numericValue() ?? '-' }}%</span>
          </div>
        </div>
        <div class="demo-field">
          <label class="demo-label">Price (2 decimals, step 0.50)</label>
          <input cngxNumericInput [min]="0" [step]="0.5" [decimals]="2"
            #price="cngxNumericInput" class="demo-input" />
          <div class="status-row">
            <span class="status-badge">{{ price.numericValue() }}</span>
          </div>
        </div>
        <div class="demo-field">
          <label class="demo-label">Temperature (-40 to 60)</label>
          <input cngxNumericInput [min]="-40" [max]="60" [step]="1" [decimals]="1"
            #temp="cngxNumericInput" class="demo-input" />
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class NumericMinMaxStepDecimals {
  protected readonly _exTitle: string = 'Numeric Input';
  protected readonly _exDescription: string = 'Locale-aware numeric input with Intl.NumberFormat formatting, arrow key increment/decrement, min/max clamping, and decimal control.';
  protected readonly _exSectionTitle: string = 'Min / Max / Step / Decimals';
  protected readonly _exSubtitle: string = 'Constrain values with <code>[min]</code>, <code>[max]</code>. Control decimal places with <code>[decimals]</code>. Arrow keys use <code>[step]</code>.';
  protected readonly _exTs: string = `import { CngxNumericInput } from '@cngx/forms/input';`;
  protected readonly _exHtml: string = `<div class="demo-form">
  <div class="demo-field">
    <label class="demo-label">Percentage (0-100, step 5)</label>
    <input cngxNumericInput [min]="0" [max]="100" [step]="5" [decimals]="0"
      #pct="cngxNumericInput" class="demo-input" />
    <div class="status-row">
      <span class="status-badge">{{ pct.numericValue() ?? '-' }}%</span>
    </div>
  </div>
  <div class="demo-field">
    <label class="demo-label">Price (2 decimals, step 0.50)</label>
    <input cngxNumericInput [min]="0" [step]="0.5" [decimals]="2"
      #price="cngxNumericInput" class="demo-input" />
    <div class="status-row">
      <span class="status-badge">{{ price.numericValue() }}</span>
    </div>
  </div>
  <div class="demo-field">
    <label class="demo-label">Temperature (-40 to 60)</label>
    <input cngxNumericInput [min]="-40" [max]="60" [step]="1" [decimals]="1"
      #temp="cngxNumericInput" class="demo-input" />
  </div>
</div>`;
}
