// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/forms/typeahead-demo/typeahead-demo.story.ts#section[0] "Typeahead — single-value async autocomplete"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { form, schema, required } from '@angular/forms/signals';
import { CngxTypeahead, type CngxSelectCommitAction, type CngxSelectOptionDef, type CngxSelectOptionsInput } from '@cngx/forms/select';
import { delay, of, throwError } from 'rxjs';
import { createManualState, type ManualAsyncState } from '@cngx/common/data';

@Component({
  selector: 'app-typeahead-typeahead-single-value-async-autocomplete',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxTypeahead],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0) {
        <ul class="cngx-ex-tags" aria-label="Tags">
          @for (t of _exTags; track t.dim + ':' + t.value) {
            <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
          }
        </ul>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <cngx-typeahead
        [label]="'User'"
        [options]="typeaheadUsers"
        [compareWith]="typeaheadCompare"
        [displayWith]="typeaheadDisplay"
        [clearable]="true"
        placeholder="Search by name…"
        [(value)]="typeaheadValue"
        (searchTermChange)="handleTypeaheadSearch($event)"
      />
      <div class="event-grid" style="margin-top:12px">
        <div class="event-row"><span class="event-label">Value</span><span class="event-value">{{ typeaheadValue()?.name || '—' }}</span></div>
        <div class="event-row"><span class="event-label">Search log</span><span class="event-value">{{ typeaheadSearchLog().join(' → ') || '—' }}</span></div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class TypeaheadTypeaheadSingleValueAsyncAutocomplete {
  protected readonly _exTitle: string = 'Typeahead';
  protected readonly _exDescription: string = 'CngxTypeahead — scalar async autocomplete. Single-value input bound to an async option source with typed-form-field, commit-action and slot-override support.';
  protected readonly _exSectionTitle: string = 'Typeahead — single-value async autocomplete';
  protected readonly _exSubtitle: string = 'Inline <code>&lt;input role="combobox"&gt;</code> with <code>displayWith</code> — type to filter, pick to commit a single value. The input shows <code>displayWith(value)</code> after a pick so the selection survives blur/refocus. <code>clearOnBlur</code> (default <code>true</code>) snaps the input back to the last-committed display if the user types stray text without picking.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [{ dim: 'atomic-level', value: 'organism' }, { dim: 'audience', value: 'dev' }, { dim: 'audience', value: 'design' }, { dim: 'audience', value: 'a11y' }, { dim: 'artifact', value: 'standalone' }, { dim: 'focus', value: 'visual-variants' }, { dim: 'focus', value: 'a11y-pattern' }, { dim: 'focus', value: 'composition' }, { dim: 'framework', value: 'signal-forms' }];
  protected readonly _exTs: string = `import { form, schema, required } from '@angular/forms/signals';
import { CngxTypeahead, type CngxSelectCommitAction, type CngxSelectOptionDef, type CngxSelectOptionsInput } from '@cngx/forms/select';
import { delay, of, throwError } from 'rxjs';
import { createManualState, type ManualAsyncState } from '@cngx/common/data';

protected readonly typeaheadUsers: CngxSelectOptionDef<{ id: number; name: string }>[] = [
  { value: { id: 1, name: 'Alice Meier' },  label: 'Alice Meier' },
  { value: { id: 2, name: 'Bob Schmidt' },  label: 'Bob Schmidt' },
  { value: { id: 3, name: 'Charlotte Fischer' }, label: 'Charlotte Fischer' },
  { value: { id: 4, name: 'David Weber' }, label: 'David Weber' },
  { value: { id: 5, name: 'Eva Wagner' }, label: 'Eva Wagner' },
];
protected readonly typeaheadValue = signal<{ id: number; name: string } | undefined>(undefined);
protected readonly typeaheadCompare = (a: { id: number } | undefined, b: { id: number } | undefined): boolean =>
  (a?.id ?? NaN) === (b?.id ?? NaN);
protected readonly typeaheadDisplay = (u: { id: number; name: string }): string => u.name;
protected readonly typeaheadSearchLog = signal<string[]>([]);
protected handleTypeaheadSearch(term: string): void {
  this.typeaheadSearchLog.update(l => [...l.slice(-4), term]);
}`;
  protected readonly _exHtml: string = `<cngx-typeahead
  [label]="'User'"
  [options]="typeaheadUsers"
  [compareWith]="typeaheadCompare"
  [displayWith]="typeaheadDisplay"
  [clearable]="true"
  placeholder="Search by name…"
  [(value)]="typeaheadValue"
  (searchTermChange)="handleTypeaheadSearch($event)"
/>`;
  protected readonly loading = signal(true);

    protected readonly commitMode = signal<'optimistic' | 'pessimistic'>('optimistic');

    protected readonly commitShouldFail = signal(false);

    protected readonly commitLog = signal<string[]>([]);

    protected readonly commitAction: CngxSelectCommitAction<string> = (intended) => {
      const ts = new Date().toLocaleTimeString();
      this.commitLog.update(l => [...l, ts + ' → commit(' + String(intended) + ')']);
      if (this.commitShouldFail()) {
        return throwError(() => new Error('Server offline')).pipe(delay(800));
      }
      return of(intended).pipe(delay(800));
    };

    protected readonly typeaheadUsers: CngxSelectOptionDef<{ id: number; name: string }>[] = [
      { value: { id: 1, name: 'Alice Meier' },  label: 'Alice Meier' },
      { value: { id: 2, name: 'Bob Schmidt' },  label: 'Bob Schmidt' },
      { value: { id: 3, name: 'Charlotte Fischer' }, label: 'Charlotte Fischer' },
      { value: { id: 4, name: 'David Weber' }, label: 'David Weber' },
      { value: { id: 5, name: 'Eva Wagner' }, label: 'Eva Wagner' },
    ];

    protected readonly typeaheadValue = signal<{ id: number; name: string } | undefined>(undefined);

    protected readonly typeaheadCompare = (a: { id: number } | undefined, b: { id: number } | undefined): boolean =>
      (a?.id ?? NaN) === (b?.id ?? NaN);

    protected readonly typeaheadDisplay = (u: { id: number; name: string }): string => u.name;

    protected readonly typeaheadSearchLog = signal<string[]>([]);

    protected handleTypeaheadSearch(term: string): void {
      this.typeaheadSearchLog.update(l => [...l.slice(-4), term]);
    }

    protected readonly typeaheadColorOptions: CngxSelectOptionDef<string>[] = [
      { value: 'red', label: 'Rot' },
      { value: 'green', label: 'Green' },
      { value: 'blue', label: 'Blau' },
      { value: 'yellow', label: 'Gelb' },
      { value: 'orange', label: 'Orange' },
    ];

    protected readonly typeaheadColorModel = signal<string>('');

    protected readonly typeaheadColorField = form(this.typeaheadColorModel, schema<string>((c) => { required(c); }));

    protected readonly typeaheadAsyncState: ManualAsyncState<CngxSelectOptionsInput<{ id: number; name: string }>> =
      createManualState<CngxSelectOptionsInput<{ id: number; name: string }>>();

    protected readonly typeaheadAsyncValue = signal<{ id: number; name: string } | undefined>(undefined);

    protected typeaheadAsyncSetLoading(): void { this.typeaheadAsyncState.set('loading'); }

    protected typeaheadAsyncSetSuccess(): void { this.typeaheadAsyncState.setSuccess(this.typeaheadUsers); }

    protected typeaheadAsyncSetError(): void { this.typeaheadAsyncState.setError(new Error('Network offline')); }

    protected readonly typeaheadCommitValue = signal<{ id: number; name: string } | undefined>(undefined);

    protected readonly typeaheadCommitMode = signal<'optimistic' | 'pessimistic'>('optimistic');

    protected readonly typeaheadCommitShouldFail = signal(false);

    protected readonly typeaheadCommitLog = signal<string[]>([]);

    protected readonly typeaheadCommitAction: CngxSelectCommitAction<{ id: number; name: string }> = (intended) => {
      const ts = new Date().toLocaleTimeString();
      this.typeaheadCommitLog.update(l => [...l, ts + ' → commit(' + (intended?.name ?? 'undefined') + ')']);
      if (this.typeaheadCommitShouldFail()) {
        return throwError(() => new Error('Server offline')).pipe(delay(800));
      }
      return of(intended).pipe(delay(800));
    };
}
