// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/ui/mat-stepper/mat-stepper-demo/mat-stepper-demo.story.ts

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ExampleCardComponent } from '../../../../shared/example-card.component';
import { DocShellComponent } from '../../../../shared/doc-shell.component';
import { Observable } from 'rxjs';
import { CngxStep, CngxStepContent, type CngxStepperCommitAction } from '@cngx/common/stepper';
import { CngxMatStepper } from '@cngx/ui/mat-stepper';

@Component({
  selector: 'app-mat-stepper-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxMatStepper,
    CngxStep,
    CngxStepContent,
  ],
  template: `
    <app-doc-shell title="Mat-Stepper — async commitAction"
      description="<code>&lt;cngx-mat-stepper&gt;</code> wraps Material's <code>&lt;mat-stepper&gt;</code> while sharing the same <code>CngxStepperPresenter</code> brain as <code>&lt;cngx-stepper&gt;</code>. Material consumers gain commit-action lifecycle, router sync, and error aggregation for free. Toggle <code>[commitMode]</code> + <code>simulate error</code> to exercise the four quadrants — the gate works identically against Material's own state machine."
      [apiComponents]="['CngxMatStepper', 'CngxStepperPresenter', 'CngxStep', 'CngxStepContent']">
      <app-example-card title="Material wizard with the cngx commit lifecycle"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0">
        
  <div role="group" aria-label="Commit mode" class="event-row" style="gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap">
    <button type="button" class="chip"
            [class.chip--active]="mode() === 'optimistic'"
            [attr.aria-pressed]="mode() === 'optimistic'"
            (click)="mode.set('optimistic')">optimistic</button>
    <button type="button" class="chip"
            [class.chip--active]="mode() === 'pessimistic'"
            [attr.aria-pressed]="mode() === 'pessimistic'"
            (click)="mode.set('pessimistic')">pessimistic</button>
    <label style="margin-inline-start:12px">
      <input type="checkbox"
             [checked]="shouldFail()"
             (change)="shouldFail.set($any($event.target).checked)" />
      simulate error
    </label>
    <label style="margin-inline-start:12px">
      latency
      <input type="range" min="100" max="2000" step="100"
             [value]="latencyMs()"
             (input)="latencyMs.set(+$any($event.target).value)" />
      {{ latencyMs() }}ms
    </label>
  </div>
  <cngx-mat-stepper
    [(activeStepIndex)]="active"
    [commitAction]="commitAction"
    [commitMode]="mode()"
    aria-label="Material async wizard"
  >
    <div cngxStep label="Customer">
      <ng-template cngxStepContent><p>Customer details.</p></ng-template>
    </div>
    <div cngxStep label="Payment">
      <ng-template cngxStepContent><p>Payment method.</p></ng-template>
    </div>
    <div cngxStep label="Confirm">
      <ng-template cngxStepContent><p>Review the order.</p></ng-template>
    </div>
  </cngx-mat-stepper>
  <div class="event-grid" style="margin-top:var(--demo-grid-gap, 12px)">
    <div class="event-row"><span class="event-label">Active step</span><span class="event-value">{{ active() }}</span></div>
  </div>
      </app-example-card>
    </app-doc-shell>
  `,
})
export class MatStepperDemoComponent {
  protected readonly _s0 = 'Same brain, Material skin. Pessimistic mode keeps Material on the origin step until the action resolves; optimistic advances immediately and rolls back on rejection.';
  protected readonly _srcHtml0 = `<div role="group" aria-label="Commit mode" class="event-row" style="gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap">
    <button type="button" class="chip"
            [class.chip--active]="mode() === 'optimistic'"
            [attr.aria-pressed]="mode() === 'optimistic'"
            (click)="mode.set('optimistic')">optimistic</button>
    <button type="button" class="chip"
            [class.chip--active]="mode() === 'pessimistic'"
            [attr.aria-pressed]="mode() === 'pessimistic'"
            (click)="mode.set('pessimistic')">pessimistic</button>
    <label style="margin-inline-start:12px">
      <input type="checkbox"
             [checked]="shouldFail()"
             (change)="shouldFail.set($any($event.target).checked)" />
      simulate error
    </label>
    <label style="margin-inline-start:12px">
      latency
      <input type="range" min="100" max="2000" step="100"
             [value]="latencyMs()"
             (input)="latencyMs.set(+$any($event.target).value)" />
      {{ latencyMs() }}ms
    </label>
  </div>
  <cngx-mat-stepper
    [(activeStepIndex)]="active"
    [commitAction]="commitAction"
    [commitMode]="mode()"
    aria-label="Material async wizard"
  >
    <div cngxStep label="Customer">
      <ng-template cngxStepContent><p>Customer details.</p></ng-template>
    </div>
    <div cngxStep label="Payment">
      <ng-template cngxStepContent><p>Payment method.</p></ng-template>
    </div>
    <div cngxStep label="Confirm">
      <ng-template cngxStepContent><p>Review the order.</p></ng-template>
    </div>
  </cngx-mat-stepper>
  <div class="event-grid" style="margin-top:var(--demo-grid-gap, 12px)">
    <div class="event-row"><span class="event-label">Active step</span><span class="event-value">{{ active() }}</span></div>
  </div>`;
  protected readonly _srcTs0 = `import { Observable } from 'rxjs';
import { CngxStep, CngxStepContent, type CngxStepperCommitAction } from '@cngx/common/stepper';
import { CngxMatStepper } from '@cngx/ui/mat-stepper';


  protected readonly active = signal(0);
  protected readonly mode = signal<'optimistic' | 'pessimistic'>('pessimistic');
  protected readonly shouldFail = signal(false);
  protected readonly latencyMs = signal(800);

  protected readonly commitAction: CngxStepperCommitAction = (from, to) => {
    const ms = this.latencyMs();
    const fail = this.shouldFail();
    return new Observable<boolean>((sub) => {
      const handle = setTimeout(() => {
        if (fail) {
          sub.error(new Error('Server refused step ' + from + ' → ' + to));
        } else {
          sub.next(true);
          sub.complete();
        }
      }, ms);
      return () => clearTimeout(handle);
    });
  };`;

  protected readonly active = signal(0);
  protected readonly mode = signal<'optimistic' | 'pessimistic'>('pessimistic');
  protected readonly shouldFail = signal(false);
  protected readonly latencyMs = signal(800);

  protected readonly commitAction: CngxStepperCommitAction = (from, to) => {
    const ms = this.latencyMs();
    const fail = this.shouldFail();
    return new Observable<boolean>((sub) => {
      const handle = setTimeout(() => {
        if (fail) {
          sub.error(new Error('Server refused step ' + from + ' → ' + to));
        } else {
          sub.next(true);
          sub.complete();
        }
      }, ms);
      return () => clearTimeout(handle);
    });
  };
  
}
