// @generated by scripts/generate-demos.mjs — do not edit manually

import { type Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./home/home.component').then((m) => m.HomeComponent),
  },
  {
    path: 'common',
    children: [
      {
        path: 'behaviors/filter',
        loadComponent: () =>
          import('./demos/common/behaviors/filter-demo/index').then((m) => m.FilterDemoComponent),
      },
      {
        path: 'behaviors/search',
        loadComponent: () =>
          import('./demos/common/behaviors/search-demo/index').then((m) => m.SearchDemoComponent),
      },
      {
        path: 'behaviors/sort',
        loadComponent: () =>
          import('./demos/common/behaviors/sort-demo/index').then((m) => m.SortDemoComponent),
      },
      {
        path: 'data/data-source',
        loadComponent: () =>
          import('./demos/common/data/data-source-demo/index').then((m) => m.DataSourceDemoComponent),
      },
      {
        path: 'data/smart-data-source',
        loadComponent: () =>
          import('./demos/common/data/smart-data-source-demo/index').then((m) => m.SmartDataSourceDemoComponent),
      },
      { path: '', redirectTo: 'behaviors/filter', pathMatch: 'full' },
    ],
  },
  {
    path: 'data-display',
    children: [
      {
        path: 'treetable',
        loadComponent: () =>
          import('./demos/data-display/treetable-demo/index').then((m) => m.TreetableDemoComponent),
      },
      { path: '', redirectTo: 'treetable', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: '' },
];
