// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/ui/stepper/stepper-vertical-demo/stepper-vertical-demo.story.ts

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ExampleCardComponent } from '../../../../shared/example-card.component';
import { DocShellComponent } from '../../../../shared/doc-shell.component';
import { CngxStep, CngxStepContent } from '@cngx/common/stepper';
import { CngxStepper } from '@cngx/ui/stepper';

@Component({
  selector: 'app-stepper-vertical-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxStepper,
    CngxStep,
    CngxStepContent,
  ],
  template: `
    <app-doc-shell title="Stepper — vertical"
      description="<code>[orientation]=&quot;'vertical'&quot;</code> swaps the layout to a 2-column grid: strip in the sidebar, panels on the right. ArrowUp/ArrowDown for keyboard nav."
      [apiComponents]="['CngxStepper']">
      <app-example-card title="Vertical sidebar layout"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0">
        
  <cngx-stepper [(activeStepIndex)]="active" [orientation]="'vertical'" aria-label="Account setup">
    <div cngxStep label="Profile">
      <ng-template cngxStepContent>
        <p>Set your display name and avatar.</p>
      </ng-template>
    </div>
    <div cngxStep label="Notifications">
      <ng-template cngxStepContent>
        <p>Choose which events should email you.</p>
      </ng-template>
    </div>
    <div cngxStep label="Security">
      <ng-template cngxStepContent>
        <p>Enable two-factor authentication.</p>
      </ng-template>
    </div>
    <div cngxStep label="Done">
      <ng-template cngxStepContent>
        <p>You are ready to go.</p>
      </ng-template>
    </div>
  </cngx-stepper>
  <div class="event-grid" style="margin-top:12px"><div class="event-row"><span class="event-label">Active step</span><span class="event-value">{{ active() }}</span></div></div>
      </app-example-card>
    </app-doc-shell>
  `,
})
export class StepperVerticalDemoComponent {
  protected readonly _s0 = 'Same component, only <code>[orientation]</code> changes. The presenter forwards the value to <code>CngxRovingTabindex</code> so the keyboard semantics swap with the layout.';
  protected readonly _srcHtml0 = `<cngx-stepper [(activeStepIndex)]="active" [orientation]="'vertical'" aria-label="Account setup">
    <div cngxStep label="Profile">
      <ng-template cngxStepContent>
        <p>Set your display name and avatar.</p>
      </ng-template>
    </div>
    <div cngxStep label="Notifications">
      <ng-template cngxStepContent>
        <p>Choose which events should email you.</p>
      </ng-template>
    </div>
    <div cngxStep label="Security">
      <ng-template cngxStepContent>
        <p>Enable two-factor authentication.</p>
      </ng-template>
    </div>
    <div cngxStep label="Done">
      <ng-template cngxStepContent>
        <p>You are ready to go.</p>
      </ng-template>
    </div>
  </cngx-stepper>
  <div class="event-grid" style="margin-top:12px"><div class="event-row"><span class="event-label">Active step</span><span class="event-value">{{ active() }}</span></div></div>`;
  protected readonly _srcTs0 = `import { CngxStep, CngxStepContent } from '@cngx/common/stepper';
import { CngxStepper } from '@cngx/ui/stepper';


  protected readonly active = signal(0);`;

  protected readonly active = signal(0);
  
}
