// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/card/card-demo/card-demo.story.ts#section[7] "Interactive Card with Actions"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxCard, CngxCardHeader, CngxCardBody, CngxCardActions } from '@cngx/common/card';

@Component({
  selector: 'app-card-interactive-card-with-actions',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxCard, CngxCardHeader, CngxCardBody, CngxCardActions],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div style="max-width:400px">
        <cngx-card>
          <header cngxCardHeader>
            <h3 style="margin:0;font-weight:600;font-size:1rem">Pflegeplan</h3>
          </header>
          <div cngxCardBody>
            <p style="margin:0;color:var(--text-muted)">Next evaluation: 18.07.2025</p>
          </div>
          <div cngxCardActions align="end">
            <button class="chip">Edit</button>
            <button class="chip">Delete</button>
          </div>
        </cngx-card>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class CardInteractiveCardWithActions {
  protected readonly _exTitle: string = 'Card';
  protected readonly _exDescription: string = 'Semantic card component with three archetypes: display (article), action (button), and link. Supports selection, loading, disabled with reason, and SR live announcements.';
  protected readonly _exSectionTitle: string = 'Interactive Card with Actions';
  protected readonly _exSubtitle: string = 'Multiple independent actions inside. The card itself is <code>role="article"</code> — the buttons carry the interaction.';
  protected readonly _exTs: string = `import { CngxCard, CngxCardHeader, CngxCardBody, CngxCardActions } from '@cngx/common/card';

protected selected = signal(false);
protected loading = signal(false);
protected cardClicked = signal(0);
protected badgeClicked = signal(0);

protected handleBadgeClick(e: MouseEvent): void {
  e.stopPropagation();
  this.badgeClicked.update(n => n + 1);
}`;
  protected readonly _exHtml: string = `<div style="max-width:400px">
  <cngx-card>
    <header cngxCardHeader>
      <h3 style="margin:0;font-weight:600;font-size:1rem">Pflegeplan</h3>
    </header>
    <div cngxCardBody>
      <p style="margin:0;color:var(--text-muted)">Next evaluation: 18.07.2025</p>
    </div>
    <div cngxCardActions align="end">
      <button class="chip">Edit</button>
      <button class="chip">Delete</button>
    </div>
  </cngx-card>
</div>`;
  protected selected = signal(false);
    protected loading = signal(false);
    protected cardClicked = signal(0);
    protected badgeClicked = signal(0);

    protected handleBadgeClick(e: MouseEvent): void {
      e.stopPropagation();
      this.badgeClicked.update(n => n + 1);
    }
}
