// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/layout/backdrop-demo/backdrop-demo.story.ts#section[0] "CngxBackdrop — Overlay with inert"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxBackdrop } from '@cngx/common';

@Component({
  selector: 'app-backdrop-overlay-with-inert',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxBackdrop],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exTags.length > 0 || _exUses.length > 0) {
        <div class="cngx-ex-meta">
          @if (_exTags.length > 0) {
            <ul class="cngx-ex-tags" aria-label="Tags">
              @for (t of _exTags; track t.dim + ':' + t.value) {
                <li class="cngx-ex-tag" [attr.data-dim]="t.dim" [attr.data-value]="t.value">{{ t.value }}</li>
              }
            </ul>
          }
          @if (_exUses.length > 0) {
            <p class="cngx-ex-uses"><span class="cngx-ex-uses__label">uses</span>
              @for (u of _exUses; track u; let last = $last) {
                <code>{{ u }}</code>@if (!last) {<span class="cngx-ex-uses__sep">, </span>}
              }
            </p>
          }
        </div>
      }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="button-row">
        <button class="sort-btn" (click)="showBackdrop.set(true)">Show backdrop</button>
      </div>

      <div style="position: relative; min-height: 200px; border: 1px solid var(--border-color, #e0e0e0); border-radius: 6px; overflow: hidden; margin-top: 0.75rem;">
        <div [cngxBackdrop]="showBackdrop()" (backdropClick)="showBackdrop.set(false); clickCount.update(n => n + 1)"
             class="cngx-backdrop" style="position: absolute;"></div>

        <div style="padding: 1rem;">
          <p>This content becomes <code>inert</code> when the backdrop is visible.</p>
          <button class="sort-btn" (click)="clickCount.update(n => n + 1)">
            Try clicking me (won't work when inert)
          </button>
        </div>
      </div>

      <div class="status-row" style="margin-top: 0.75rem;">
        <span class="status-badge" [class.active]="showBackdrop()">
          {{ showBackdrop() ? 'visible' : 'hidden' }}
        </span>
        <span class="status-badge">clicks: {{ clickCount() }}</span>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class BackdropOverlayWithInert {
  protected readonly _exTitle: string = 'Backdrop';
  protected readonly _exDescription: string = 'Overlay behavior with visibility toggle, click-to-close, and automatic inert toggling on sibling elements for a11y.';
  protected readonly _exSectionTitle: string = 'CngxBackdrop — Overlay with inert';
  protected readonly _exSubtitle: string = 'When visible, <code>[cngxBackdrop]</code> adds <code>inert</code> to all sibling elements — they become unfocusable and non-interactive. Click the backdrop to dismiss.';
  protected readonly _exTags: readonly { dim: string; value: string }[] = [];
  protected readonly _exUses: readonly string[] = ['CngxBackdrop'];
  protected readonly _exTs: string = `import { CngxBackdrop } from '@cngx/common';

protected readonly showBackdrop = signal(false);
protected readonly clickCount = signal(0);`;
  protected readonly _exHtml: string = `<div class="button-row">
  <button class="sort-btn" (click)="showBackdrop.set(true)">Show backdrop</button>
</div>

<div style="position: relative; min-height: 200px; border: 1px solid var(--border-color, #e0e0e0); border-radius: 6px; overflow: hidden; margin-top: 0.75rem;">
  <div [cngxBackdrop]="showBackdrop()" (backdropClick)="showBackdrop.set(false); clickCount.update(n => n + 1)"
       class="cngx-backdrop" style="position: absolute;"></div>

  <div style="padding: 1rem;">
    <p>This content becomes <code>inert</code> when the backdrop is visible.</p>
    <button class="sort-btn" (click)="clickCount.update(n => n + 1)">
      Try clicking me (won't work when inert)
    </button>
  </div>
</div>

<div class="status-row" style="margin-top: 0.75rem;">
  <span class="status-badge" [class.active]="showBackdrop()">
    {{ showBackdrop() ? 'visible' : 'hidden' }}
  </span>
  <span class="status-badge">clicks: {{ clickCount() }}</span>
</div>`;
  protected readonly showBackdrop = signal(false);
    protected readonly clickCount = signal(0);
}
