// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/interactive/click-outside-demo/click-outside-demo.story.ts#section[1] "CngxClickOutside — enabled toggle"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxClickOutside } from '@cngx/common/interactive';

@Component({
  selector: 'app-click-outside-enabled-toggle',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxClickOutside],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <div class="button-row">
        <button class="sort-btn" (click)="enabled.set(!enabled())">
          {{ enabled() ? 'Disable' : 'Enable' }} outside detection
        </button>
        <span class="chip" [class.chip--active]="enabled()">{{ enabled() ? 'enabled' : 'disabled' }}</span>
      </div>

      <div
        cngxClickOutside
        [enabled]="enabled()"
        (clickOutside)="clickCount.update(n => n + 1)"
        style="
          padding: 16px;
          border: 2px dashed var(--cngx-color-border, #aaa);
          border-radius: 6px;
          margin-top: 8px;
          text-align: center;
        "
      >
        Click outside this box
      </div>

      <div class="output-badge" style="margin-top:12px">
        Outside clicks detected: <strong>{{ clickCount() }}</strong>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class ClickOutsideEnabledToggle {
  protected readonly _exTitle: string = 'ClickOutside';
  protected readonly _exDescription: string = 'Emits an event when the user interacts outside the host element. Useful for closing dropdowns, tooltips, and overlays.';
  protected readonly _exSectionTitle: string = 'CngxClickOutside — enabled toggle';
  protected readonly _exSubtitle: string = 'When <code>[enabled]="false"</code> the directive is inactive and no events are emitted.';
  protected readonly _exTs: string = `import { CngxClickOutside } from '@cngx/common/interactive';

protected open = signal(false);
protected clickCount = signal(0);
protected enabled = signal(true);`;
  protected readonly _exHtml: string = `<div class="button-row">
  <button class="sort-btn" (click)="enabled.set(!enabled())">
    {{ enabled() ? 'Disable' : 'Enable' }} outside detection
  </button>
  <span class="chip" [class.chip--active]="enabled()">{{ enabled() ? 'enabled' : 'disabled' }}</span>
</div>

<div
  cngxClickOutside
  [enabled]="enabled()"
  (clickOutside)="clickCount.update(n => n + 1)"
  style="
    padding: 16px;
    border: 2px dashed var(--cngx-color-border, #aaa);
    border-radius: 6px;
    margin-top: 8px;
    text-align: center;
  "
>
  Click outside this box
</div>

<div class="output-badge" style="margin-top:12px">
  Outside clicks detected: <strong>{{ clickCount() }}</strong>
</div>`;
  protected open = signal(false);
    protected clickCount = signal(0);
    protected enabled = signal(true);
}
