// @generated by scripts/generate-demos.mjs — do not edit manually
// Source: demos/forms/field-demo/field-demo.story.ts

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { ExampleCardComponent } from '../../../shared/example-card.component';
import { DocShellComponent } from '../../../shared/doc-shell.component';
import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-field-demo',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ExampleCardComponent,
    DocShellComponent,
    CngxFormField,
    CngxLabel,
    CngxInput,
    CngxHint,
    CngxFieldErrors,
    FormField,
    CngxError,
    CngxFormErrors,
    ReactiveFormsModule,
  ],
  template: `
    <app-doc-shell title="Form Field"
      description="Invisible A11y coordination container for form fields. Strong opinions about ARIA, zero opinions about styling."
      overview="<p><code>cngx-form-field</code> renders as <code>display: contents</code> — it has zero visual footprint. All ARIA coordination (deterministic IDs, <code>aria-describedby</code>, <code>aria-invalid</code>, <code>aria-errormessage</code>, <code>aria-busy</code>, error gating) is handled automatically.</p><p>CSS state classes (<code>.cngx-field--error</code>, <code>.cngx-field--touched</code>, <code>.cngx-field--disabled</code>, etc.) are set on the container, label, and input for easy styling.</p><p>Input directives live in <code>@cngx/forms/input</code>. Material bridge in <code>@cngx/forms/field/material</code>.</p>"
      [apiComponents]="['CngxFormField', 'CngxFormFieldPresenter', 'CngxLabel', 'CngxHint', 'CngxError', 'CngxFieldErrors', 'CngxRequired', 'CngxFormErrors']">
      <app-example-card title="Basic — Label, Input, Hint, Auto Errors"
        [subtitle]="_s0"
        [sourceHtml]="_srcHtml0"
        [sourceTs]="_srcTs0">
        
  <div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="emailField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="emailField" placeholder="max@example.com" />
        <span cngxHint>Business address</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="passwordField">
        <label cngxLabel>Password</label>
        <input cngxInput [formField]="passwordField" type="password" placeholder="At least 8 characters" />
        <span cngxHint>8-64 characters</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="touchLogin()">Touch all fields</button>
    <div class="status-row">
      <span class="status-badge">Email touched: {{ emailField().touched() }}</span>
      <span class="status-badge">Email valid: {{ emailField().valid() }}</span>
    </div>
  </div>
      </app-example-card>
      <app-example-card title="Manual Error Template"
        [subtitle]="_s1"
        [sourceHtml]="_srcHtml1"
        [sourceTs]="_srcTs1"
        [sourceCss]="_srcCss1">
        
  <div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="manualEmailField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="manualEmailField" placeholder="max@example.com" />
        <div cngxError class="demo-errors">
          @for (err of manualEmailField().errors(); track err.kind) {
            <span>{{ err.message ?? err.kind }}</span>
          }
        </div>
      </cngx-form-field>
    </div>
    <button class="chip" (click)="manualEmailField().markAsTouched()">Touch email</button>
  </div>
      </app-example-card>
      <app-example-card title="Disabled Field with Reasons"
        [subtitle]="_s2"
        [sourceHtml]="_srcHtml2"
        [sourceTs]="_srcTs2"
        [sourceCss]="_srcCss2">
        
  <div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="disabledPwField">
        <label cngxLabel>Password</label>
        <input cngxInput [formField]="disabledPwField" type="password" placeholder="Type to enable confirm" />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="confirmField">
        <label cngxLabel>Confirm Password</label>
        <input cngxInput [formField]="confirmField" type="password" placeholder="Re-enter password" />
        <span cngxHint>Must match password</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="status-row">
      <span class="status-badge">Disabled: {{ confirmField().disabled() }}</span>
    </div>
    @for (reason of confirmField().disabledReasons(); track $index) {
      <div class="demo-disabled-reason">{{ reason.message }}</div>
    }
  </div>
      </app-example-card>
      <app-example-card title="ARIA Inspection"
        [subtitle]="_s3"
        [sourceHtml]="_srcHtml3"
        [sourceTs]="_srcTs3">
        
  <div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="ariaEmailField">
        <label cngxLabel>Inspect this input</label>
        <input cngxInput [formField]="ariaEmailField" placeholder="Open DevTools, inspect me"
          style="border: 2px dashed var(--cngx-border,#aaa)" />
        <span cngxHint>Check aria-describedby, aria-required, aria-invalid</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
  </div>
  <pre class="code-block" style="margin-top:16px"><code>&lt;cngx-form-field class="cngx-field--required cngx-field--error cngx-field--touched"&gt;
  &lt;label class="cngx-label--required cngx-label--error"
         id="cngx-email-label" for="cngx-email-input"&gt;...&lt;/label&gt;
  &lt;input class="cngx-input--error cngx-input--focused"
         id="cngx-email-input"
         aria-describedby="cngx-email-hint cngx-email-error"
         aria-labelledby="cngx-email-label"
         aria-required="true"
         aria-invalid="true"
         aria-errormessage="cngx-email-error" /&gt;
&lt;/cngx-form-field&gt;</code></pre>
      </app-example-card>
      <app-example-card title="Error Summary + Focus First Error"
        [subtitle]="_s4"
        [sourceHtml]="_srcHtml4"
        [sourceTs]="_srcTs4">
        
  <div class="demo-form">
    <cngx-form-errors [fields]="[firstNameField, lastNameField, emailAddrField]" [show]="submitted()" />
    <div class="demo-field">
      <cngx-form-field [field]="firstNameField">
        <label cngxLabel>First Name</label>
        <input cngxInput [formField]="firstNameField" placeholder="Jane" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="lastNameField">
        <label cngxLabel>Last Name</label>
        <input cngxInput [formField]="lastNameField" placeholder="Doe" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="emailAddrField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="emailAddrField" placeholder="jane@example.com" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="handleSubmit()">Submit</button>
    @if (submitMessage()) {
      <div class="status-row">
        <span class="status-badge">{{ submitMessage() }}</span>
      </div>
    }
  </div>
      </app-example-card>
      <app-example-card title="Reactive Forms Adapter"
        [subtitle]="_s5"
        [sourceHtml]="_srcHtml5"
        [sourceTs]="_srcTs5">
        
  <div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="reactiveField">
        <label cngxLabel>E-Mail (Reactive Forms)</label>
        <input cngxInput [formControl]="reactiveControl" placeholder="max@example.com" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="reactiveControl.markAsTouched()">Touch</button>
    <div class="status-row">
      <span class="status-badge">Touched: {{ reactiveControl.touched }}</span>
      <span class="status-badge">Valid: {{ reactiveControl.valid }}</span>
    </div>
  </div>
      </app-example-card>
    </app-doc-shell>
  `,
})
export class FieldDemoComponent {
  protected readonly _s0 = '<code>CngxFieldErrors</code> auto-renders from the <code>CNGX_ERROR_MESSAGES</code> registry. Errors appear after touch. CSS classes toggle automatically for styling.';
  protected readonly _s1 = 'Use <code>[cngxError]</code> for full control over error rendering.';
  protected readonly _s2 = 'Signal Forms <code>disabled()</code> accepts a string reason. Type in the password field to enable confirm.';
  protected readonly _s3 = 'Inspect the input in DevTools. Deterministic IDs, ARIA attributes, and CSS classes toggle automatically.';
  protected readonly _s4 = '<code>CngxFormErrors</code> shows a WCAG 3.3.1 error summary. <code>focusFirstError()</code> jumps to the first invalid field.';
  protected readonly _s5 = '<code>adaptFormControl()</code> wraps an <code>AbstractControl</code> for use without Signal Forms.';
  protected readonly _srcHtml0 = `<div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="emailField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="emailField" placeholder="max@example.com" />
        <span cngxHint>Business address</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="passwordField">
        <label cngxLabel>Password</label>
        <input cngxInput [formField]="passwordField" type="password" placeholder="At least 8 characters" />
        <span cngxHint>8-64 characters</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="touchLogin()">Touch all fields</button>
    <div class="status-row">
      <span class="status-badge">Email touched: {{ emailField().touched() }}</span>
      <span class="status-badge">Email valid: {{ emailField().valid() }}</span>
    </div>
  </div>`;
  protected readonly _srcTs0 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;
  protected readonly _srcHtml1 = `<div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="manualEmailField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="manualEmailField" placeholder="max@example.com" />
        <div cngxError class="demo-errors">
          @for (err of manualEmailField().errors(); track err.kind) {
            <span>{{ err.message ?? err.kind }}</span>
          }
        </div>
      </cngx-form-field>
    </div>
    <button class="chip" (click)="manualEmailField().markAsTouched()">Touch email</button>
  </div>`;
  protected readonly _srcTs1 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;
  protected readonly _srcCss1 = `.demo-errors { font-size: 0.75rem; color: var(--cngx-field-error-color, #d32f2f); display: flex; flex-direction: column; gap: 2px; }`;
  protected readonly _srcHtml2 = `<div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="disabledPwField">
        <label cngxLabel>Password</label>
        <input cngxInput [formField]="disabledPwField" type="password" placeholder="Type to enable confirm" />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="confirmField">
        <label cngxLabel>Confirm Password</label>
        <input cngxInput [formField]="confirmField" type="password" placeholder="Re-enter password" />
        <span cngxHint>Must match password</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="status-row">
      <span class="status-badge">Disabled: {{ confirmField().disabled() }}</span>
    </div>
    @for (reason of confirmField().disabledReasons(); track $index) {
      <div class="demo-disabled-reason">{{ reason.message }}</div>
    }
  </div>`;
  protected readonly _srcTs2 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;
  protected readonly _srcCss2 = `.demo-disabled-reason { font-size: 0.75rem; color: var(--cngx-field-hint-color, #888); font-style: italic; }`;
  protected readonly _srcHtml3 = `<div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="ariaEmailField">
        <label cngxLabel>Inspect this input</label>
        <input cngxInput [formField]="ariaEmailField" placeholder="Open DevTools, inspect me"
          style="border: 2px dashed var(--cngx-border,#aaa)" />
        <span cngxHint>Check aria-describedby, aria-required, aria-invalid</span>
        <cngx-field-errors />
      </cngx-form-field>
    </div>
  </div>
  <pre class="code-block" style="margin-top:16px"><code>&lt;cngx-form-field class="cngx-field--required cngx-field--error cngx-field--touched"&gt;
  &lt;label class="cngx-label--required cngx-label--error"
         id="cngx-email-label" for="cngx-email-input"&gt;...&lt;/label&gt;
  &lt;input class="cngx-input--error cngx-input--focused"
         id="cngx-email-input"
         aria-describedby="cngx-email-hint cngx-email-error"
         aria-labelledby="cngx-email-label"
         aria-required="true"
         aria-invalid="true"
         aria-errormessage="cngx-email-error" /&gt;
&lt;/cngx-form-field&gt;</code></pre>`;
  protected readonly _srcTs3 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;
  protected readonly _srcHtml4 = `<div class="demo-form">
    <cngx-form-errors [fields]="[firstNameField, lastNameField, emailAddrField]" [show]="submitted()" />
    <div class="demo-field">
      <cngx-form-field [field]="firstNameField">
        <label cngxLabel>First Name</label>
        <input cngxInput [formField]="firstNameField" placeholder="Jane" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="lastNameField">
        <label cngxLabel>Last Name</label>
        <input cngxInput [formField]="lastNameField" placeholder="Doe" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <div class="demo-field">
      <cngx-form-field [field]="emailAddrField">
        <label cngxLabel>E-Mail</label>
        <input cngxInput [formField]="emailAddrField" placeholder="jane@example.com" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="handleSubmit()">Submit</button>
    @if (submitMessage()) {
      <div class="status-row">
        <span class="status-badge">{{ submitMessage() }}</span>
      </div>
    }
  </div>`;
  protected readonly _srcTs4 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;
  protected readonly _srcHtml5 = `<div class="demo-form">
    <div class="demo-field">
      <cngx-form-field [field]="reactiveField">
        <label cngxLabel>E-Mail (Reactive Forms)</label>
        <input cngxInput [formControl]="reactiveControl" placeholder="max@example.com" />
        <cngx-field-errors />
      </cngx-form-field>
    </div>
    <button class="chip" (click)="reactiveControl.markAsTouched()">Touch</button>
    <div class="status-row">
      <span class="status-badge">Touched: {{ reactiveControl.touched }}</span>
      <span class="status-badge">Valid: {{ reactiveControl.valid }}</span>
    </div>
  </div>`;
  protected readonly _srcTs5 = `import { form, schema, required, email, minLength, maxLength, disabled, submit, FormField } from '@angular/forms/signals';
import { CngxFormField, CngxLabel, CngxHint, CngxError, CngxFieldErrors, CngxFormErrors, focusFirstError, adaptFormControl } from '@cngx/forms/field';
import { CngxInput } from '@cngx/forms/input';
import { FormControl, Validators, ReactiveFormsModule } from '@angular/forms';


  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');`;

  // ── Login form (Sections 1, 2, 4) ────────────────────────
  private readonly model = signal({ email: '', password: '' });
  private readonly loginSchema = schema<{ email: string; password: string }>(root => {
    required(root.email);
    email(root.email);
    required(root.password);
    minLength(root.password, 8);
    maxLength(root.password, 64);
  });
  protected readonly loginForm = form(this.model, this.loginSchema);
  protected readonly emailField = this.loginForm.email;
  protected readonly passwordField = this.loginForm.password;

  protected touchLogin(): void {
    this.emailField().markAsTouched();
    this.passwordField().markAsTouched();
  }

  // ── Manual error form (Section 2) ───────────────────────
  private readonly manualModel = signal({ email: '' });
  private readonly manualSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly manualForm = form(this.manualModel, this.manualSchema);
  protected readonly manualEmailField = this.manualForm.email;

  // ── ARIA inspection form (Section 4) ───────────────────
  private readonly ariaModel = signal({ email: '' });
  private readonly ariaSchema = schema<{ email: string }>(root => {
    required(root.email);
    email(root.email);
  });
  protected readonly ariaForm = form(this.ariaModel, this.ariaSchema);
  protected readonly ariaEmailField = this.ariaForm.email;

  // ── Disabled-reasons form (Section 3) ────────────────────
  private readonly disabledModel = signal({ password: '', confirmPassword: '' });
  private readonly disabledSchema = schema<{ password: string; confirmPassword: string }>(root => {
    required(root.password);
    minLength(root.password, 8);
    required(root.confirmPassword);
    disabled(root.confirmPassword, () => !this.disabledModel().password ? 'Enter a password first' : false);
  });
  protected readonly disabledForm = form(this.disabledModel, this.disabledSchema);
  protected readonly disabledPwField = this.disabledForm.password;
  protected readonly confirmField = this.disabledForm.confirmPassword;

  // ── Submit form (Section 5) ──────────────────────────────
  private readonly submitModel = signal({ firstName: '', lastName: '', emailAddr: '' });
  private readonly submitSchema = schema<{ firstName: string; lastName: string; emailAddr: string }>(root => {
    required(root.firstName);
    required(root.lastName);
    required(root.emailAddr);
    email(root.emailAddr);
  });
  protected readonly submitForm = form(this.submitModel, this.submitSchema);
  protected readonly firstNameField = this.submitForm.firstName;
  protected readonly lastNameField = this.submitForm.lastName;
  protected readonly emailAddrField = this.submitForm.emailAddr;
  protected readonly submitted = signal(false);
  protected readonly submitMessage = signal('');

  protected async handleSubmit(): Promise<void> {
    this.submitMessage.set('');
    this.submitted.set(true);
    const success = await submit(this.submitForm, async () => {
      this.submitMessage.set('Form submitted successfully!');
    });
    if (!success) {
      this.submitMessage.set('Validation failed — focus moved to first error.');
      focusFirstError(this.submitForm);
    }
  }

  // ── Reactive Forms adapter (Section 6) ───────────────────
  protected readonly reactiveControl = new FormControl('', [Validators.required, Validators.email]);
  protected readonly reactiveField = adaptFormControl(this.reactiveControl, 'reactiveEmail');
  
}
