// @generated by scripts/generate-examples.mjs — do not edit manually
// Source: dev-app/src/app/demos/common/interactive/context-menu-demo/context-menu-demo.story.ts#section[0] "Right-click target zone"

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CngxContextMenuTrigger, CngxMenu, CngxMenuItem, CngxMenuSeparator } from '@cngx/common/interactive';
import { CngxPopover } from '@cngx/common/popover';

@Component({
  selector: 'app-context-menu-right-click-target-zone',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CngxContextMenuTrigger, CngxMenu, CngxMenuItem, CngxMenuSeparator, CngxPopover],
  template: `
    <header class="cngx-ex-intro">
      @if (_exTitle) { <h1>{{ _exTitle }}</h1> }
      @if (_exDescription) { <p [innerHTML]="_exDescription"></p> }
      @if (_exSectionTitle && _exSectionTitle !== _exTitle) { <h2>{{ _exSectionTitle }}</h2> }
      @if (_exSubtitle) { <p class="cngx-ex-hint" [innerHTML]="_exSubtitle"></p> }
    </header>
    <style>
        .zone { display: flex; align-items: center; justify-content: center; min-height: 160px; padding: 16px; border: 2px dashed #c7cdd6; border-radius: 8px; background: #f9fafb; color: #475569; cursor: context-menu; user-select: none; }
        .zone:focus-visible { outline: 2px solid #4a8cff; outline-offset: 2px; }
        .pop { padding: 4px; min-width: 200px; border: 1px solid #d0d5dd; border-radius: 6px; background: #fff; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
        .menu { list-style: none; margin: 0; padding: 0; outline: none; }
        .menu [cngxMenuItem] { padding: 6px 10px; border-radius: 4px; cursor: pointer; user-select: none; }
        .menu [cngxMenuItem]:hover, .menu .cngx-menu-item--highlighted { background: rgba(74, 140, 255, 0.15); }
        .menu [cngxMenuSeparator] { display: block; height: 1px; margin: 4px 6px; background: #e5e7eb; list-style: none; }
      </style>
      <div
        class="zone"
        tabindex="0"
        [cngxContextMenuTrigger]="ctx"
        [popover]="pop"
      >
        Right-click here (or focus + Shift+F10)
      </div>
      <div cngxPopover #pop="cngxPopover" placement="bottom-start" class="pop">
        <ul
          cngxMenu
          [label]="'Context actions'"
          class="menu"
          tabindex="0"
          #ctx="cngxMenu"
          (itemActivated)="lastAction.set($any($event)); pop.hide()"
        >
          <li cngxMenuItem value="cut">Cut</li>
          <li cngxMenuItem value="copy">Copy</li>
          <li cngxMenuItem value="paste">Paste</li>
          <li cngxMenuSeparator></li>
          <li cngxMenuItem value="delete">Delete</li>
        </ul>
      </div>
      <div class="event-grid" style="margin-top:12px">
        <div class="event-row">
          <span class="event-label">Last action</span>
          <span class="event-value">{{ lastAction() ?? '—' }}</span>
        </div>
      </div>
    <details class="cngx-ex-code">
      <summary>TypeScript</summary>
      <pre><code>{{ _exTs }}</code></pre>
    </details>
    <details class="cngx-ex-code">
      <summary>Template</summary>
      <pre><code>{{ _exHtml }}</code></pre>
    </details>
  `,
})
export class ContextMenuRightClickTargetZone {
  protected readonly _exTitle: string = 'Context Menu Trigger';
  protected readonly _exDescription: string = 'Right-click or Shift+F10 opens a CngxMenu inside a CngxPopover anchored at the pointer location. Escape closes; arrow keys navigate.';
  protected readonly _exSectionTitle: string = 'Right-click target zone';
  protected readonly _exSubtitle: string = 'Right-click anywhere inside the dashed zone, or focus it and press Shift+F10. Escape closes the menu.';
  protected readonly _exTs: string = `import { CngxContextMenuTrigger, CngxMenu, CngxMenuItem, CngxMenuSeparator } from '@cngx/common/interactive';
import { CngxPopover } from '@cngx/common/popover';

protected readonly lastAction = signal<string | null>(null);`;
  protected readonly _exHtml: string = `<style>
  .zone { display: flex; align-items: center; justify-content: center; min-height: 160px; padding: 16px; border: 2px dashed #c7cdd6; border-radius: 8px; background: #f9fafb; color: #475569; cursor: context-menu; user-select: none; }
  .zone:focus-visible { outline: 2px solid #4a8cff; outline-offset: 2px; }
  .pop { padding: 4px; min-width: 200px; border: 1px solid #d0d5dd; border-radius: 6px; background: #fff; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
  .menu { list-style: none; margin: 0; padding: 0; outline: none; }
  .menu [cngxMenuItem] { padding: 6px 10px; border-radius: 4px; cursor: pointer; user-select: none; }
  .menu [cngxMenuItem]:hover, .menu .cngx-menu-item--highlighted { background: rgba(74, 140, 255, 0.15); }
  .menu [cngxMenuSeparator] { display: block; height: 1px; margin: 4px 6px; background: #e5e7eb; list-style: none; }
</style>
<div
  class="zone"
  tabindex="0"
  [cngxContextMenuTrigger]="ctx"
  [popover]="pop"
>
  Right-click here (or focus + Shift+F10)
</div>
<div cngxPopover #pop="cngxPopover" placement="bottom-start" class="pop">
  <ul
    cngxMenu
    [label]="'Context actions'"
    class="menu"
    tabindex="0"
    #ctx="cngxMenu"
    (itemActivated)="lastAction.set($any($event)); pop.hide()"
  >
    <li cngxMenuItem value="cut">Cut</li>
    <li cngxMenuItem value="copy">Copy</li>
    <li cngxMenuItem value="paste">Paste</li>
    <li cngxMenuSeparator></li>
    <li cngxMenuItem value="delete">Delete</li>
  </ul>
</div>`;
  protected readonly lastAction = signal<string | null>(null);
}
